### ISSUE TITLE
Sketch widget generate KML file 

### ISSUE THREAD

**Issue by rpateld** [Esri/arcgis-rest-js#1004]
Is it possible that the [Sketch ](https://developers.arcgis.com/javascript/latest/sample-code/sketch-geometries/)widget can generate a KML file?

**Comment by gavinr** [comment]
Hi @rpateld, thank you for the question, but this repository is only for the **ArcGIS REST JS** project. The Sketch widget is in the **ArcGIS API for JavaScript**. Please see https://developers.arcgis.com/support/ for options for questions/support about the ArcGIS API for JavaScript, specifically you probably want to visit the [Esri Community](https://community.esri.com/t5/arcgis-api-for-javascript/ct-p/arcgis-api-for-javascript).
