### ISSUE TITLE
4.x ArcGISIdentityManager does not have its redirectUri property set

### ISSUE THREAD

**Issue by desjardinsm** [Esri/arcgis-rest-js#1006]
I don't think this is exactly the same issue as #995 (apologies if it is). The other issue seems to have more to do with calling `completeOAuth2` with query parameters on the `redirect_uri`, but in this case `completeOAuth2` otherwise works fine. 

After `completeOAuth2` returns a valid `ArcGISIdentityManager`, it does not have its `redirect_uri` property set (and it is marked as a read-only property in the TypeScript definition file, so it cannot be manually set without having to ignore the type error).

Then, when a token expires (or it is invalidated), it does automatically call the token endpoint for a `exchange_refresh_token`, but it doesn't have a `redirect_uri` so the endpoint returns a 400 error (`redirect_uri not specified`). I'm not sure if this is intended design or if we are supposed to be exchanging a token manually.

It's also still possible to set the `redirect_uri` property manually (and ignoring the type errors from modifying a readonly property), which does work and automatically calls the token endpoint with that `redirect_uri` if the token is ever found to be invalid.

**Comment by patrickarlt** [comment]
This is a bug. `completeOAuth2` should pass the redirect URL into the new instance of `ArcGISIdentityManager` from the options.

After a user clicks a sign in button

```
ArcGISIdentityManager.beginOAuth2({
  clientId: "ABC123...",
  popup: true,
  redirectUri: "https://myapp.com/authorize.html",
});
```

After authorizing on https://myapp.com/authorize.html:

```
ArcGISIdentityManager.completeOAuth2({
  clientId: "ABC123...",
  popup: true,
  redirectUri: "https://myapp.com/authorize.html"
})
```

We should add the redirect URL [here when we create the instance of `ArcGISIdentityManager`](https://github.com/Esri/arcgis-rest-js/blob/main/packages/arcgis-rest-request/src/ArcGISIdentityManager.ts#L578-L587) from the options. We should also update the docs to mention that you should pass the same `redirectUrl` in as well.
