### ISSUE TITLE
searchItems does not respect filter as parameter in v4

### ISSUE THREAD

**Issue by cooney** [Esri/arcgis-rest-js#1009]
After updating our dependencies to v4, we found a breaking change with the use of `searchItems` that no longer respects `filter` as a parameter.  A workaround is to pass filter as part of the `params` object.

**Comment by gavinr** [comment]
Thank you for the report!

It looks like `"filter", "countFields", "countSize", "categories", "categoryFilters"` were all added to the v3 branch in #928. Our [plan](https://github.com/Esri/arcgis-rest-js/pull/928#issuecomment-951143025) was to port this back to the v4 branch but I guess that never happened. So I think we just need to copy those changes to the new main (v4) branch. PRs welcome.

**Comment by gavinr** [comment]
Released in v4.0.4
