### ISSUE TITLE
Incorrect path for "browser" field in package.json

### ISSUE THREAD

**Issue by jluna** [Esri/arcgis-rest-js#101]
### Problem
When building a bundle with `browserify`, I received the very unhelpful error message that the module could not be found even though it was installed in `./node_modules` via npm.

`Error: Cannot find module './node_modules/@esri/arcgis-rest-auth'`

### Solution
After much confusion, poking, and prodding. I realized that the "browser" path hint in `package.json` was pointing to the wrong location.  After fixing this locally browserify was able to find the correct distribution and build the bundle.

### Example
https://github.com/Esri/arcgis-rest-js/blob/master/packages/arcgis-rest-request/package.json#L6
Presumably it's an issue for all packages.

**Comment by jgravois** [comment]
thanks for the heads up @jluna! are you interested in submitting a Pull Request with the fix?
