### ISSUE TITLE
processParams not converting extent to string

### ISSUE THREAD

**Issue by benstoltz** [Esri/arcgis-rest-js#1023]
### Describe the bug

`addItem` and `updateItem` both expect `extent` to be a flattened string instead of a bbox ( `1, 2, 3, 4` vs `[[1, 2], [3, 4]]` ). Apparently around two years ago we made a change to `processParams` ( #779 ) for catalog to allow array of arrays through. At that time it was decided to do that for all the cases so as to not make an explicit reference to a property. Unfortunately that has broken `extent`. What ends up happening is in the actual request the bbox is split into two different extent params, the create/update call succeeds, however the item ends up with an extent which is simply an empty array.

### Reproduction

Will be provided

### System Info

```shell
v3.4.3
```

**Comment by gavinr** [comment]
Closing per @dbouwman.
