### ISSUE TITLE
Inconsistent signatures...

### ISSUE THREAD

**Issue by dbouwman** [Esri/arcgis-rest-js#104]
`searchItems` and `searchGroups` signatures are inconsistent;

`searchItems(search: string | ISearchRequestOptions) : Promise<ISearchResult>` has one arg...
and `ISearchRequestOptions` contains a `searchForm`...

where as `searchGroups` takes the `searchForm` as the first arg.

`searchGroups(searchForm: IGroupSearchRequest, requestOptions: IRequestOptions)`

Either is fine, but consistency makes the lib much easier to work with.

As we port the ember-arcgis-portal-services over to using this lib, I'm sure we will find other things like this :)

**Comment by jgravois** [comment]
assigning to myself. i'd like to reorganize the way actual search parameters are supplied entirely.

**Comment by jgravois** [comment]
tracking in #137
