### ISSUE TITLE
Latest `gh-pages` update broke 4.x doc build

### ISSUE THREAD

**Issue by araedavis** [Esri/arcgis-rest-js#1054]
It looks like every time `gh-pages` gets auto-updated with commits, it's wiping out the `4/**` directory that we use on https://devtopia.esri.com/ArcGISDevelopers/open-source-and-third-party-doc to build the rest-js API Reference on the developers' website. 

@patrickarlt manually fixed this a couple weeks ago in 993d5f3a0ca32d9519968c9a105bf7ca34d179ec but it looks like https://github.com/Esri/arcgis-rest-js/commit/1a9ba744ccbf299050916896083f94b1897b6de8 wiped out the directory again. 

@patrickarlt @gavinr @tomwayson is there a way to adjust the tooling so we either build the 4.x `typedoc.json` file somewhere else, or that this gets built and updated automatically from the `gh-pages` branch? 

Thanks all!

**Comment by patrickarlt** [comment]
This should be resolved. I've also removed the automated doc build for 3.x so this shouldn't happen again.

**Comment by araedavis** [comment]
Yes, this is fixed now - closing
