### ISSUE TITLE
Portal / AGOL only or also ArcGIS Server

### ISSUE THREAD

**Issue by JeffJacobson** [Esri/arcgis-rest-js#106]
So far it seems this project only contains code for calling Portal or ArcGIS Online. Will support for [ArcGIS Server services](https://developers.arcgis.com/rest/services-reference/get-started-with-the-services-directory.htm) be added at some point, or is that beyond the intended scope of this project?

At the moment, I am tasked with creating a JavaScript application that will call the [Esri Linear Referencing REST API](http://roadsandhighwayssample.esri.com/roads/api/index.html), which is part of the [Roads and Highways](https://enterprise.arcgis.com/en/roads-highways/) product. Should I fork and add the LRS API support code as a new package within this project, or should I just create a new project that references *@esri/arcgis-rest-request* as a dependency?

**Comment by jgravois** [comment]
we currently include support for calling ArcGIS Server geocoding services in the [`arcgis-rest-geocoder`](https://github.com/Esri/arcgis-rest-js/tree/master/packages/arcgis-rest-geocoder) package. the next thing we have our eyes on are packages for querying, editing and administering feature services, whether they're published to ArcGIS Enterprise _or_ ArcGIS Online.

> Should I fork and add the LRS API support code as a new package within this project, or should I just create a new project that references @esri/arcgis-rest-request as a dependency?

i'd be happy with either choice! especially if you're willing to share feedback about what is working as you expected and what isn't. obviously your application logic is your own, but a seperate package makes sense if you are interested in writing generic methods that other developers could use as building blocks. it could ultimately live in this repo or anywhere else.

**Comment by tomwayson** [comment]
@JeffJacobson 

Yes, we intend to add the capability to call feature service endpoints (see #46). However, beyond the initial API design no work has been done to my knowledge. It's on my "before devsummit" todo list.

What @jgravois said re: fork vs depend on. Personally I'd lean towards you creating a new lib that depends on @esri/arcgis-rest-request.

**Comment by JeffJacobson** [comment]
OK, I'll make a new lib and reference @esri/arcgis-rest-request.
Thanks.
