### ISSUE TITLE
Cannot run npm install or build project on M1 Mac

### ISSUE THREAD

**Issue by juliannaeapicella** [Esri/arcgis-rest-js#1060]
### Describe the bug

When attempting to initialize the repository on my M1 Mac, I got this error:
<img width="570" alt="MicrosoftTeams-image (4)" src="https://user-images.githubusercontent.com/42875581/210598127-4eaa7906-3d96-4163-8bf6-fa0bc9f8bd89.png">

It seems older versions of chrome driver are not supported on this new architecture. This is a dependency of the "inspect-process" package, which is on its most current version. This package may need to be removed and/or replaced in order for this repository to run on newer machines.

I also received errors relating to the node-sass package. I am unsure if this is related to the M1 chip, however.

### Reproduction

Device: 
MacBook Pro, 16-inch, 2021
Apple M1 Pro Chip
macOS Ventura 13.1

1) Attempt to run npm install, npm i, or npm build
2) Observe failure

### Logs

```shell
npm ERR! code 1
npm ERR! path /Users/jul11634/Documents/GitHub/arcgis-rest-js/node_modules/chromedriver
npm ERR! command failed
npm ERR! command sh -c node install.js
npm ERR! Only Mac 64 bits supported.
```

### System Info

```shell
v3.5.1
System:
  OS: macOS 13.1
  CPU: (10) arm64 Apple M1 Pro
  Memory: 4.78 GB / 32.00 GB
  Shell: 3.2.57 - /bin/bash
Binaries:
  Node: 16.14.0 - ~/.volta/tools/image/node/16.14.0/bin/node
  Yarn: 1.22.15 - ~/.volta/tools/image/yarn/1.22.15/bin/yarn
  npm: 8.3.1 - ~/.volta/tools/image/node/16.14.0/bin/npm
  Watchman: 2022.03.14.00 - /opt/homebrew/bin/watchman
Browsers:
  Chrome: 108.0.5359.124
  Firefox: 107.0.1
  Safari: 16.2
```

**Comment by gavinr** [comment]
Thank you for logging this issue. I do not have a M1 Mac so cannot reproduce this, but I did do some searching. It seems like this is a common issue across the JS project ecosystem, for example:

- https://www.google.com/search?hl=en&q=%22node_modules%2Fchromedriver%22%20%22Only%20Mac%2064%20bits%20supported%22
- https://github.com/webrtc/samples/issues/1431
- https://github.com/vuejs/vue/issues/12031

Have you tried any of those local solutions?

**Comment by juliannaeapicella** [comment]
> Thank you for logging this issue. I do not have a M1 Mac so cannot reproduce this, but I did do some searching. It seems like this is a common issue across the JS project ecosystem, for example:
> 
> * https://www.google.com/search?hl=en&q=%22node_modules%2Fchromedriver%22%20%22Only%20Mac%2064%20bits%20supported%22
> * [Unable to 'npm install' on Apple Silicon MacBook webrtc/samples#1431](https://github.com/webrtc/samples/issues/1431)
> * [Cannot run npm install on macbook m1 vuejs/vue#12031](https://github.com/vuejs/vue/issues/12031)
> 
> Have you tried any of those local solutions?

@gavinr I have tried these, but we don't actually use chromedriver as a direct dependency. It's a dependency of inspect-process, so I can't update the version it uses. In order to build the project, I essentially have to remove it.

**Comment by patrickarlt** [comment]
@gavinr @juliannaeapicella I think we might be able to remove `inspect-process`. If you can still run the node debugging scripts with `inspect-process` removed then we are fine. https://github.com/Esri/arcgis-rest-js/blob/main/package.json#L31-L33 

Previously I setup `inspect-process` but at some point I removed it in favor of just `node --inspect`.

If there are other problematic packages we can evaluate moving them to `optionalDependencies`

**Comment by juliannaeapicella** [comment]
@patrickarlt It seems node-sass may also be an issue.

**Comment by patrickarlt** [comment]
@juliannaeapicella `node-sass` was previously needed in 3.x for the doc site. It can be moved to `optionalDependencies`

**Comment by gavinr** [comment]
@juliannaeapicella since node-sass was removed in #1072, is this now working for you? cc @dbouwman
