### ISSUE TITLE
OAuth2 flow fails when using hash routing in single-page applications

### ISSUE THREAD

**Issue by philnagel** [Esri/arcgis-rest-js#1070]
### Describe the bug

When using has routing in single-page applications (in my case, `vue-router` in `VueJS` with the [hash history mode](https://router.vuejs.org/guide/essentials/history-mode.html#hash-mode) enabled), the PKCE-based OAuth2 flow fails. I think this is caused by the fact that in this case, the authentication page that runs `completeOAuth2()` will have a URL with both a hash and a search component. This requires special handling to correctly parse this type of URL.

Specifically, this error is returned even when everything else should enable a succesful authentication:

```
Uncaught (in promise) ArcGISAuthError: no-auth-state: No authentication state was found, call `ArcGISIdentityManager.beginOAuth2(...)` to start the authentication process.
```

### Reproduction

I've created a repository with the necessary code to reproduce this issue in `VueJS` [here](https://github.com/philnagel/oauth-bug).
The readme of that repo should outline the steps needed to reproduce - let me know of any questions or need for clarification.

The demo shows that the auth flow works fine when using HTML5 history mode, which does not leverage `#` in the route URL. By only changing the router history mode, the flow fails when all else remains equal.

### Logs

```shell
Uncaught (in promise) ArcGISAuthError: no-auth-state: No authentication state was found, call `ArcGISIdentityManager.beginOAuth2(...)` to start the authentication process.
```

### System Info

```shell
@esri/arcgis-rest-request: 4.1.1

  System:
    OS: macOS 13.1
    CPU: (10) arm64 Apple M1 Max
    Memory: 19.38 GB / 64.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.16.0 - ~/.volta/tools/image/node/16.16.0/bin/node
    Yarn: 1.22.19 - ~/.volta/tools/image/yarn/1.22.19/bin/yarn
    npm: 8.11.0 - ~/.volta/tools/image/node/16.16.0/bin/npm
  Browsers:
    Brave Browser: 105.1.43.93
    Chrome: 109.0.5414.87
    Firefox: 108.0.2
    Safari: 16.2
```

**Comment by patrickarlt** [comment]
Closing see https://github.com/Esri/arcgis-rest-js/pull/1071#issuecomment-1425085829
