### ISSUE TITLE
Typescript definition for IWebmap in v4

### ISSUE THREAD

**Issue by bamse16** [Esri/arcgis-rest-js#1079]
### Describe the problem

Hello,

I'm trying to migrate a Typescript project using `@esri/arcgis-rest-*` from v3 to v4.

In the process of converting the existing types, I couldn't find the definition for `IWebmap`.

Is there a plan to bring that back? What's the migration path for projects using Typescript?

Thank you

### Describe the proposed solution

Add IWebmap type to v4.

**Comment by patrickarlt** [comment]
Hi @bamse16 we decided to remove the web map types at 4.0. We simply got too many issues about missing/incorrect types and the webmap types aren't actually used anywhere in REST JS and generally fell outside the scope of the project.

You can however continue to use `@esri/arcgis-rest-types` at version 3.6.0 with the rest of ArcGIS REST JS 4.0. Just know that we aren't going to be updating the types.

**Comment by bamse16** [comment]
Not adding types going forward works fine to you, however it does not work out for those using the API with TypeScript (node.js or React).

I hope you'll reconsider and keep those packages up to date, so people would not be discouraged to upgrade to 4.x.
