### ISSUE TITLE
Geocoding postal code type

### ISSUE THREAD

**Issue by cyatteau** [Esri/arcgis-rest-js#1094]
### Description

Jim Barry brought to my attention that the postal code parameter should be wrapped in quotes as it is an alphanumeric value. Issues arise when using a postal code starting with zero as demonstrated in these CodePen examples ([ex1](https://codepen.io/cyatteau/pen/OJoYRNr), [ex2](https://codepen.io/cyatteau/pen/BaOeRLj)). 

Several places state or use a _number_ instead of a _string_, which need to be addressed:
- [ ] The [API Reference](https://developers.arcgis.com/arcgis-rest-js/api-reference/arcgis-rest-geocoding/IGeocodeOptions#postal) states that the postal code value should be a _number_.
- [ ] The example given [here](https://developers.arcgis.com/arcgis-rest-js/api-reference/arcgis-rest-geocoding/geocode).
- [ ] The tutorial [here](https://developers.arcgis.com/arcgis-rest-js/geocode-and-search/search-for-an-address/).

### Link to page

https://developers.arcgis.com/arcgis-rest-js/api-reference/arcgis-rest-geocoding/IGeocodeOptions#postal

**Comment by patrickarlt** [comment]
@gavinr I think we should accept numbers OR strings here and maybe warn if someone passes a number?

This isn't a breaking change since the number just gets serialized to a string on the POST body or query string.
