### ISSUE TITLE
Example Apps

### ISSUE THREAD

**Issue by dbouwman** [Esri/arcgis-rest-js#11]
In order to ensure that the api works for our desired use-cases, I propose we build some simple applications to validate the library.

The following demos seem useful:
- jquery app
- dojo app
- ember js app
- angular js app
- react app
- node cli app

For the browser demos, the app should use oAuth to get a token, then instantiate a session and execute a simple, authenticated search @ AGO. 

The node example should take the creds as command-line args, and iterate over all the items the user owns, listing the titles.

At this point, lets keep these as vanilla as possible - just bootstrap + minimal code needed. We can build idiomatic examples down the road.

I'll sign-up to create the `arcgis-rest-js-demos` repo, and build the jquery, ember and node examples. Need some Dojo/Angular/React people to jump in as well @tomwayson @mjuniper??

**Comment by jgravois** [comment]
more `demos/` are **always** welcome.
