### ISSUE TITLE
owningSystemUrl in IServerInfo is not available in JS SDK's ServerInfo

### ISSUE THREAD

**Issue by arjanvanzutphen** [Esri/arcgis-rest-js#1108]
### Describe the bug

The property '[owningSystemUrl ](https://developers.arcgis.com/arcgis-rest-js/api-reference/arcgis-rest-request/IServerInfo#owningSystemUrl)' is not available in JS SDK's [ServerInfo](https://developers.arcgis.com/javascript/latest/api-reference/esri-identity-ServerInfo.html) but is defined in [IServerInfo](https://developers.arcgis.com/arcgis-rest-js/api-reference/arcgis-rest-request/IServerInfo).

Should owningSystemUrl be removed or does it serve another purpose? 

### Reproduction

Run this snippet from the website: https://developers.arcgis.com/arcgis-rest-js/api-reference/arcgis-rest-request/ArcGISIdentityManager#fromCredential

```
require(["esri/id"], (esriId) => {
  const credential = esriId.findCredential("https://www.arcgis.com/sharing/rest");
  const serverInfo = esriId.findServerInfo("https://www.arcgis.com/sharing/rest");

  const manager = ArcGISIdentityManager.fromCredential(credential, serverInfo);
});
```

TypeScript will notice that 'owningSystemUrl' is not available in ServerInfo

### Logs

```shell
webpack compiled with 1 warning
ERROR in src/logic/GroupLogic.ts:16:68
TS2345: Argument of type 'ServerInfo' is not assignable to parameter of type 'IServerInfo'.
  Property 'owningSystemUrl' is missing in type 'ServerInfo' but required in type 'IServerInfo'.
    14 |   );
    15 |
  > 16 |   const manager = ArcGISIdentityManager.fromCredential(credential, serverInfo);
       |                                                                    ^^^^^^^^^^
    17 |   debugger;
    18 |   try {
    19 |     const resultGroupUsers = await getGroupUsers(groupId, {
```

### System Info

```shell
"@esri/arcgis-rest-request": "4.2.0",
```

**Comment by gavinr-maps** [comment]
Hi Arjan, thanks for logging this. 

This snippet is actually old - using the JS API v3 syntx (for example,  should be `esri/identity/IdentityManager` instead of `esri/id`). Could  you please send a PR to update this snippet to the latest JS API? This can be found in https://github.com/Esri/arcgis-rest-js/tree/main/demos/jsapi-integration I think.

After that's updated, can you please provide an updated replication case.

**Comment by gavinr-maps** [comment]
## Snippet (non-)issue

After further looking into this, I think [that snippet](https://developers.arcgis.com/arcgis-rest-js/api-reference/arcgis-rest-request/ArcGISIdentityManager/#fromCredential) is actually acceptable:

- [The snippet](https://developers.arcgis.com/arcgis-rest-js/api-reference/arcgis-rest-request/ArcGISIdentityManager/#fromCredential) uses [findCredential](https://developers.arcgis.com/javascript/latest/api-reference/esri-identity-IdentityManager.html#findCredential), which "_Returns the [Credential](https://developers.arcgis.com/javascript/latest/api-reference/esri-identity-Credential.html) for the resource identified by the specified url_"
- The [example in the REST JS sample](https://github.com/Esri/arcgis-rest-js/tree/main/demos/jsapi-integration#running-this-demo) uses [getCredential](https://developers.arcgis.com/javascript/latest/api-reference/esri-identity-IdentityManager.html#getCredential), which "_Returns a [Credential](https://developers.arcgis.com/javascript/latest/api-reference/esri-identity-Credential.html) object that can be used to access the secured resource identified by the input URL_"

I think the `Credential` that is returned from `findCredential` or `getCredential` should both be able to be passed into the ArcGIS REST JS `ArcGISIdentityManager.fromCredential` function.

So I don't think the snippet is the issue.

## Replication case

I was able to create a simple replication case for this issue in a StackBlitz: 
https://stackblitz.com/edit/vitejs-vite-ikrxa2?file=src%2Fmain.ts,src%2Fstyle.css,src%2Fmap.ts&terminal=dev

![image](https://github.com/Esri/arcgis-rest-js/assets/137905994/9d4cc9c8-f4de-4a6e-b9c9-8c1128771951)


That ^ is the original issue (I think).

Given that, I do agree with @arjanvanzutphen that `owningSystemUrl` should be removed (or set to optional?) here. Note that this property does not seem to be included anymore: for example compare [our fetch mock](https://github.com/Esri/arcgis-rest-js/blob/7d8220ad3d3a872fda36f02c21e4046a2b87b7ed/packages/arcgis-rest-request/test/ArcGISIdentityManager.test.ts#L233-L242) vs the actual response: 
https://sampleserver6.arcgisonline.com/arcgis/rest/info/?f=json
```
{
  "currentVersion": 10.91,
  "fullVersion": "10.9.1",
  "soapUrl": "https://sampleserver6.arcgisonline.com/arcgis/services",
  "secureSoapUrl": null,
  "authInfo": {
    "isTokenBasedSecurity": true,
    "tokenServicesUrl": "https://sampleserver6.arcgisonline.com/arcgis/tokens/",
    "shortLivedTokenValidity": 60
  }
}
```

**Comment by gavinr-maps** [comment]
Discussed with @patrickarlt, we propose to **remove** this line:
https://github.com/Esri/arcgis-rest-js/blob/7d8220ad3d3a872fda36f02c21e4046a2b87b7ed/packages/arcgis-rest-request/src/ArcGISIdentityManager.ts#L97
