### ISSUE TITLE
Update REST JS places documentation to reflect pagination changes

### ISSUE THREAD

**Issue by sherylgiovanni** [Esri/arcgis-rest-js#1117]
### Description

There has been a couple of changes to the places-service relating to pagination which need updating in the REST JS documentation.

Theses pagination changes are:
- Removed property `maxResultsExceeded`
- Renamed `links` object to `pagination` 
- Renamed `next` and `previous` to `nextUrl` and `previousUrl`
- `nextUrl` and `previousUrl` are now full Urls rather than Url fragments - `links.base` removed

Old format
```
{
  "results": [/*snip*/],
  "maxResultsExceeded": true,
  "links": {
    "base": "https://places-api.arcgis.com",
    "previous": "/arcgis/rest/services/places-service/v1/places/near-point?x=-3.18718337&y=55.95203695&radius=1000.00000000&searchText=&f=pjson&offset=0&pageSize=10",
    "next": "/arcgis/rest/services/places-service/v1/places/near-point?x=-3.18718337&y=55.95203695&radius=1000.00000000&searchText=&f=pjson&offset=20&pageSize=10"
  }
}
```

New format:

```
{
  "results": [/*snip*/],
  "pagination": {
    "previousUrl": "https://placesdev-api.arcgis.com/arcgis/rest/services/places-service/v1/places/near-point?x=-3.18718337&y=55.95203695&radius=1000.00000000&searchText=&f=pjson&offset=0&pageSize=10",
    "nextUrl": "https://placesdev-api.arcgis.com/arcgis/rest/services/places-service/v1/places/near-point?x=-3.18718337&y=55.95203695&radius=1000.00000000&searchText=&f=pjson&offset=20&pageSize=10"
  }
}
```

### Changes needed
These are the pages that still have the old attributes `links` and `maxResultsExceeded` and they need to be updated accordingly:
- [IFindPlacesNearPointResponse](https://developers.arcgis.com/arcgis-rest-js/api-reference/arcgis-rest-places/IFindPlacesNearPointResponse)
- [IFindPlacesWithinExtentResponse](https://developers.arcgis.com/arcgis-rest-js/api-reference/arcgis-rest-places/IFindPlacesWithinExtentResponse)
- [findPlacesNearPoint](https://developers.arcgis.com/arcgis-rest-js/api-reference/arcgis-rest-places/findPlacesNearPoint/)
- [findPlacesWithinExtent](https://developers.arcgis.com/arcgis-rest-js/api-reference/arcgis-rest-places/findPlacesWithinExtent)

### Link to page

https://developers.arcgis.com/arcgis-rest-js/api-reference/arcgis-rest-places/

**Comment by gavinr-maps** [comment]
fixed in #1133. thanks @sherylgiovanni!
