### ISSUE TITLE
REST JS Request 3.7.0 /bundled/ CDN not resolving

### ISSUE THREAD

**Issue by gowin20** [Esri/arcgis-rest-js#1125]
### Describe the bug

The URL https://unpkg.com/@esri/arcgis-rest-request@3.7.0/dist/bundled/request.umd.js is no longer resolving.

### Reproduction

https://unpkg.com/@esri/arcgis-rest-request@3.7.0/dist/bundled/request.umd.js

### System Info

```shell
v. 3.7.0
```

### Additional Information

Also, is 3.7.0 the latest version? It is not listed in the "releases" category here https://github.com/Esri/arcgis-rest-js/releases but IS listed as "latest verion"  on NPM https://www.npmjs.com/package/@esri/arcgis-rest-request

**Comment by gavinr-maps** [comment]
I think you probably want `/umd/` instead of `/bundled/` .... https://unpkg.com/@esri/arcgis-rest-request@3.7.0/dist/umd/request.umd.js

**Comment by gowin20** [comment]
@gavinr-maps the `/bundled/` link used to work though?

And the `/bundled/` link for version 4.0.0 still does work: https://unpkg.com/@esri/arcgis-rest-request@4.0.0/dist/bundled/request.umd.js
