### ISSUE TITLE
Update automated unit tests to run on Node 20

### ISSUE THREAD

**Issue by gavinr-maps** [Esri/arcgis-rest-js#1138]
### Describe the problem

Node v20 is now the current active LTS version:
https://github.com/nodejs/release#release-schedule

![image](https://github.com/Esri/arcgis-rest-js/assets/137905994/c5e65a5b-7988-46d4-bb8c-7006f998d4d7)

### Describe the proposed solution

So we should probably add v20 to the list of versions that we automatically test on:

https://github.com/Esri/arcgis-rest-js/blob/9ec89a2113dd616519398cc217309930fed7c7bc/.github/workflows/pull-request-tests.yml#L21

### Additional Information

Questions:

- Should we also remove Node 14 from the automated unit tests ([end of life](https://github.com/nodejs/release#end-of-life-releases) was 2023-04-30)?
- Should we also remove Node 16 from the automated unit tests ([end of life](https://github.com/nodejs/release#end-of-life-releases) was 2023-09-11)?

**Comment by patrickarlt** [comment]
I think we should remove 14 and 16.

**Comment by 0scvr** [comment]
I would like to work on this issue, please :)

**Comment by patrickarlt** [comment]
@0scvr all yours!

**Comment by gavinr-maps** [comment]
Updated in #1144 - thanks @0scvr and @patrickarlt!
