### ISSUE TITLE
updateItemResource() in arcgis-rest-items has flipped parameters

### ISSUE THREAD

**Issue by noahmulfinger** [Esri/arcgis-rest-js#118]
See code here:
https://github.com/Esri/arcgis-rest-js/blob/7d9a593ba1f39992bbaba57fa2cfa73f725731d4/packages/arcgis-rest-items/src/items.ts#L324-L338

The value of `fileName` should be `requestOptions.name` and the value of `text` should be `requestOptions.content`

**Comment by jgravois** [comment]
ugh. i wish i was more surprised that i screwed that one up.
