### ISSUE TITLE
How much wrapping of the API do we do?

### ISSUE THREAD

**Issue by patrickarlt** [Esri/arcgis-rest-js#12]
> Only thing that gives me pause is the core-types - are we planning to parse the response json into types with behavior? I could see this massively increasing the scope of this effort if that is the case. My personal preference is to keep arcgis-rest-js a thin wrapper over the API idiosyncrasies, but still allowing a consumer to work with the json directly. If they choose to pump the json into "models" of some sort, so be it, but let's not force that.
>
> @dbouwman in https://github.com/ArcGIS/arcgis-rest-js/pull/6#pullrequestreview-54540194

This is a pretty legitimate question. I definitely agree with @dbouwman that we should not attempt to put everything in our own models.

However I DO think we should provide TypeScript types for request and response parameters.  For example here the response for http://geocode.arcgis.com/arcgis/rest/services/World/GeocodeServer/findAddressCandidates?Address=380+new+york+st&City=redlands&Region=CA&Postal=92373&forStorage=false&f=pjson

```js
{
  spatialReference: {
    wkid: 4326,
    latestWkid: 4326
  },
  candidates: [
    {
      address: "380 New York St, Redlands, California, 92373",
      location: {
        x: -117.1956703176181,
        y: 34.05648811930892
      },
      score: 100,
      attributes: {},
      extent: {
        xmin: -117.1963135,
        ymin: 34.05510800000001,
        xmax: -117.19431349999999,
        ymax: 34.05710800000001
      }
    }
  ]
}
```

Below would be the corresponding typescript interface for this request using `@esri/rest-common-types`:

```ts
import { IExtent, ISpatialReference } from '@esri/rest-common-types';

interface IGeocodeResponse {
  spatialReference: ISpatialReference,
  candidates: IGeocodeCanidate[]
}

interface IGeocodeCanidate {
  address: string;
  location: {
    x: number,
    y: number
  },
  score: number,
  attrubutes: {
    [key: string]: any; //index type allows anything under here... https://www.typescriptlang.org/docs/handbook/advanced-types.html
  },
  extent: IExtent,
  [key: string]: any; // allow any additional params we might not have typed...
}
```

We can then write the `geocode` function like this:

```ts
import { IRequestOptions } from '@esri/rest-request';
import { IGeocodeResponse } from './IGeocodeResponse';

interface IGeocodeParams {
// stuff...
}

interface IGeocodeOptions extends IRequestOptions {
  geocodeService: string;
}

export function geodode(params: IGeocode, options: IGeocodeOptions) : Promise<IGeocodeResponse>{
  // stuff
  return request(/*...*/)
}
```

I think we should author typescript types for requests and responses. `@esri/rest-common-types` was simply envisioned to be a repository of the common types we spread across the different packages.

I think authoring TypeScript types for request params and responses is important for a couple of reasons.

1. TypeScript users will expect this. Deferring everything to an `<any>` type and deferring people to the REST API will not provide the best experience.
2. It allows us to annotate the response in our own docs first since we export the interfaces providing comments specific to our own library before shelling out to the REST API docs.
3. TypeScript users (and JavaScript users in VSCode) will get Intelisense from the typings.
4. In some cases (feature layer admin) we will HAVE to provide our own params and response types since it will have to wrap multiple calls. This means we will need to write a good chunk of `@esri/rest-common-types` anyway.

Since the typings are fairly easy to write and we will have to write a ton anyway for more complex use cases (like feature layer admin) I think we should strive to be consistant and provide at least some basic types since they are easy to write.

---

But we do still need to discuss what level of wrapping DOES any sense for the API? I have 3 examples:

1. In the above geocoding response, the `location` of each candidate does not have a `spatialReference`. If a user wants to pass the `location` of a match to another API they will need to manually add the `spatialReference` property to it. Should we wrap this for users?
2. How would we build an API for sharing items? There are 3 different sharing APIs (`itemid/share`, `groupid/share`, and `users/username/share`) how should would we implement this? Should we make an easier sharing API? Simply wrapping all 3 methods seems inadequate but a better sharing API gets away from the idea of a "simple request" wrapper.
3. Feature layer creation wraps 4-7 requests in most cases. how should we handle this? How much validation should we do?

---

My point being that should probably decide on a series of principles to guide how much wrapping we are going to do.

**Comment by jgravois** [comment]
i wouldn't say what we're doing now is _perfect_, but i think we've settled on a comfortable balance between the thinness @dbouwman craves and the value adds that @patrickarlt described.

#339 will likely be where this conversation continues to evolve.
