### ISSUE TITLE
peerDependencies should treat arcgis-rest-request as external

### ISSUE THREAD

**Issue by tomwayson** [Esri/arcgis-rest-js#128]
As far as I understand, we're implementing packages like -geocoder, -items, -groups, -feature-service, etc as plugins of arcgis-rest-request using `peerDependencies`, right? However, the UMD builds currently do **not** treat arcgis-rest-request as external, so it is bundled in the UMD build of each package. I discovered this while creating the demo for arcgis-rest-feature-service:

https://github.com/Esri/arcgis-rest-js/blob/c961602ac002264e55da5d76514bd2ad64f247ac/demos/feature-service-browser/index.html#L40-L41

I think we need to [modify the rollup config to treat arcgis-rest-request as `external`](https://rollupjs.org/guide/en#peer-dependencies).

**Comment by jgravois** [comment]
this can wait till after DevSummit, but _the man has a point_.
