### ISSUE TITLE
distribute unminified files

### ISSUE THREAD

**Issue by tomwayson** [Esri/arcgis-rest-js#135]
anyone object? I think pulling in the minified files in ember addons is causing slow builds. we're still working on configuring ember to not try and minify the pre-uglfied files, but I wondered if anyone had a reason to **not** distribute them?

cc @patrickarlt @dbouwman @jgravois

**Comment by jgravois** [comment]
fine by me.

**Comment by patrickarlt** [comment]
@tomwayson the ESM and Node files aren't minified anyway only the UMD files. Is there any way to try to pull the compiled ESM modules into Ember? The only downside I can see to not minifying the UMD modules is the filesizes on the CDN would be larger.

**Comment by jgravois** [comment]
@tomwayson you were suggesting shipping _both_ right?

https://unpkg.com/leaflet@1.3.1/dist/leaflet-src.js
https://unpkg.com/leaflet@1.3.1/dist/leaflet.js

**Comment by tomwayson** [comment]
So, I looked at [specifying `output` as an array](https://rollupjs.org/guide/en#configuration-files) to generate multiple files from the same config, but it turns out we're quite a few versions behind of rollup, and we don't even use the `input`/`output` options. I don't think it's a good idea to mess w/ that now. Of course we could do what I do in cedar, which I think I stole from leaflet, which is just run rollup 2x for prod builds. All of that is sounding kinda hairball right now w/ all the devsummit stuff looming.

@dbouwman how bad is this needed? You still having long build times?

**Comment by jgravois** [comment]
> the downside would be that the dist is larger, so slower npm installs.

ember needs or not, i think we should be shipping an un-minified UMD too to make downstream debugging easier. even with a sourcemap, variable names don't resolve when loading the obfuscated build.

![screenshot 2018-03-01 10 14 55](https://user-images.githubusercontent.com/3011734/36861667-67b97b5a-1d39-11e8-8c95-b8e453034bfc.png)

**Comment by dbouwman** [comment]
@tomwayson this is not critical path at all - I was really just using this time to poke at this before we all convene in Palm Springs, so if I hit any ZOMG show-stoppers we can puzzle it out face-to-face.

That said - right now the build time on the `torii-provider-arcgis` dummy app is > 5 minutes, and it just has the `request` and `auth` modules included.

I'll also echo @jgravois that debugging against the minified stuff is 😱 - imho - we def need to ship un-minified umd's

**Comment by dbouwman** [comment]
In contrast - before adding those modules, the build is 16s

**Comment by patrickarlt** [comment]
I don't think we really have to worry about the size difference of minified vs unminified. Right now almost every module is ~2kb or less so shipping both isn't a problem.

@dbouwman I'm more tempted to call this an ember bug then anything else. Why would including minified code in a project ballon the build time 100x but unminified code not?

**Comment by dbouwman** [comment]
@patrickarlt tbh - I have no idea why, but adding them def causes this increase. I'm going to npm-link things up later this evening, and see if the un-minified version solves this... it may well be some other O_o broccoli-ember-mystery-meat that's the cause :)
