### ISSUE TITLE
ignored parameters in processParams

### ISSUE THREAD

**Issue by Biboba** [Esri/arcgis-rest-js#142]
Hi,

Working on esri-leaflet tests migration to arcgis-rest-js library [(#1054)](https://github.com/Esri/esri-leaflet/pull/1054), I noticed that some params were filtered in the processParams method.
For example a request with integer 0 as a value is ignored in processParams method:
https://github.com/Esri/arcgis-rest-js/blob/e9297ff38c7f651b82755b1dfbec7495398eac96/packages/arcgis-rest-request/src/utils/process-params.ts#L13

So for example  a parameter like 'noData=0' is not send.

**Comment by jgravois** [comment]
great catch @Biboba. (ref: https://github.com/Esri/esri-leaflet/issues/946)

**Comment by Biboba** [comment]
Thanks @jgravois for the quick fix.
Unfortunately, false params are still filtered:
returnM=false for example is not sent.

Thanks

**Comment by jgravois** [comment]
wow. sorry about that! i didn't look closely enough at the test that was already in there. 

https://github.com/Esri/arcgis-rest-js/blob/1173a88db7d4383cb70acfac570078f4d7c6e0e6/packages/arcgis-rest-request/test/utils/process-params.test.ts#L80-L90
