### ISSUE TITLE
should default tokens be valid for 2 weeks?

### ISSUE THREAD

**Issue by jgravois** [Esri/arcgis-rest-js#144]
https://github.com/Esri/arcgis-rest-js/blob/4b1544f8b788573137d3519718ab1869eefd17a2/packages/arcgis-rest-auth/src/UserSession.ts#L248

that seems like a _long_ time.

**Comment by patrickarlt** [comment]
Yes?

In my experience talking with other devs they generally want their users to stay signed in for as long as possible by default. This also doesn't make the token last 2 weeks by default. I think a shorter expiration token gets returned if the user doesn't check the remember me box. I also think users can configure their custom portals to return shorter sessions by default.

**Comment by jgravois** [comment]
fair enough. [`OAuthInfo`](https://developers.arcgis.com/javascript/latest/api-reference/esri-identity-OAuthInfo.html#expiration) implements the same default.
