### ISSUE TITLE
release:publish doesn't publish anything w/o follow up command to force it

### ISSUE THREAD

**Issue by tomwayson** [Esri/arcgis-rest-js#150]
Seems like lerna thinks we've already released, b/c I see this in the output:

```bash
lerna info version 2.5.1
lerna info current version 1.1.0
lerna info Checking for updated packages...
lerna info Comparing with v1.1.0.
lerna info Checking for prereleased packages...
lerna info No updated packages to publish. 
```

I am able to publish w/ 

`lerna publish --skip-git --repo-version x.x.x --force-publish=*`

I suspect this is something we're going to have to do every time the way the scripts are currently set up, not just on the "[off chance](https://github.com/Esri/arcgis-rest-js/tree/master/notes#release-system)."

**Comment by tomwayson** [comment]
maybe we just add `--force-publish=*` to

https://github.com/Esri/arcgis-rest-js/blob/master/support/publish.sh#L25

**Comment by jgravois** [comment]
i pushed an additional commit to add the flag in #152, but lets leave this issue open until the problem is actually _fixed_.

**Comment by jgravois** [comment]
@noahmulfinger took another look at this today.

he has me convinced that the force flag is _the right thing to do_&trade; given that we call: 

```
lerna publish --skip-git --skip-npm --yes
```
immediately beforehand via `npm run release:prepare`.

this is so we can bump individual module `package.json` version numbers and generate updates to the CHANGELOG _prior_ to executing the actual release.
