### ISSUE TITLE
We're not distributing types in @esri/arcgis-rest-common-types

### ISSUE THREAD

**Issue by tomwayson** [Esri/arcgis-rest-js#151]
Trying to use @esri/arcgis-rest-feature-service in a typescript app (cedar) and I got this build error:

```bash
$ tsc && rollup -c profiles/dev.js && npm run copy:themes
node_modules/@esri/arcgis-rest-feature-service/dist/esm/features.d.ts(1,87): error TS2307: Cannot find module '@esri/arcgis-rest-common-types'.
error Command failed with exit code 2.
```

Turns out the only thing we distribute in @esri/arcgis-rest-common-types is packge.json and README.md

![image](https://user-images.githubusercontent.com/662944/36988184-16d5382e-2053-11e8-86a8-34d431739c96.png)

https://unpkg.com/@esri/arcgis-rest-common-types@1.1.0

**Comment by tomwayson** [comment]
`npm run bootstap` _does_ output dist/index.ts

**Comment by jgravois** [comment]
i introduced this in 52043f5b702aca699f62abf8054582286e258ba5

https://github.com/Esri/arcgis-rest-js/blob/1173a88db7d4383cb70acfac570078f4d7c6e0e6/packages/arcgis-rest-common-types/package.json#L8
