### ISSUE TITLE
IUser

### ISSUE THREAD

**Issue by jpeterson** [Esri/arcgis-rest-js#159]
It would be useful to have a method/primitive that expresses an **ArcGIS User**. This feels similar to the `IPortal` and `getSelf()` method in `arcgis-rest-request`.

Note that an `IPortal` returned by `request.getSelf()` includes a `user` property, but this object doesn't appear to be a fully-qualified **User** per the REST API spec.

**User spec**
https://developers.arcgis.com/rest/users-groups-and-items/user.htm

The following works fine today:
```javascript
import { request } from '@esri/arcgis-rest-request';

// session === UserSession();

// use request module to fetch user profile
request(`${session.portal}/community/users/${session.username}`, {
  authentication: session
})
```

**Comment by tomwayson** [comment]
Yeah, we should expose a `getUser()` method, and define an `IUser` interface that basically wraps the above call. The question is what package?

**Comment by jpeterson** [comment]
For what its worth, I first went looking for it in `arcgis-rest-auth`'s `UserSession` class.

But as I thought about it, this feels almost directly analogous to `arcgis-rest-request`'s `IPortal` and `getSelf()`/`getPortal()` methods. In the same way, I would expect to be able to fetch the currently logged in user as well as other users (by username). Worth noting that the shape of the object returned there would be determined by the role of the currently logged in user.

**Comment by jgravois** [comment]
my first instinct is to put it in `arcgis-rest-auth`.

**Comment by tomwayson** [comment]
I feel like we need a new package (@esri/arcgis-rest-users) to manage users. It would have `getUser()` and other functions for all the operations under the ["Community - User" left nav here](https://developers.arcgis.com/rest/users-groups-and-items/user.htm).

`IUser` itself will probably end up in common types and shared amongst the auth and groups packages.

**Comment by jgravois** [comment]
@tomwayson and i _both_ ultimately got our way.

`v1.1.2` included this:

```js
import { getUser } from '@esri/arcgis-rest-users';

getUser("jsmith") // returns IUser
```
in `v1.4.0` we also introduced support for
```js
import { UserSession } from '@esri/arcgis-rest-auth';

const session = new UserSession({
  username: "jsmith",
  password: "123456"
})

session.getUser() // returns IUser and caches the response
```
