### ISSUE TITLE
Using arcgis-rest-request when Portal is HTTPS only 

### ISSUE THREAD

**Issue by jpeterson** [Esri/arcgis-rest-js#164]
I'm seeing some odd behavior when using the `request` method against an organization which has been configured to allow HTTPS only.

Given the following snippet:
```js
import { request } from '@esri/arcgis-rest-request';

// session === UserSession();

// use request module to fetch user profile
request(`${session.portal}/community/users/${session.username}`, {
  authentication: session
})
```

If the organization has been configured for HTTPS only, I'm seeing the following network request:

```
https://a4iot.maps.arcgis.com/sharing/rest/community/users/jpeterson_iot&ssl=true
```

Where the expected request is this:
```
https://a4iot.maps.arcgis.com/sharing/rest/community/users/jpeterson_iot
```

This results in an error: `User does not exist or is inaccessible.`

### Relevant Docs

The relevant Portal Self property is `allSSL`.
(doc is here: https://developers.arcgis.com/rest/users-groups-and-items/portal-self.htm)

In case its helpful for discussion, the doc on this configuration option is here:
https://doc.arcgis.com/en/arcgis-online/administer/configure-security.htm

**Comment by jgravois** [comment]
this looks an awful lot like the bug i fixed way back in #143 and i can't repro against `master`

```js
const session = new arcgisRest.UserSession({
  username: "johngdevprogram",
  password: "[redacted]",
  portal: "https://grogg.maps.arcgis.com/sharing/rest"
})

arcgisRest.request(`${session.portal}/community/users/${session.username}`, {
  authentication: session
})
```
![screenshot 2018-03-30 11 59 27](https://user-images.githubusercontent.com/3011734/38150019-d69c61a6-3411-11e8-972f-672db982dfbe.png)

can you test with our [`oauth2-browser`](https://github.com/Esri/arcgis-rest-js/tree/master/demos/oauth2-browser) to see whether it says your username is `jpeterson_iot&ssl=true` after you login using OAuth?

**Comment by jpeterson** [comment]
Gah. Super major big apologies... updating to v1.1.1 and **it works as expected**.

Thanks @jgravois

**Comment by jgravois** [comment]
> Super major big apologies

no worries man. my favorite :bug: is one that i already fixed.
