### ISSUE TITLE
IItem interface shouldn't require properties except id, owner

### ISSUE THREAD

**Issue by noahmulfinger** [Esri/arcgis-rest-js#171]
The `IItem` interface currently requires:
```
owner
title
type
tags
typeKeywords
```
This is an issue in functions like `updateItem`, which requires an `IItem` be passed in. So any call to `updateItem` must include the listed properties. I think it makes sense to just require `id` and `owner`, because these are generally needed to access the item's endpoint, but the rest should be optional. If a function requires an additional property, the interface can be extended.

**Comment by jgravois** [comment]
> I think it makes sense to just require `id` and `owner`.

that sounds fine to me.

**Comment by tomwayson** [comment]
>  So any call to updateItem must include the listed properties

So is that all of the ones listed above, or just `id` and `owner`?
