### ISSUE TITLE
move from @esri to @arcgis npm namespace

### ISSUE THREAD

**Issue by jgravois** [Esri/arcgis-rest-js#172]
[`@esri/arcgis-rest-request`](https://www.npmjs.com/package/@esri/arcgis-rest-request) > [`@arcgis/rest-request`](https://www.npmjs.com/org/arcgis)

**Comment by tomwayson** [comment]
or will @arcgis be reserved for products and/or official SDKs?

**Comment by jgravois** [comment]
i'd also really like to make the built filenames less _verbose_.

```html
<script src="https://unpkg.com/@esri/arcgis-rest-request@1.1.2/dist/umd/arcgis-rest-request.umd.js"></script>

<!--becomes-->

<script src="https://unpkg.com/@arcgis/rest-request@1.1.2/dist/umd/request.umd.js"></script>
```
