### ISSUE TITLE
Fetching token service url fails

### ISSUE THREAD

**Issue by richardhinkamp** [Esri/arcgis-rest-js#174]
I need to export some data to an ArcGIS system with the REST API. I created a developer account and got the code working on my ArcGIS Online account fairly simple. When using the REST endpoint provided by our customer, things didn't work, so I tried to find out what went wrong:

Like this:

```
const URL = "https://<customer.domain>/arcgis/rest/services/<a>/<b>/FeatureServer/0"
const session = new UserSession({
    username: "<username>",
    password: "<password>",
});
let options = {
    httpMethod: "POST",
    authentication: session,
    params: {
        where: `FIELD1 = 12345`,
        outFields: "OBJECTID,FIELD1,FIELD2",
        },
    };
return request(URL + "/query", options);
```

Because of the authentication, in `request()` it calls `authentication.getToken(url)`.
I did not provide a portal url in the sesssion options, so it get's to `this.getTokenForServer(url)`. It requests "https://<customer.domain>/arcgis/rest/info". The response it gets is this:

```
{
    "currentVersion": 10.31,
    "fullVersion": "10.3.1",
    "soapUrl": "https://<customer.domain>/arcgis/services",
    "secureSoapUrl": null,
    "authInfo": {
        "isTokenBasedSecurity": true,
        "tokenServicesUrl": "https://<customer.domain>/arcgis/tokens/",
        "shortLivedTokenValidity": 60
    }
}
```

It tries to get the `owningSystemUrl` property to do a request to `owningSystemUrl + "/sharing/rest/info"` but this property is undefined. The RegExp check should probably fail, but since it's undefined it doesn't. The request fails ofcourse because `owningSystemUrl` is undefined, but it's not needed I guess because the `authInfo.tokenServicesUrl` is already available in the response above.

I tried providing a portal property with the `UserSession`. Using "https://<customer.domain>/arcgis" results in a request to "https://<customer.domain>/arcgis/generateToken" which gives a 404. Using "https://<customer.domain>/arcgis/tokens" as the portal (since portal + "/generateToken" results in the correct url) also fails, because in `getToken()` the RegExp fails and so `getTokenForServer()` is called which results in the case described above.

I'm using node v6.12.3, with ts-node v5.0.1 and typescript v2.7.2 with version 1.1.1 of @esri/arcgis-rest-auth + @esri/arcgis-rest-common-types + @esri/arcgis-rest-request + @esri/arcgis-to-geojson-utils

I'm not really familiar with ArcGIS and have no idea what version the server is, so I'm hoping the description of the problem is enough, otherwise I will dig deeper.

--

To get this working in the mean time I used the following hack:

```
// disable check for portal, direct to getFreshToken()
UserSession.prototype.getToken = function(url) {
    return (this as any).getFreshToken();
};

// portal with /tokens at the end and correct tokenDuration
const session = new UserSession({
    portal: "https://<customer.domain>/arcgis/tokens",
    tokenDuration: 60,
    username: "<username>",
    password: "<password>",
});
```

This works.

**Comment by jgravois** [comment]
thanks for the detailed feedback @richardhinkamp!

you've caught us out on the fact that this library doesn't currently provide a wrapper to help authenticate against an instance of ArcGIS Server which isn't [**federated**](http://enterprise.arcgis.com/en/portal/latest/administer/linux/federate-an-arcgis-server-site-with-your-portal.htm).

we could (and should) do something very similar to your hack _within_ `getToken(url)` and use the `authInfo` in the metadata response to construct a request for a token if we can't find evidence of federation.
