### ISSUE TITLE
Peer dependencies out of sync

### ISSUE THREAD

**Issue by tomwayson** [Esri/arcgis-rest-js#196]
https://github.com/Esri/arcgis-rest-js/blob/master/packages/arcgis-rest-feature-service/package.json#L17-L24

This seems like something we need to fix ASAP and cut a new release.

**Comment by tomwayson** [comment]
Hrm.... maybe not https://github.com/lerna/lerna/issues/1018

I guess we should only be updating the peer deps that rely on the changes in 1.2.0?

**Comment by jgravois** [comment]
i wonder what was keeping them in sync before...

**Comment by jgravois** [comment]
i manually [synchronized](https://github.com/Esri/arcgis-rest-js/blob/v1.2.1/packages/arcgis-rest-auth/package.json) in `v.1.2.1`

**Comment by tomwayson** [comment]
I was wondering how they got back in sync.
