### ISSUE TITLE
create mechanism to share login info w/ JSAPI

### ISSUE THREAD

**Issue by jgravois** [Esri/arcgis-rest-js#208]
for lazy loading workflows. ie. transitioning from non-map > map UI.

@noahmulfinger are you guys already doing this in your vector file editor?

**Comment by patrickarlt** [comment]
@jgravois for they style editor we have a method that looks like:

```ts
class AuthService 
  // ...

  registerToken(session: UserSession) {
    loadModules(["esri/identity/IdentityManager"], {
      url: "https://js.arcgis.com/4.7/"
    }).then(([esriId]: [__esri.IdentityManager]) => {
      esriId.registerToken({
        expires: session.tokenExpires.getTime(),
        server: session.portal,
        ssl: true,
        token: session.token,
        userId: session.username
      });
    });
  }

  // ...
}
```

I do like the idea for bi-directionally that @qlqllu mentioned. I think the rough equivalent would be:

```ts
import { UserSession } from "@esri/arcgis-rest-auth";

loadModules(["esri/identity/IdentityManager"], {
  url: "https://js.arcgis.com/4.7/"
}).then(([esriId]: [__esri.IdentityManager]) => {
  var credential = esriId. getCredential(portalUrl);
  var session = new UserSession({
    clientId,
    portal: credential.server,
    token: credential.token,
    tokenExpires: new Date(credential.expires),
    username: credential.userId
  });
});
```

**Comment by qlqllu** [comment]
I have an idea about the bi-direction sync:

Because the API is lazy load, so when the `IdentityManager` is first loaded, we can call an API in this lib to register the IdentityManager. In this register API, we can sync these two sign in info.

**Comment by tomwayson** [comment]
Maybe we can get some easy wins by starting w/ the low level helper fns that would later support a more comprehensive strategy for this.

For example: the `UserSession` could expose a `getRegisterTokenProperties()` fn that returns an object w/ the properties that `registerToken()` expects. Fortunately those properties seem to be the same between [3.x](https://developers.arcgis.com/javascript/3/jsapi/identitymanager-amd.html#registertoken) and [4.x](https://developers.arcgis.com/javascript/latest/api-reference/esri-identity-IdentityManager.html#registerToken). So in @qlqllu's scenario, we'd call `esriId.registerToken(userSession.getRegisterTokenProperties())` once the `IdentityManager` is loaded.

Alternatively, `UserSession` could expose it's own `registerToken(IIdentityManager)` that takes an instance of `IdentityManager` and calls it's `registerToken()`. The wrinkle there is that we'd have to create our own `IIdentityManager` interface b/c this library doesn't know which version of the JSAPI is being used in the consuming app. However it would have a more terse signature: `userSession.registerToken(esriId)`. 

I'd be fine w/ either of those, but lean toward the first b/c it's simpler and more clear (if also more verbose).

On the flipside, `UserSession` could have something like a `fromCredential()` fn that would read in it's own properties from a [Credential](https://developers.arcgis.com/javascript/3/jsapi/credential-amd.html) as @patrickarlt showed above. I think this would work b/c I believe [all the UserSession constructor options are optional](https://esri.github.io/arcgis-rest-js/api/auth/IUserSessionOptions/), so it would look like:

```js
esriId.getCredential(portalUrl).then(credential => {
  var session = new UserSession({ clientId });
  session.fromCredential(credential)
});
```

**Comment by tomwayson** [comment]
For completeness, I think we ought to add `fromCredential()`, though not exactly as I suggested [above](https://github.com/Esri/arcgis-rest-js/issues/208#issuecomment-394548269). I now think this should be a `static` method on `UserSession`, so:

```
esriId.getCredential(portalUrl).then(credential => {
  var session = UserSession.fromCredential(credential);
});
```

Also, this makes me want to rename `session.getCredential()` to `session.toCredential()`, which should also help avoid any [potential confusion](https://github.com/Esri/arcgis-rest-js/pull/219#discussion_r195212995) with [`esriId.getCredential()`](https://developers.arcgis.com/javascript/latest/api-reference/esri-identity-IdentityManager.html#getCredential).

What do you think @jgravois?

**Comment by jgravois** [comment]
> For completeness, I think we ought to add `fromCredential()`

agreed.

> this makes me want to rename ... to `session.toCredential()`

given that we haven't published a release yet, i'm all for it.

**Comment by tomwayson** [comment]
yeah, i was very cognizant of the fact that we hadn't released this yet when I suggested renaming. :)

**Comment by tomwayson** [comment]
Re-opening b/c of https://github.com/Esri/arcgis-rest-js/pull/227#issuecomment-398516658

Also, should we strip the `/sharing/rest` from [`this.portal` in `toCredential()`](https://github.com/Esri/arcgis-rest-js/blob/1ca31f7f454a46fd4230bf0635a166aa94f7dafa/packages/arcgis-rest-auth/src/UserSession.ts#L556)? It looks [like IdentityManager expects](https://developers.arcgis.com/javascript/3/jsapi/identitymanager-amd.html#registertoken):

> The ArcGIS for Portal URL, for example "https://www.arcgis.com" for ArcGIS Online and "https://www.example.com/portal" for your in-house portal.

**Comment by tomwayson** [comment]
Hm... maybe we don't have to strip `/sharing/rest` b/c this seems to have been working in the jsapi-integration demo. However, that demo will need to be updated w/ `toCredential()`:

https://github.com/Esri/arcgis-rest-js/blob/28dc49b3315e61766c7820c77c7af82b5fa06b3a/demos/jsapi-integration/index.html#L61

**Comment by tomwayson** [comment]
Also, presumably [it's been working for the developers site](https://github.com/Esri/arcgis-rest-js/issues/208#issuecomment-392810703).

**Comment by patrickarlt** [comment]
I think the JS API handles normalizing `/sharing/rest` to figure out the URL.
