### ISSUE TITLE
Group interfaces don't match documentation

### ISSUE THREAD

**Issue by alukach** [Esri/arcgis-rest-js#241]
Taking a look at our `IGroup` interface, it doesn't seem to match [the documentation](https://developers.arcgis.com/rest/users-groups-and-items/common-parameters.htm#ESRI_SECTION1_17DCA22A3B4F4623960631498150A28C) at all:
https://github.com/Esri/arcgis-rest-js/blob/2aa15e8b7457940bc7b2fef1543f6ba3a5c095c0/packages/arcgis-rest-groups/src/groups.ts#L20-L29

For example, it shows `owner` as a required parameter however the docs do not show it as a supported parameter and states:

> The user who creates the group automatically becomes the owner of the group.

Furthermore, parameters like `culture` and `categories` are not related to the `Group` objects at all and appear to be likely copied over from the parameters for creating `Item` instances.

My understanding is that the interfaces should be updated to something similar to the following:

```typescript

export interface IGroupCreateRequest {
  title: string;
  access: 'private' | 'org' | 'public';
  description?: string;
  snippet?: string;
  tags?: string;
  phone?: string;
  sortField?: 'title' | 'owner' | 'avgrating' | 'numviews' | 'created' | 'modified';
  sortOrder?: 'asc' | 'desc';
  isViewOnly?: boolean;
  isInvitationOnly?: boolean;
  thumbnail?: string;
  autoJoin?: boolean;
}

// https://developers.arcgis.com/rest/users-groups-and-items/group.htm
export interface IGroup {
  title: string;
  id: string;
  isInvitationOnly: boolean;
  owner: string;
  description?: string;
  snippet?: string;
  tags: string[];
  phone?: string;
  sortField?: 'title' | 'owner' | 'avgrating' | 'numviews' | 'created' | 'modified';
  sortOrder?: 'asc' | 'desc';
  isViewOnly: boolean;
  isFav: boolean;
  thumbnail?: string;
  created: number;
  modified: number;
  access: 'private' | 'org' | 'public';
  protected: boolean;
  autoJoin: boolean;
  // Server responded with the following undocumented attributes:
  // "isReadOnly": false,
  // "capabilities": [],
  // "provider": null,
  // "providerGroupName": null,
}

export interface IGroupCreateResponse {
  success: boolean;
  group: IGroup;
}
```

Having separate interfaces for the Request and Response parameters would make development go much more smoothly.

**Comment by jgravois** [comment]
thanks for taking the time to write up this feedback @alukach!

i just opened #244 to try and address the problem. if you have time to give it a quick review, it'd be sincerely appreciated.

**Comment by jgravois** [comment]
took another pass at this in #248. Updated interfaces are `IGroupAdd` (for requests to create a new group) and `IGroup` (which represents an existing group).

thanks again for the feedback and follow up dialog.
