### ISSUE TITLE
Doc: IItem shows "type" & "title" as optional, but AGOL requires them for createItem calls

### ISSUE THREAD

**Issue by MikeTschudi** [Esri/arcgis-rest-js#246]
```
  arcgisRest.createItem({
    authentication: userSession,
    item: {
    }
  })
```
leads to
![image](https://user-images.githubusercontent.com/2125181/42819613-ee79aa0a-8988-11e8-8e95-d37a00d0711d.png)

```
  arcgisRest.createItem({
    authentication: userSession,
    item: {
      title: "copied zip",
      type: "Code Sample"
    }
  })
```
is accepted by AGOL.

**Comment by jgravois** [comment]
since `updateItem()` _doesn't_ require those properties, we can extend `IItem` for that method specifically.

```ts
export interface IItemAdd extends IItem {
  title: string;
  type: string; /* maybe even a type? */
}
// ...
export interface IItemAddRequestOptions extends IItemCrudRequestOptions {
  item: IItemAdd;
}

export function createItem(
  requestOptions: IItemAddRequestOptions
)
```
i should be able to knock this out today. i've been meaning to reorganize the package to break it up into multiple files and take a slightly different internal approach to auth anyway.
