### ISSUE TITLE
Possible server federation check bug

### ISSUE THREAD

**Issue by noahmulfinger** [Esri/arcgis-rest-js#257]
I'm attempting to run `queryFeatures` on a feature service in devext (ie `https://servicesdev.arcgis.com/orgId/arcgis/rest/services/test/FeatureServer/0`), but I ran into a possible federation issue.

`UserSession.getTokenForServer` checks the `owningSystemUrl` property, which in this case is `https://devext.arcgis.com`. However, my portal is set to `https://devext.arcgis.com/sharing/rest`, so the urls don't match and a `NOT_FEDERATED` error is returned. I'm assuming the check on the `owningSystemUrl` should accept my portal in this case.

Relevant code (specifically line 703):
https://github.com/Esri/arcgis-rest-js/blob/834ad79632f40c3d1abedf017d202a184bb25db3/packages/arcgis-rest-auth/src/UserSession.ts#L701-L709

cc @patrickarlt @jgravois 

Note: This won't be an issue for the servicesdev domain after https://github.com/Esri/arcgis-rest-js/pull/245 is released, since `getToken` will correctly recognize servicesdev as an arcgis.com server.

**Comment by jgravois** [comment]
this definitely _should_ be resolved in the next release. if not, we'll revisit.

**Comment by noahmulfinger** [comment]
@jgravois It will get resolved for `servicedev.arcgis.com` in the next release, but I wanted to point out more generally that when the portal is `https://my.server.com/sharing/rest` and the `owningSystemUrl` is `https://my.server.arcgis.com`, the `NOT_FEDERATED` error will be returned. That seems incorrect to me.

**Comment by jgravois** [comment]
> when the portal is https://my.server.com/sharing/rest and the owningSystemUrl is https://my.server.arcgis.com, the NOT_FEDERATED error will be returned.

i just tested the repro case i wrote up in #161 again, and we definitely appear to be handling things appropriately.


```js
// owningSystemUrl = "https://portalhostds.ags.esri.com/gis";
// this.portal = "https://portalhostds.ags.esri.com/gis/sharing/rest";

new RegExp(owningSystemUrl).test(portal)
>> true
```

happy to dig in further if you can provide more info.

**Comment by noahmulfinger** [comment]
@jgravois You're right, I looked at it again and the actual issue is that the `owningSystemUrl` was  `http://...` whereas the portal was `https://...`. That's what caused the regex failure.

**Comment by jgravois** [comment]
glad to hear it.
