### ISSUE TITLE
arcgis-rest-feature-service 1.5.1 : getAttachments is not a function

### ISSUE THREAD

**Issue by Biboba** [Esri/arcgis-rest-js#258]
In a nodejs application, I am trying to load "getAttachments" but it seems like it is not bundled in npm package 'arcgis-rest-feature-service' v.1.5.1:
https://esri.github.io/arcgis-rest-js/api/feature-service/getAttachments/

`const { getAttachments, queryFeatures } = require("@esri/arcgis-rest-feature-service");`
TypeError: getAttachments is not a function

Looking at the node package, I have the following structure, so I believe others packages are missing (addAttachment, deleteAttachment, ... ):
![image](https://user-images.githubusercontent.com/11556423/43330310-120f7e76-91c3-11e8-9f47-312b08b1ae5e.png)

Publishing problem ?

Thanks,

Nicolas

PS : Love that package 👍 Thanks

**Comment by jgravois** [comment]
hey @Biboba!

i haven't tagged a new version since @COV-GIS made that great contribution in #235, but i assure you, a new release is imminent.

**Comment by Biboba** [comment]
Hi @jgravois,
Thanks for the quick reply. Lucky me then ! I did not realize all of this was new. Thanks @COV-GIS as it was exactly what I needed ! 
Can't wait for the release.

**Comment by jgravois** [comment]
released as [`v1.6.0`](https://github.com/Esri/arcgis-rest-js/releases/tag/v1.6.0) :tada:
