### ISSUE TITLE
Errors in browser geocode demo

### ISSUE THREAD

**Issue by tomwayson** [Esri/arcgis-rest-js#267]
Clicking get service info button shows `arcgisRest.serviceInfo is not a function` in the console:

<img width="553" alt="image" src="https://user-images.githubusercontent.com/662944/43723190-e3945950-994b-11e8-9e5e-7557aebec3eb.png">

Oauth popup hangs after successful sign in:

<img width="692" alt="image" src="https://user-images.githubusercontent.com/662944/43723117-bab0aac0-994b-11e8-8765-82d481406230.png">

Opening the console for that popup I see `Cannot read property 'completeOAuth2' of undefined at post-sign-in.html:14`

**Comment by jgravois** [comment]
i'm not sure whats causing the first error, but we can (and should) use `getGeocodeService()` instead.

for the second, we just need to update the filenames in the script tags.

```
https://github.com/Esri/arcgis-rest-js/blob/master/demos/geocoder-browser/post-sign-in.html
<script src="node_modules/@esri/arcgis-rest-request/dist/umd/request.umd.js"></script>
<script src="node_modules/@esri/arcgis-rest-auth/dist/umd/auth.umd.js"></script>
```
