### ISSUE TITLE
empty JS files generated in packages/arcgis-rest-common-types/src

### ISSUE THREAD

**Issue by tomwayson** [Esri/arcgis-rest-js#269]
I keep seeing:

```bash
On branch master
Your branch is up-to-date with 'origin/master'.
Untracked files:
  (use "git add <file>..." to include in what will be committed)

	packages/arcgis-rest-common-types/src/group.js
	packages/arcgis-rest-common-types/src/index.js
	packages/arcgis-rest-common-types/src/item.js
	packages/arcgis-rest-common-types/src/webmap.js
```

I think those are getting generated by `npm run bootstrap`? They're all empty:

```bash
➜  arcgis-rest-js git:(master) ✗ more packages/arcgis-rest-common-types/src/group.js
/* Copyright (c) 2018 Environmental Systems Research Institute, Inc.
 * Apache-2.0 */
```

**Comment by jgravois** [comment]
have you pulled upstream `master` lately?

https://github.com/Esri/arcgis-rest-js/tree/72ed12224b8dcbd53121d59cd0f72d1e3ffe9e39/packages/arcgis-rest-common-types/src

**Comment by tomwayson** [comment]
Yes, this is after pulling `master`, and I see those TS files, but I don't expect the build process to leave empty **JS** files around, or if it does, I'd expect to that we'd add them to .gitignore

**Comment by tomwayson** [comment]
OK, this definitely happens after `npm run bootstrap`  - even after running `lerna clean` first.

**Comment by jgravois** [comment]
i noticed something similar to this on @dbouwman's box today after he started stubbing out a new hub.js package...

**Comment by jgravois** [comment]
file this one under 🤷‍♂️
