### ISSUE TITLE
createItem documentation sample

### ISSUE THREAD

**Issue by gavinr** [Esri/arcgis-rest-js#283]
This line should ready `type: "Web Map"` not `type: "Webmap"`

https://github.com/gavinr/arcgis-rest-js/blob/e42f3eefbb46943c400da0e4e4b96b64e38508e5/packages/arcgis-rest-items/src/items.ts#L186

**Comment by jgravois** [comment]
nice catch! a PR with the fix would be _most_ appreciated.

**Comment by jgravois** [comment]
bonus points if you can tackle the typo @tomwayson noticed in https://github.com/Esri/arcgis-rest-js/issues/281#issue-351249868 at the same time. 😉

**Comment by gavinr** [comment]
yep, working on it. will take a look at tom's issue too. thanks

**Comment by jgravois** [comment]
resolved via #287
