### ISSUE TITLE
Documentation pages navigation: highlight currently selected page

### ISSUE THREAD

**Issue by gavinr** [Esri/arcgis-rest-js#284]
I'll admit this is a subjective request, but I personally find it easier when the page I'm on highlights itself in the navigation. It helps me get my bearings if maybe I arrived on this page from a search engine or outside link. So I would propose changing this:
![image](https://user-images.githubusercontent.com/209355/44232173-e1640f00-a165-11e8-86c5-8377fe39988a.png)

to something like this:
![image](https://user-images.githubusercontent.com/209355/44232190-eb860d80-a165-11e8-8a6b-ad8fa60fc801.png)
(notice the background highlight on the selected page in the nav)

Just throwing it out there to see what you all think! Thanks!

**Comment by jgravois** [comment]
_definitely_ a good suggestion.

**Comment by noahmulfinger** [comment]
The highlighting actually works if you run the docs locally. I think we need to change something in the calcite web configuration so it works in both environments.

**Comment by gavinr** [comment]
I see now - yes - when running the doc locally the current page in the navigation is outlined:
![image](https://user-images.githubusercontent.com/209355/44268873-6ef03f00-a1f8-11e8-9ef0-ac782ac1d333.png)

I'm not too familiar with the docs build system, but FWIW it looks like the `list-item-active` class is just not getting added to the div when hosted in production:

![production](https://user-images.githubusercontent.com/209355/44269000-df975b80-a1f8-11e8-9664-361a775bdaec.png) (production)

vs locally hosted:

![locally hosted](https://user-images.githubusercontent.com/209355/44269025-ecb44a80-a1f8-11e8-81b7-61c2e10c9e92.png)

**Comment by jgravois** [comment]
the problem is worse than that. `is-active` isn't being set on page load in production _anywhere_ on page load.

proposed ~~fix~~ hack in #334 	

![screenshot 2018-09-21 12 01 39](https://user-images.githubusercontent.com/3011734/45900962-22b79200-bd96-11e8-86bb-4affed58b2ba.png)

![screenshot 2018-09-21 12 02 28](https://user-images.githubusercontent.com/3011734/45901000-3fec6080-bd96-11e8-9cc9-aec2e5e001c1.png)

**Comment by gavinr** [comment]
looks great @jgravois!

**Comment by tomwayson** [comment]
I hate to even bring this up, but in FF I can get the nav in a state where _both_ nav links appear active by going from one to the other and then using the back button (or key board shortcut):

<img width="379" alt="image" src="https://user-images.githubusercontent.com/662944/46565636-31d62e00-c8c6-11e8-9f9c-e86899720e8c.png">

As long as navigate back/forward using the built in browser controls both continue to appear active, but when I _click_ on either one, only that one will be appear active.

Other than that this looks great, and I'm not even sure a fix for ^^^ is worth the trouble.

**Comment by jgravois** [comment]
feature-service pages expand the 'admin' package tree too. :wink:

![2018-10-05 17 52 24](https://user-images.githubusercontent.com/3011734/46565773-3e5b8600-c8c8-11e8-9d19-97ad17000e06.png)
