### ISSUE TITLE
Enable passing headers (and possibly credentials) to fetch?

### ISSUE THREAD

**Issue by Biboba** [Esri/arcgis-rest-js#290]
Hello,

I am using "arcgis-rest-js" library to query a secured Web-tiers ArcGIS Server from NodeJS backend.
The ArcGIS Server is not federated to a Portal so I cannot use the built-in Oauth mechanism.
I am able to query the ArcGIS Server using fetch by specifiying a cookie to add in the request:
`fetch(agsUrl,
{
        headers: {
          Cookie: mycookie
        }
})`

but I am under the impression that it is not possible with this library or did I miss anything ?

Thanks for your help and for this well-documented library !

**Comment by jgravois** [comment]
hey @Biboba!

I'm not familiar with using cookies to access secure content in ArcGIS Server. Do you know what type of security is in place? ArcGIS Server or Web-tier [authentication](https://enterprise.arcgis.com/en/server/latest/administer/windows/configuring-arcgis-server-s-authentication-tier.htm)? What kind of [identity store](https://enterprise.arcgis.com/en/server/latest/administer/windows/about-the-identity-store.htm)?

In general, no immediate concerns with adding `headers?` to [`IRequestOptions`](https://esri.github.io/arcgis-rest-js/api/request/IRequestOptions/) spring to mind.

---

this is a _bit_ of a tangent, but i just took a look at the doc for ArcGIS Enterprise for the first time in awhile and noticed new information in [About ArcGIS tokens](https://enterprise.arcgis.com/en/server/latest/administer/windows/about-arcgis-tokens.htm).

> When building custom ArcGIS client applications that use GET requests to access web services secured using ArcGIS token-based authentication, it is recommended that the token be sent in the X-Esri-Authorization header instead of a query parameter.

> > GET https://arcgis.mydomain.com/arcgis/rest/services/SampleWorldCities/MapServer?f=pjson HTTP/1.1
    Host: arcgis.mydomain.com
    X-Esri-Authorization: Bearer xMTuPSYpAbj85TVfbZcVU7td8bMBlDKuSVkM3FAx7zO1MYD0zDam1VR3Cm-ZbFo-

I wasn't aware of this capability before, but it looks like it's worth investigating too.

**Comment by COV-GIS** [comment]
@jgravois I was reading up on the `fetch API` last week and was thinking a `headers` param to mix in custom headers would be nice FWIW.

**Comment by Biboba** [comment]
Hey @jgravois ,

Thanks for the quick reply. It is an ArcGIS Server Web-tiers authentification with a windows active directory store (no ArcGIS Enterprise involved),
Would love headers params to solve my issue 👍 

Thanks

**Comment by jgravois** [comment]
i'm tied up with other :fire:s at the moment, but i _think_ this would be as simple as:

**Comment by Biboba** [comment]
In the meantime, I was able to solve my issue using a custom fetch with cookie management:

`const nodeFetch = require("node-fetch");`
`const tough = require('tough-cookie');`
`const cookieJar = new tough.CookieJar(mycookies);`
`const fetchWithCookie = require('fetch-cookie')(nodeFetch, cookieJar);`
`const { queryFeatures } = require("@esri/arcgis-rest-feature-service");`

`queryFeatures({`
        `fetch: fetchWithGISCookie,`
        `url: panoramicServiceUrl,`
        `where: whereClause`
`})`

**Comment by itrew** [comment]
@jgravois In the same vein as this issue with regards to supporting IWA, it would be nice to just set the fetch option `credentials: 'include'` for instances where the url is pointed at a different host. Right now the request method defaults to `credentials: 'same-origin'`, so the ability to overwrite that default would be nice. For now, I've found the need to pass in a custom fetch to get fetch to send the correct creds.
```typescript
// Potential update
// packages/arcgis-rest-request/src/request.ts
const options: IRequestOptions = {
  httpMethod: "POST",
  fetchCredentials: "same-origin"
  ...requestOptions
  };

const { httpMethod, authentication, fetchCredentials } = options;

const fetchOptions: RequestInit = {
  method: httpMethod,
  // ensures behavior mimics XMLHttpRequest. needed to support sending IWA cookies
  credentials: fetchCredentials
};

// implementation.js
import { request } from '@esri/arcgis-rest-request';

request('some url', {
  // Tacks on creds even when the url is on a different host than the origin.
  fetchCredentials: 'include'
})
```
```javascript
// Current workaround
import { request } from '@esri/arcgis-rest-request';

function fetchWithCredentials(url, opts = {}) {
  return fetch(
    url,
    Object.assign(opts, {
      credentials: 'include',
    }),
  );
}

function customFetch(url, opts) {
  return Object.assign(fetchWithCredentials.bind(null, url, opts), fetch)();
}

request('some url', {
  fetch: customFetch
})
```

**Comment by jgravois** [comment]
we landed support for passing custom `headers` in `IRequestOptions` in #437.

@itrew it wouldn't be hard to surface `credentials` too, but since you have a workaround, i'm wary to do it until #209 is resolved. feel free to log another issue for it if you'd like us to track it.

**Comment by itrew** [comment]
@jgravois I'll go ahead and log another issue or now, as it really is a separate, but probably a pretty low priority. I'll be sure include my work around in the new issue in case anyone else stumbles onto the same problem.

**Comment by Biboba** [comment]
Hi @jgravois ! 

Thanks for the update. 
So I tried getting rid of my custom fetch with cookie jar following the release of v1.15.2 but it fails because my cookie specified in headers object is appended to the get parameter:
https://hostname.foo.io/arcgis/rest/services/folder/service/FeatureServer/0/query?f=json&headers=%7B%22Cookie%22%3A%22myCookie%22%7D

I am using queryFeatures from @esri/arcgis-rest-feature-service and my object looks like the following:
```js
queryFeatures({
                headers: {
                    Cookie:"myCookie"
                },
                url: myUrl,
                where: "MY_FIELD LIKE '%" + fieldValue + "%'",
                returnGeometry: false
            })
  ```

Having a look at the code (not tested), I believe the issue is coming from "appendCustomParams" function not filtering headers:
https://github.com/Esri/arcgis-rest-js/blob/065d439995b8dde24c851043f75de369bc45c822/packages/arcgis-rest-request/src/utils/append-custom-params.ts#L9-L29

Thanks !

**Comment by jgravois** [comment]
@Biboba thanks for the detailed bug report. this has been patched in #447.

**Comment by Biboba** [comment]
@jgravois Thanks the quick fix ! I was able this time to get rid of my custom fetch using [v1.16.0](https://github.com/Esri/arcgis-rest-js/releases/tag/v1.16.0) :pray:

**Comment by jgravois** [comment]
no problem.

i'd _love_ to be able to write a test that throws an error if anything unexpected shows up in the request parameters, but a blacklist presents a bit of a 🐔 and 🥚 problem.
