### ISSUE TITLE
introduce an option to 'cache bust' UserSession.getUser()

### ISSUE THREAD

**Issue by jgravois** [Esri/arcgis-rest-js#291]

**Comment by tomwayson** [comment]
`session.refreshUser()` seems like a good way to me.

**Comment by dbouwman** [comment]
So I ran into needing something like this - details in #309

**Comment by jgravois** [comment]
my linting escapades in #430 taught me that UserSession already has a `refreshSession()` method.

**Comment by tomwayson** [comment]
and it's doc'd: https://esri.github.io/arcgis-rest-js/api/auth/UserSession/#refreshSession
