### ISSUE TITLE
provide a way to hide private fns from the API docs

### ISSUE THREAD

**Issue by tomwayson** [Esri/arcgis-rest-js#293]
The same way that @dbouwman did for Hub.js: https://github.com/Esri/hub.js/pull/55/files

**Comment by patrickarlt** [comment]
If you mark anything as `private` in the codebase typedoc should respect that and give us a flag we can use in the templates to hide things.

**Comment by dbouwman** [comment]
so - this is still pretty hacky... but ended up I updating the `build-typedoc.js` script to take a argument that can be `private` or `protected`.

If we pass `protected` it will filter out `isProtected` and `isPrivate` entries.

If we pass `private` it will filter out `isPrivate` entries.

If we pass nothing, it does not filter anything.

Icky-hacky-but-worky code --> https://github.com/Esri/hub.js/blob/master/docs/build-typedoc.js#L133-L154

**Comment by jgravois** [comment]
resolved in https://github.com/Esri/arcgis-rest-js/pull/531
