### ISSUE TITLE
Unable to determine if a user session should be SSL-only

### ISSUE THREAD

**Issue by skitterm** [Esri/arcgis-rest-js#295]
When authenticating with the OAuth implicit grant, a `ssl=true` key-value pair is returned as part of the OAuth callback's hash, when the organization is HTTPS-only. Based on that I can adjust everything to be strictly HTTPS when the organization requires it.

However, when calling `userSession.toCredential()`, `ssl` is [always `true`](https://github.com/Esri/arcgis-rest-js/blob/0b2d8f8c4b5f177471158a0d165089312459c010/packages/arcgis-rest-auth/src/UserSession.ts#L579).

Unless I'm mistaken, that makes it impossible to determine whether or not a session should be SSL-only (without manually reading the oauth callback hash for that value, of course).

Newbie idea, but a way to let `userSession` know if `ssl` should be `true || false`  would be to allow passing it in as a parameter in `completeOAuth2()`?

**Comment by tomwayson** [comment]
I think the way to do that would be to add add a `ssl: boolean` prop to [UserSession](https://esri.github.io/arcgis-rest-js/api/auth/UserSession/) and [UserSessionOptions](https://esri.github.io/arcgis-rest-js/api/auth/IUserSessionOptions/) and then as you say add it here:

https://github.com/Esri/arcgis-rest-js/blob/af61e3e9b2a7fbc164b1d3e7ccad8e9b6a2079ea/packages/arcgis-rest-auth/src/UserSession.ts#L430

Then update `toCredential()` to pull from that value.

I'd gladly accept such a pull request 😄

**Comment by skitterm** [comment]
PR submitted: #332

**Comment by jgravois** [comment]
resolved via #332. thanks again @skitterm 🎉
