### ISSUE TITLE
add signout() method to UserSession

### ISSUE THREAD

**Issue by tomwayson** [Esri/arcgis-rest-js#297]
I think we should add `userSession.signout()` which under the hood would call the (apparently undocumented cc @patrickarlt) oauth2/signout REST end point.

I _swear_ I already opened this issue, but I can't find it. @skitterm also recently asked me about this, so that's 2 interested parties.

**Comment by patrickarlt** [comment]
I think the undocumented signout method is actually specifically for signing out of Online/Portal it won't actually sign the our of a 3rd party app.

**Comment by tomwayson** [comment]
Yes, it clears the esri_auth cookie, and most apps won't be using that. However, there are apps like Hub, StoryMaps, etc that are part of Online and do use it, and for which a shared implementation might be useful.

To that end, we should first figure out if there is a shared implementation that would be useful to us. 😉 

Here's a code snippet from an existing app that shows how we would use it:

```ts
    // if we have the auth cookie we also need to clear it
    const location = window && window.location;
    if (location && Cookies.get(ESRI_AUTH_COOKIE_NAME)) {
      // we want to reload the app w/ the current state
      const redirectUri = encodeURIComponent(location.toString());

      // NEW CODE HERE! this is the proposed API:
      userSession.signout(redirectUri);

      // BACK TO EXISTING CODE
      // this is how the app currently does this, and this could be called under the hood
      // and the new method could do this by getting portal and clientId from the userSession (this)
      // const signoutUrl = `${portal}/oauth2/signout?client_id=${clientId}&redirect_uri=${redirectUri}`;
      // location.href = signoutUrl;
    }
```

@skitterm is that the kind of thing you had in mind?

**Comment by skitterm** [comment]
@tomwayson even more than clearing the cookie is invalidating the token. I assume that's part of the magic the `oauth2/signout` endpoint does, but I could be mistaken.

Cookie clearing could be nice but if the cookie's not set here in the library, I could see it making sense to also not clear it.

**Comment by tomwayson** [comment]
> but if the cookie's not set here in the library,

Well, I think that it is set when we use the [oauth2/authorize](https://developers.arcgis.com/rest/users-groups-and-items/authorize.htm) end point, which is called by `beginOAuth2()`.

**Comment by tomwayson** [comment]
> even more than clearing the cookie is invalidating the token. I assume that's part of the magic the oauth2/signout endpoint does, but I could be mistaken.

I did not know that, but it would make sense. If so, it seems like docs around that endpoint could be useful to others beyond us "Online" developers.

**Comment by skitterm** [comment]
> Well, I think that it is set when we use the oauth2/authorize end point, which is called by beginOAuth2().

From my [experience](https://developers.arcgis.com/documentation/core-concepts/security-and-authentication/browser-based-user-logins/), the cookie is not set automatically as part of that workflow; the developer is left to persist the username/token/etc credentials him/herself.

**Comment by tomwayson** [comment]
I just did a quick test and confirmed that using the `oauth2/signout` end point _does_ indeed invalidate the token.

**Comment by patrickarlt** [comment]
>Hub, StoryMaps, etc that are part of Online and do use it, and for which a shared implementation might be useful.

I agree this would totally be useful and if this were an internal shared library I would 💯 agree. But since this is an externally facing library for users I don't think we should really put it in here since it doesn't relate to the users app. 

> Well, I think that it is set when we use the oauth2/authorize end point, which is called by beginOAuth2().

It is set by the `oauth2/authorize` but it has never really been clear to be if the `esri_auth` cookie should be used in third party apps.

I also think @skitterm is right the `esri_auth` cookie is only set if your redirect URL is to an `arcgis.com` domain. To test this fire up one fo the demo apps and sign in. The `esri_auth` cookie isn't even present.

I don't really think we should add convenience methods for our (Esri/ArcGIS) apps unless they will be useful for users too.

**Comment by tomwayson** [comment]
I think invalidating the token is useful for everyone.

**Comment by patrickarlt** [comment]
@tomwayson it is but I don't think you can control which token is invalidated. It always invalidates the token in the `esri_auth` cookie.

**Comment by skitterm** [comment]
Sounds like `oauth2/signout` does more than just undo what `beginOAuth2` and `completeOAuth2` do (thru the sign-in workflow); I see the point about not wanting to trigger unknown side-effects like signing you out of arcgis.com apps as well as your app. If there's any way to call a method that invalidates the token set when signing in thru that workflow, that seems sufficient to me.

**Comment by jgravois** [comment]
closing, but happy to reconsider if anyone discovers a technique to invalidate a token.
