### ISSUE TITLE
Update `folder` to `folderId` in IItemCrudRequestOptions

### ISSUE THREAD

**Issue by MikeTschudi** [Esri/arcgis-rest-js#308]
This affects interfaces that inherit, e.g., [IItemMoveRequestOptions](https://esri.github.io/arcgis-rest-js/api/items/IItemMoveRequestOptions/), which has `folder` from IItemCrudRequestOptions and `folderId` from [Make moveItem's folder parameter optional](https://github.com/Esri/arcgis-rest-js/pull/306); only the latter works.

**Comment by jgravois** [comment]
thanks for this.

tracking in https://github.com/Esri/arcgis-rest-js/issues/137#issue-301512975
