### ISSUE TITLE
Workflows and UserSession._user

### ISSUE THREAD

**Issue by dbouwman** [Esri/arcgis-rest-js#309]
During the "activation" of an Initiative, we have the following (rough) workflow:

- fetch initiative "template" item
- interpolate values into template, and save as new Initiative "instance"
- create a "collaboration group" (shared editing)
- share newly created Initiative to the "collaboration group"

The tricky bit arises in the sharing at the end. Since the Portal Sharing API has some "idiosyncrasies", the `shareItemWithGroup` function does a lot of pre-flight checking, including a check to see if the current user is a member of the group. It currently does this by checking if the group is in the `UserSession._user`'s array of groups.

The trouble is that `UserSession.getUser()`, tries to be "smart" in that it will only fetch the user from the Portal if it does not already have a cached version and of course, the cached `user` can not possibly have the group because we just created it. 

In my local AGRjs branch, I updated the `getUserMembership` call to fetch the group, and look at it's `.userMembership` property instead of looking in the `UserSession.user.groups`. However, that just seems like a wasted xhr, when the app actually knows the user is a member of the group. 

Question is - how can we inform AGRjs's group sharing logic of this? Should we send another optional param that basically says "trust me, the user is a member"? 

I also sense that this may crop up in more scenarios... thus begging the question of keeping the `UserSession.user` in sync with what's on the server-side? Should we even try?

For this specific scenario, I'm disinclined to make the `addGroup` function inject the group into `UserSession._user.groups` as that seems "side-effecty" and get's into managing state etc... but i'm unclear how else to wrangle this...

Anyhow - open to ideas...

**Comment by jgravois** [comment]
thanks for this write up. i still think our best option is to expose something in the API that guarantees a fresh request for user metadata will be made.

lets continue tracking in #291.
