### ISSUE TITLE
conceptual auth doc

### ISSUE THREAD

**Issue by jgravois** [Esri/arcgis-rest-js#315]
- [x] embedding username/password (don't do it)
- [x] browser based oauth
- [x] `ArcGISAuthError.retry()` (see #224 for more info)
- [ ] cookies
- [ ] passing a session to the JSAPI (and vice versa)

**Comment by tomwayson** [comment]
See my (mostly duplicate) suggestions in #316

**Comment by petemahoney** [comment]
Would love a little doc to help guide on how to do browser based OAuth2.  We are doing extensive work with Portal and writing lots of apps - but not all of them need the full Javascript API so a lightweight option for authentication would be great.

I see the guide that is started here - https://esri.github.io/arcgis-rest-js/guides/browser-authentication/ - but I'm still lost at a high level.  I realize I may need to learn some more fundamental concepts here but I think I just need help setting up the logic in my app.  In the main demo, https://github.com/Esri/arcgis-rest-js/tree/master/demos/oauth2-browser, the app uses a redirect to an authenticate.html page that then stores the session info in local storage.  Is this the pattern we should all adopt?  So when our app loads we check for session info in local storage and do the authentication if it's not there or expired?  For you smart people, what are the pros and cons of that approach.  Are there other ways to do it?

**Comment by jgravois** [comment]
@petemahoney persisting authentication info in `localStorage` is a helpful technique, but to be clear, its not a _necessary_ step in the OAuth 2.0 flow.

i'll plan on adding the links below to the guide you mention to more explicitly steer folks toward more comprehensive and relevant external doc.

### Resources

* [Implementing Named User Login](https://developers.arcgis.com/documentation/core-concepts/security-and-authentication/signing-in-arcgis-online-users/)
* [Browser-based Named User Login](https://developers.arcgis.com/documentation/core-concepts/security-and-authentication/browser-based-user-logins/)

just the other day we discussed covering this topic in some detail at Developer Summit in Palm Springs. if you have any other specific feedback or questions it will not only help us continue to improve our doc, but also help us hit the right notes in that recorded talk.
