### ISSUE TITLE
add SRI hashed script tag examples to packages docs page

### ISSUE THREAD

**Issue by COV-GIS** [Esri/arcgis-rest-js#321]
Perhaps under `CDN url:` have...

Script tag:
```<script src="https://unpkg.com/@esri/arcgis-rest-request@1.9.0/dist/umd/request.umd.js" integrity="sha384-Iutv/c8BA+49hi5Y9oNmHeFbrxWU62LKbyb2YV/OK3PwGP2e4XFIq//lFTWDXryO" crossorigin="anonymous"></script>```

I'm sure there's a way to automate it.

Just a thought.

**Comment by jgravois** [comment]
this would be a welcome contribution, but i won't have time to tackle it personally any time soon.

pat's great static site generator [`acetate`](https://github.com/patrickarlt/acetate) already provides a great hook to do this. you'd just need to add another dep to generate the hash when the cdn url is composed.

https://github.com/Esri/arcgis-rest-js/blob/master/docs/acetate.config.js#L200-L204

**Comment by COV-GIS** [comment]
Just getting it out there.

Very well may do @jgravois.

**Comment by COV-GIS** [comment]
I was investigating a bit. Don't see any issue using node's `crypto` package to generate hashes for the dist packages and creating a script tag code sample.

John, Tom and Pat...what say you about either replacing `CDN url:` with script tag code or adding it as an additional code sample as suggested above?

**Comment by COV-GIS** [comment]
Sorry fellas...I'm gonna let this one go for now.

The hashes are easy enough to create. And so is composing a script tag string for the docs with an acetate helper. But creating an SRI hash requires a promise, so hashes would need to be created as part of the build or possibly with an acetate plugin to create and include the hashes in the `typedoc.json` for each package.

Too far out in the rhubarb for me at this time.

I'll keep it in mind and might surprise with a PR at a future date.

**Comment by jgravois** [comment]
> But creating an SRI hash requires a promise

i hadn't considered that but it makes sense, only because we don't have a local reference to built files from the latest release readily available.

one way to sidestep that problem would be to add yet another step to our [release script](https://github.com/Esri/arcgis-rest-js/blob/master/support/publish.sh#L17) to calculate hashes for each of the _local_ packages locally and save them in a config file.

https://github.com/Esri/arcgis-rest-js/blob/master/support/publish.sh#L17

leaving this open in case anyone else is interested in tackling.

**Comment by COV-GIS** [comment]
Here's where I got to @jgravois.

https://github.com/COV-GIS/arcgis-rest-js/commit/579636bafebff4f2b352c70863dc5331d5650d5e

If there's some direction or ideas I'm open to them.

I can also submit a PR with just the script tag for now as well.
