### ISSUE TITLE
FormData is not defined

### ISSUE THREAD

**Issue by zhouLion** [Esri/arcgis-rest-js#322]
my app was run in 
## *the Node of v8.9 with the OS win10 *  , 
following is my code 
```
let { request } = require('@esri/arcgis-rest-request') 
let { HTTP_RESTFUL_URL } = require('../config/url')
request(baseUrl + url, {
        httpMethod: 'POST',
        params
 })
```
it will throw exception like below
![image](https://user-images.githubusercontent.com/19882767/45630110-932a8e80-baca-11e8-8d2f-bb0b51a5fc60.png)
- - -
is this package only work in modern browsers?

**Comment by itrew** [comment]
If you are running it in node, you need to supply your own fetch API and FormData API. You can use [isomorphic-fetch](https://www.npmjs.com/package/isomorphic-fetch) and [isomorphic-form-data](https://www.npmjs.com/package/isomorphic-form-data).  See the node-cli example [here](https://github.com/Esri/arcgis-rest-js/blob/d3f2553e59235c7657a074160a3694e06144b87e/demos/ago-node-cli/ago.js#L2-L3).

You would then load them into your app's index. 
```
require('isomorphic-fetch');
require('isomorphic-form-data');
```

**Comment by jgravois** [comment]
this is docced here: https://esri.github.io/arcgis-rest-js/guides/node/

if anyone has other ideas to surface this info more prominently, i'm all ears.

**Comment by patrickarlt** [comment]
@jgravois something might be up with https://github.com/Esri/arcgis-rest-js/blob/master/packages/arcgis-rest-request/src/request.ts#L161-L190 `request` should throw a helpful error message here.

**Comment by itrew** [comment]
Simple as `if (typeof Promise === 'undefined') {}` & `if (typeof FormData === 'undefined') {}` ?

**Comment by jgravois** [comment]
@itrew bingo. can't believe i missed that when i fixed fetch in https://github.com/Esri/arcgis-rest-js/pull/264/commits/90f9e75c513136c828e10faa757ada80ce389dd3.
