### ISSUE TITLE
clearly doc requirements for lib use

### ISSUE THREAD

**Issue by jgravois** [Esri/arcgis-rest-js#34]
* fetch polyfill
* user endpoints need to support CORS 
* browser/node versions
* ?

**Comment by patrickarlt** [comment]
I never looped back and updated this issue. Right now we are simply relying on globals that we expect users to install but we don't throw any errors or try anything fancy if they are not there or polyfills aren't loaded.

I could try to make the following work:

1. If `request` is called and we are in a browser environment (as far as we can tell) and we do not have the necessary globals, try to load the polyfills for the globals and try again.
2. If `request` is called in Node and the required globals are not found throw an error and try again.

I'm also ok with just throwing an error that links to the get stared guide if we cant find the globals.

**Comment by tomwayson** [comment]
> I'm also ok with just throwing an error that links to the get stared guide if we cant find the globals.

Works for me. We can always add the fancy stuff later.

**Comment by patrickarlt** [comment]
@tomwayson @jgravois ok then this probably needs to be a v1 issue then. I'll wrap this up tomorrow.

**Comment by tomwayson** [comment]
FYI - here's what I ended up doing for esri-loader:

https://github.com/Esri/esri-loader#promises
