### ISSUE TITLE
Feature Service introspection

### ISSUE THREAD

**Issue by ajturner** [Esri/arcgis-rest-js#349]
using the feature service interface, it would be helpful to provide introspection for getting layer + service metadata such as Fields (and types), version, etc.

**Comment by tomwayson** [comment]
you mean the `/info` endpoint, right? 

http://sampleserver6.arcgisonline.com/arcgis/rest/services/Census/MapServer/3/info/?f=pjson

For that I would suggest `getLayerInfo(requestOptions)` as the API.

**Comment by ajturner** [comment]
I didn’t know that endpoint existed. How is it different from just /0?f=JSON

The API should provide Layer info and service info.

**Comment by ajturner** [comment]
Another way to say this: what does Tugboat need for the harvesters?

**Comment by tomwayson** [comment]
Ha! I didn't know _that_ endpoint existed. Looks like they are the same.

@haoliangyu @dmfenton what do you need for the harvesters? It shall be yours!

**Comment by dmfenton** [comment]
We save all the metadata /FeatureServer and /FeatureServer/layer. When there is xml metadata passed through, we’ll want that too. The UI also needs the auth info at /FeatureServer/info (or something like that) to decide when to send tokens along.

Long way of saying, Hub Indexer needs every bit of metadata we can get our hands on.

**Comment by ajturner** [comment]
@dmfenton we were asking so you could enumerate “every bit of metadata” that exists or is useful based on current implementations. Where are the worker code that do these calls?

**Comment by dmfenton** [comment]
@ajturner Here is the code we use to derive metadata from:
- server info
- layer info
- org info
- xml metadata
https://github.com/ArcGIS/hub-indexer/blob/master/packages/duke/compose/dataset.js#L74

That said, we still save these full objects to our document store.

**Comment by dmfenton** [comment]
There are also more areas where we use layer or server metadata directly here:
https://github.com/ArcGIS/hub-indexer/blob/master/packages/api/schema.json

**Comment by tomwayson** [comment]
Is there a timeline for this, or some specific plan to update the harvester code?

**Comment by dmfenton** [comment]
@tomwayson was that directed at me? We don have any plans to use arcgis-rest-js in the harvester code right now. I don't know that we need to change any of the calls we are making or add any new ones with regards to metadata.

**Comment by ajturner** [comment]
I used the harvester as an example of comprehensive service/layer metadata.

________________________________

**Comment by jgravois** [comment]
this was resolved in https://github.com/Esri/arcgis-rest-js/pull/386
