### ISSUE TITLE
common-types not available

### ISSUE THREAD

**Issue by dgoldb2** [Esri/arcgis-rest-js#357]
Cannot find "/dist/umd/common-types.umd.min.js" in @esri/arcgis-rest-common-types@1.13.0

https://unpkg.com/@esri/arcgis-rest-common-types@1.13.0/dist/umd/common-types.umd.min.js

**Comment by jgravois** [comment]
the `common-types` package doesn't contain any JavaScript for us to bundle in a UMD. it only contains typings for TypeScript developers.

https://unpkg.com/@esri/arcgis-rest-common-types@1.13.0/dist/types/

**Comment by jgravois** [comment]
closing for housekeeping, but happy to chat more (at anytime) if it'd be helpful.
