### ISSUE TITLE
run travis build on windows?

### ISSUE THREAD

**Issue by tomwayson** [Esri/arcgis-rest-js#363]
Thanks to @gavinr  for the hot tip that Travis can now run your build on windows!

https://blog.travis-ci.com/2018-10-11-windows-early-release

At the risk of making our build take even longer...

**Comment by jgravois** [comment]
my first instinct is that our build already takes long enough. what i'd recommend first:
- [ ] make sure its clear in our contributing doc how to run tests _locally_ on windows
- [ ] confirm that the results of that are consistent with Linux/OSX

if we do the above and identify a scenario at some point that produces different results (or if anyone else disagrees), we can start targeting windows too.

**Comment by jgravois** [comment]
lets put this one in the icebox.
