### ISSUE TITLE
Support for Custom Value Domains

### ISSUE THREAD

**Issue by dmfenton** [Esri/arcgis-rest-js#375]
As a developer I should not have to know about custom value domains.

If I query `where=cvd=water`, I should not have to care that cvd stores the term `water` as the value `1`.

When data is displayed from this service I again should not have to know that `water` is stored as `1`. I should not have to decode the value myself, the library should handle that for me.

I recommend that this support be default but opt-out for those that know what they are doing with CVD's.

e.g.  `{decodeDomains: false}` to leave domains undisturbed.

**Comment by jgravois** [comment]
i'm into this idea.

has something like this already been implemented in the koop ecosystem anywhere?

**Comment by dmfenton** [comment]
Yes. There is prior art here:
https://github.com/GeoXForm/esri-to-geojson/blob/master/src/index.js#L193-L235
https://github.com/koopjs/winnow/blob/master/src/where.js#L74-L104

**Comment by tomwayson** [comment]
> I recommend that this support be default but opt-out for those that know what they are doing with CVD's.

I'm fine w/ that, but it would be a breaking change.
