### ISSUE TITLE
Getting #Views, Last Accessed, FileSize

### ISSUE THREAD

**Issue by simongis** [Esri/arcgis-rest-js#378]
I am looking to put together an app that lets me tidy up the content in my portal.

I would like to allow a user to view items that they own with some parameters to filter the list down:

- Has not been **accessed** in XX days 
- **Size** Is larger than XX size (megabytes)
- Is not [protected](https://esri.github.io/arcgis-rest-js/api/common-types/IItem/#protected)
- Is not in the [category ](https://esri.github.io/arcgis-rest-js/api/common-types/IItem/#categories)'Authoratative' 

**I know that usage stats and filesize is reported on an Item details page.  However, I am struggling to find the properties for them in the reference.  Can someone point me in the right direction?**

![image](https://user-images.githubusercontent.com/2769383/47928704-e1241600-df01-11e8-84ca-761cca092dbe.png)

![image](https://user-images.githubusercontent.com/2769383/47928696-dcf7f880-df01-11e8-9297-de27c64b6d64.png)

**Comment by jgravois** [comment]
> I know that usage stats and filesize is reported on an Item details page. However, I am struggling to find the properties for them in the reference.

i don't know about usage stats, but the last one is just [`size`](https://developers.arcgis.com/rest/users-groups-and-items/item.htm)

**Comment by simongis** [comment]
Thanks John.  The `numViews `and `size `will be really useful to filter on.

Should these properties also exist on the [IItem properties](https://esri.github.io/arcgis-rest-js/api/common-types/IItem/#categories)?

We can still get to them, so all good on that front.

> As a user, I  want to be able to filter my items down to the stale ones - ones that have not had any new views in the last XX days, so that I can consider deleting these. 

I spotted GeoJobe Admin tools does not offer 'Last Accessed'  it as a filter, which makes me think Last Modified + Views is as close as I can get?

![image](https://user-images.githubusercontent.com/2769383/47945104-a8ecf980-df3a-11e8-8952-f74f42785bbb.png)

**Comment by tomwayson** [comment]
> Should these properties also exist on the IItem properties?

Yes, looks to me like they should be added.
