### ISSUE TITLE
Possibly change feature add, update and delete params to match REST API at some point

### ISSUE THREAD

**Issue by COV-GIS** [Esri/arcgis-rest-js#391]
It's personal preference but `adds`, `updates` and `deletes` params really bother me for not being the REST params, e.g. `features` and `objectIds` respectively. I never fully understood the JS API having different param names from the REST API for queries and the like. I get it, `outSpatialReference` is more descriptive than `outSR`, but the rest of the param names here are REST API driven. I just like being able to look at the REST API docs and know I can pass any param as is.

I thought about it at the time the functions were added but didn't mention it. This would be a breaking change. So may never happen. But if there ever is a v2 candidate or other opening to change the param names I'd be happy to submit changes.

**Comment by jgravois** [comment]
we actually already discussed this in https://github.com/Esri/hub.js/issues/58

a PR that introduces `features` and `objectIds` and adds a [deprecation warning](https://github.com/Esri/arcgis-rest-js/blob/84ad2cdc3a3336fa2c33f7eb565aa359259c6871/packages/arcgis-rest-geocoder/src/helpers.ts#L72-L74) when parsing what we already have would be _most_ welcome.

**Comment by COV-GIS** [comment]
I'm not the only one then.

Will do.

**Comment by COV-GIS** [comment]
https://github.com/Esri/arcgis-rest-js/pull/396
