### ISSUE TITLE
Get Icons for Item Types?

### ISSUE THREAD

**Issue by simongis** [Esri/arcgis-rest-js#395]
With Web GIS content, there is an [ever growing range of Item Types.](https://developers.arcgis.com/rest/users-groups-and-items/items-and-item-types.htm)

**As a developer, I want:
- to be able to make a lookup request for an Item Types Icon
- to request the correct icon for any new Item types
- Parameter for either SVG or PNG response**

We are currently [pinching some logic ](https://github.com/Esri/ago-assistant/blob/6a336e8936c8850e8a28b03df59cc9a741bf2ab1/src/js/portal/info/items.json)from ago-assistant, but this does not cater for every type of Item.

I know Calcite [has the icons](https://github.com/Esri/arcgis-js-api/tree/master/themes/calcite/icons/images/svg) on there repo.

Not sure if it belongs in ArcGIS-REST-JS or if its an enhancement request for the REST API itself?

![image](https://user-images.githubusercontent.com/2769383/48697322-4fb1e500-ec1f-11e8-9c6e-bb2770f2c630.png)

**Comment by jgravois** [comment]
a new utility function that decorates an item with its icon _should_ be pretty straightforward (and would **definitely** be welcomed).

my instinct is that it could pull down the calcite-web resources from GitHub (or somewhere else) by default and support an option for developers to pass through their own baseUrl if they're being hosted locally.

```ts
appendItemIcon({
  item: { type: "Web Scene"} as IItem
})

// { type: "Web Scene", icon: "https://raw.githubusercontent.com/Esri/arcgis-js-api/master/themes/calcite/icons/images/svg/Web_Scene_32.svg" }

appendItemIcon({
  item: { type: "Web Scene"} as IItem,
  baseUrl: "https://foo.bar/"
})

// { type: "Web Scene", icon: "https://foo.bar/Web_Scene_32.svg" }
```

**Comment by patrickarlt** [comment]
As far as I know the icons that AGOL uses for item styles aren't available anywhere else. The calcite icons aren't the right ones and I know there are more icons then what AGO assistant handles https://github.com/Esri/ago-assistant/tree/6a336e8936c8850e8a28b03df59cc9a741bf2ab1/src/assets/images.

**Comment by simongis** [comment]
Just for info, our code on how we ended up approaching this:
https://github.com/bgtdevhub/housekeeping

And app:
https://housekeeping.bgtdevhub.com/

**Comment by patrickarlt** [comment]
I'm closing this. It is pretty unlikely that we are going to support this in ArcGIS REST JS. The logic for which icons to use for which item types is very specific to the AGOL interface and changes all the time as we add more icon types and change the UI. The icons are also not available anywhere we can currently consume them from.
