### ISSUE TITLE
Install script fails on Windows

### ISSUE THREAD

**Issue by hogpilot** [Esri/arcgis-rest-js#40]
I am unable to get a clean install by following the instructions on the README.md, While executing the `npm install`  process, it fails at the lerna command `npm run prepublish`.  I get the same error when using _Cygwin64 Terminal_ or _Git Bash_.  Below are my system details.
- Windows 8.1 Enterprise
- node 6.10.2
- npm 5.4.2
- lerna 2.2.0

I've attached a text file of the exact messages. [rest-js_npm_install_log.txt](https://github.com/ArcGIS/rest-js/files/1315978/rest-js_npm_install_log.txt)

**Comment by gavinr** [comment]
I am having issues running `npm install` on windows. I am getting:

```
lerna ERR! npm run prepare [@esri/arcgis-rest-request] Output from stderr:
[!] Error: Cannot find module '/mnt/c/github/arcgis-rest-js/packages/arcgis-rest-common/package.json'
Error: Cannot find module '/mnt/c/github/arcgis-rest-js/packages/arcgis-rest-common/package.json'
```

- `$ npm -v`
    - `6.9.0`
- `node -v`
    - `v10.16.0`

Anyone else having these issues?

**Comment by tomwayson** [comment]
try deleting the `node_modules` under `packages/arcgis-rest-request/` before running `npm i`
