### ISSUE TITLE
Remove malicious version of event-stream 

### ISSUE THREAD

**Issue by ryanewtaylor** [Esri/arcgis-rest-js#401]
According to dominictarr/event-stream#116 event-stream contains some malicious code. I do not understand the full impact at this time but it would appear this project has a (sub-sub-sub-sub) dependency on the impacted version. Note the reference to flatmap-stream@0.1.1 below.

```
$ npm ls event-stream flatmap-stream
@esri/arcgis-rest-js@1.14.1 C:\Dev\neip\arcgis-rest-js
`-- cz-lerna-changelog@1.2.1 (github:patrickarlt/cz-lerna-changelog#3fe7650a2e2e624b1f46e5031c96119759698288)
  `-- UNMET DEPENDENCY @semantic-release/commit-analyzer@2.0.0
    `-- UNMET DEPENDENCY conventional-changelog@0.0.17
      `-- UNMET DEPENDENCY event-stream@3.3.6
        `-- UNMET DEPENDENCY flatmap-stream@0.1.1

npm ERR! missing: @semantic-release/commit-analyzer@2.0.0, required by cz-lerna-changelog@1.2.1
npm ERR! missing: conventional-changelog@0.0.17, required by @semantic-release/commit-analyzer@2.0.0
npm ERR! missing: event-stream@3.3.6, required by conventional-changelog@0.0.17
npm ERR! missing: flatmap-stream@0.1.1, required by event-stream@3.3.6
```

See dominictarr/event-stream#116 for more details.

**Comment by jgravois** [comment]
thanks for the heads up. this is addressed in #402.

to be clear, `cz-lerna-changelog` isn't a dependency of the npm packages we maintain here. it is a **dev**Dependency and the only way to invoke that code is to clone this repo and run `npm run i && npm run c`.
