### ISSUE TITLE
update feature-service fns to use cleanUrl()

### ISSUE THREAD

**Issue by tomwayson** [Esri/arcgis-rest-js#403]
I think the feature-service package is probably most significant area where `cleanUrl()` still needs to be be applied (see https://github.com/Esri/arcgis-rest-js/pull/400#issuecomment-441808360)

**Comment by COV-GIS** [comment]
Hey @tomwayson. I can add `cleanUrl()` in feature service and PR if you'd like.

**Comment by jgravois** [comment]
closed via #404 :tada
