### ISSUE TITLE
oauth2-browser demo: "Sign In (inline redirect)" does not redirect correctly when not at url root

### ISSUE THREAD

**Issue by gavinr** [Esri/arcgis-rest-js#414]
When running the app at `http://localhost:5000/` it works ok, but if not at the root, ie `http://localhost:5000/path/to/arcgis-rest-js/demos/oauth2-browser/` it does not redirect correctly.

**Comment by jgravois** [comment]
thx for reporting (and patching) @gavinr! 🥇

if its more convenient you're also welcome to skip creating an issue entirely and just describe the problem you're solving in the pull request.
