### ISSUE TITLE
Authentication - how to use a token

### ISSUE THREAD

**Issue by previnWong** [Esri/arcgis-rest-js#425]
I have custom code to generate a token.  How can I use that token to in the addItemJsonData or updateItem calls.  Right now, I have to create a new userSession

```
            "token": this.generateToken(),
            "f": "json",
            "authentication": new restAuth.UserSession({
              username: "PrevinSolutions",
              password: "password"
            })
```
I'm using this as a widget in ArcGIS Web AppBuilder.
The generateToken is a function leveraging ArcGIS Web AppBuilder's core module to generate a token. Since the user is already logged in, I would like to leverage that and not force a second log in prompt when the user presses the button to update and item.

**Comment by jgravois** [comment]
this library contains comprehensive internal logic for selectively generating tokens, checking their expiration, determining whether a resource is federated and appending tokens to requests automatically so you're far better off relying on a [`UserSession`](https://esri.github.io/arcgis-rest-js/api/auth/UserSession/) than trying to generate static tokens on your own.

that said, the bookdoor to append _any_ random parameter to a request is `params`.

```js
const options = {
  // no need to pass a token, we'll do it for you
  authentication: new restAuth.UserSession({
    username: "PrevinSolutions",
    password: "password"
  }),
  params: {
    foo: "bar"
  }
}
```

this is documented under [`IItemDataAddRequestOptions`](https://esri.github.io/arcgis-rest-js/api/items/IItemDataAddRequestOptions/) and inherited from [`IRequestOptions`](https://esri.github.io/arcgis-rest-js/api/request/IRequestOptions/).

**Comment by jgravois** [comment]
does that answer your question @previnWong?

**Comment by previnWong** [comment]
yes it does, thank you. will close

**Comment by jgravois** [comment]
and my apologies. i didn't fully read your initial question.

i'm not _super_ familiar with WAB, but if you're able to generate access `IdentityManager`, that _also_ provides a means to instantiate/syncronize a UserSession.

https://github.com/Esri/arcgis-rest-js/blob/master/demos/jsapi-integration/index.html#L76-L80
