### ISSUE TITLE
Docs menu and content columns overlap

### ISSUE THREAD

**Issue by COV-GIS** [Esri/arcgis-rest-js#448]
The menu and content columns overlap; even at 1500px width for some longer names.

![image](https://user-images.githubusercontent.com/14297903/51619255-c3ed5b00-1ee4-11e9-89e5-8249a5475404.png)

**Comment by COV-GIS** [comment]
no longer an issue with shortened package names in toc

**Comment by jgravois** [comment]
_most_ of the packages are okay, but there are still a couple interfaces in `feature-service-admin` that overflow.
