### ISSUE TITLE
distribute a UMD bundle that only includes what's needed to complete the OAuth flow

### ISSUE THREAD

**Issue by tomwayson** [Esri/arcgis-rest-js#449]
In a couple apps now, when I've needed to create the redirect page to complete the OAuth flow, I've done so by loading the entire UMD bundle for arcgis-rest-auth like so:

```html
<!-- redirect.html -->
<!DOCTYPE html>
<html>
<head>
  <!-- arcgis-rest-js script to complete user sign in -->
  <!-- NOTE: this JS file is copied from node_modules by a package.json script -->
  <script src="./auth.umd.min.js"></script>
  <script>
    function loadHandler() {
      // get client id from url hash
      const match = window.location.href.match(/&state=([^&]+)/);
      const clientId = match && match[1];
      // complete the oauth flow
      session = arcgisRest.UserSession.completeOAuth2({
        clientId: clientId,
      });
    }
  </script>
</head>
<body onload="loadHandler();">
</body>
</html>
```

I think we should consider splitting the code needed to complete the OAuth flow out of that bundle and distribute a second script along side the current one.

I think this would be a matter of moving [completeOAuth2](https://github.com/Esri/arcgis-rest-js/blob/fc7b8f0ea32e97fb9539a8a7ee5c4ad77fa1dcbf/packages/arcgis-rest-auth/src/UserSession.ts#L298-L367) into it's own util module and creating a second rollup entry for it.

I think for backwards compatibility, `UserSession` will have to import that module and still expose that fn as a static method, which means the code will be included in the existing auth bundle as well. We can decide at the next major release if we want it in both bundles.

**Comment by jgravois** [comment]
if the `auth` package is loaded from the same location as it was in the app that spawned the OAuth 2.0 flow, isn't this 3kb file pretty much guaranteed to be served up from browser cache?

**Comment by tomwayson** [comment]
I'd say in most cases the auth package will be bundled along with other vendor dependencies, so this 3kb file will not be in the browser cache.

**Comment by tomwayson** [comment]
And sure, 3kb might not sound like too much, but it _is_ [our largest package](https://johngravois.com/devsummit/2019/rest-js/#/17).

**Comment by patrickarlt** [comment]
I'm going to close this. At 4.0 we are combining the `-auth` and `-request` package and with PKCE support `completeOAuth2()` might call `request` now so I don't think this is the most practical thing to do to shave a few kb off of a single page the user only sees when they sign in.
