### ISSUE TITLE
Regarding using software for commercial purpose.

### ISSUE THREAD

**Issue by mourya09** [Esri/arcgis-rest-js#470]
Hi All,

I under that arcgis-rest-js is fallen under two license part 1. ESRI license and another is Apache 2.0 license part. Is it possible to clarify which license will prevail if this library wants to use for the commercial purpose?

**Comment by jgravois** [comment]
`rest-js` only has one license, Apache 2.0.

https://github.com/Esri/arcgis-rest-js/blob/master/LICENSE

what led you to believe that there was a second license?

**Comment by mourya09** [comment]
> `rest-js` only has one license, Apache 2.0.
> 
> https://github.com/Esri/arcgis-rest-js/blob/master/LICENSE
> 
> what led you to believe that there was a second license?

Thanks Jgravois,

If you visit the url
[https://github.com/Esri/arcgis-rest-js#license](https://github.com/Esri/arcgis-rest-js#license)

and scroll down till last section "License" section. Here it is mentioned as 

> "Copyright © 2017-2019 Esri"

It made me think that this utility is licensed.

**Comment by jgravois** [comment]
[INAL](https://www.urbandictionary.com/define.php?term=INAL), but a copyright and a license are two very different things.

* a copyright establishes who owns the code.
* a license establishes what use is allowed and what is not.

reference: https://opensource.stackexchange.com/questions/297/whats-the-difference-between-copyright-and-licensing

**Comment by jgravois** [comment]
happy to chat more if anyone has any further questions about this.
