### ISSUE TITLE
clicking feature-service in the API ref TOC expands the sub menu for the admin package too

### ISSUE THREAD

**Issue by patrickarlt** [Esri/arcgis-rest-js#471]
> If you have time take a look at this... https://github.com/Esri/arcgis-rest-js/blob/master/docs/src/js/nav-toggle.js#L8-L12 matches both `@esri/arcgis-rest-feature-service` and `@esri/arcgis-rest-feature-service-admin`. So clicking `@esri/arcgis-rest-feature-service` opens both sub menus. I couldn't see a simple and elegant solution. Mildly annoying more than anything.
> 
> @COV-GIS in https://github.com/Esri/arcgis-rest-js/pull/469#issuecomment-467548082

**Comment by jgravois** [comment]
i'm not sure what i did is _elegant_, but the problem @COV-GIS reported is definitely fixed 😉
