### ISSUE TITLE
Should failure to refresh a token produce an ArcGISAuthError?

### ISSUE THREAD

**Issue by patrickarlt** [Esri/arcgis-rest-js#476]
Working on a demo for DevSummit I found this behavior and it struck me as odd:

```js
const session = new UserSession({
  username:"incorrect",
  password "incorrect"
});

session.getUser().catch(error => {
  console.log(error.name + " " + error.message); // ArcGISRequestError 400: Unable to generate token.
});
```

When we fail to refresh a token should we throw a `ArcGISAuthError` instead to give users the change to `ArcGISRequestError.retry` again? Right now this throws an `ArcGISRequestError` because `Unable to generate token.` is a 400 error not one of the cases in https://github.com/Esri/arcgis-rest-js/blob/master/packages/arcgis-rest-request/src/request.ts#L332.

**Comment by tomwayson** [comment]
Makes sense to me that it would throw an auth error.
