### ISSUE TITLE
docs: crud methods for feature services display a duplicate options table

### ISSUE THREAD

**Issue by jgravois** [Esri/arcgis-rest-js#479]
* [`addFeatures()`](https://esri.github.io/arcgis-rest-js/api/feature-service/addFeatures/)
* [`updateFeatures()`](https://esri.github.io/arcgis-rest-js/api/feature-service/updateFeatures/)
* [`deleteFeatures()`](https://esri.github.io/arcgis-rest-js/api/feature-service/deleteFeatures/)

**Comment by COV-GIS** [comment]
More than just the crud methods: [getGeocodeService()](https://esri.github.io/arcgis-rest-js/api/geocoder/getGeocodeService/) FYI.
