### ISSUE TITLE
Provide option to force request to use FormData content type

### ISSUE THREAD

**Issue by ssylvia** [Esri/arcgis-rest-js#499]
There are some API requests that require `FormData` as the content type. We need a fallback option to force the request to FormData when only JSON params are passed so `x-www-form-urlencoded` is used as the fallback.

**Comment by jgravois** [comment]
in [`v1.19.1`](https://github.com/Esri/arcgis-rest-js/releases/v1.19.1) and above `updateItemResource()` will use FormData automatically.

if you can do me a big favor and loop back _after_ June. i'd love to get confirmation that the underlying bug has been fixed.

**Comment by patrickarlt** [comment]
@jgravois even if the underlying bug IS fixed in June do we will leave this in place for people who are using older versions of Portal?

**Comment by jgravois** [comment]
great point.

The Portal API doc doesn't advertise when individual parameters landed in Enterprise. Its possible that by the time you can set `access` on an existing resource, FormData will no longer be required.

That's just a guess though. until we know for sure we should probably leave our check in place.
