### ISSUE TITLE
Problem with HTML description on updateItem

### ISSUE THREAD

**Issue by hhkaos** [Esri/arcgis-rest-js#501]
I don't understand why when I try to update [this item](https://awesome-arcgis.maps.arcgis.com/home/item.html?id=bb04b466539446cb9715943406c4c707) with this code:

```js
updateItem({
  item: {
    id: "bb04b466539446cb9715943406c4c707",
    description: "<h1>H1 Header</h1><p>Paragraph</p>",
    clearEmptyFields: true
  },
  authentication: session
}).then(response=>{
  console.log("response=",response)
});
```

The header tag is removed:

![Screen Shot 2019-03-31 at 01 53 45](https://user-images.githubusercontent.com/826965/55283297-dc9c4600-5357-11e9-8a78-12b6cbbd6700.png)

@jgravois are you "processing" the `description` field before sending the request? (I took a quick look to the [update.ts file](https://github.com/Esri/arcgis-rest-js/blob/master/packages/arcgis-rest-items/src/update.ts#L56) but I haven't seen it)

My code can be [found here](https://github.com/hhkaos/awesome-arcgis/blob/master/sync-product-items.js#L16).

Thanks in advance!

**Comment by jgravois** [comment]
> are you "processing" the description field before sending the request?

nope, the header tag is still there when we execute the request.

<img width="461" alt="Screenshot 2019-03-30 21 46 51" src="https://user-images.githubusercontent.com/3011734/55284941-62f36080-5335-11e9-96fc-1bd3e70286a7.png">

i can't say i know _why_, but `<h>` tags aren't included in the HTML supported in ArcGIS Online.

https://doc.arcgis.com/en/arcgis-online/reference/supported-html.htm

h/t to @ssylvia for the pointer in [`@esri/arcgis-html-sanitizer`](https://github.com/Esri/arcgis-html-sanitizer)

**Comment by hhkaos** [comment]
mMmMm, I see... but ... then it shouldn't work either when I enter it manually, should it?

![3D Analyst](https://user-images.githubusercontent.com/826965/55287568-f5821700-53aa-11e9-8103-702f43a32fa7.gif)

Thanks again! :smile:

**Comment by jgravois** [comment]
> but ... then it shouldn't work either when I enter it manually, should it?

`<h>` tags aren't being persisted in the item description when you use the GUI either. its just not evident until you refresh the entire page.

**Comment by jgravois** [comment]
closing, but happy to chat more about this if anyone has additional questions down the line.

**Comment by hhkaos** [comment]
Awesome John! thanks and sorry for the late reply.

Finally I have decided to parse the auto-generated HTML I was producing to replace it for <font size="X">.

I have now working [the product pages in the Awesome](https://esri-es.github.io/awesome-arcgis/arcgis/products/) in [a group](https://awesome-arcgis.maps.arcgis.com/home/group.html?id=663480a878724c42aef09a523a8d5139&view=list&start=1&num=20&searchTerm=#content) inside my awesome ArcGIS Online Organization :D

Now I'm also working in [a more visual product listing](https://esri-es.github.io/esri-products/) (many features still missing):

[![Screen Shot 2019-04-03 at 09 37 57](https://user-images.githubusercontent.com/826965/55461237-3faa0900-55f4-11e9-9f39-009f708d5f6c.png)](https://esri-es.github.io/esri-products/)

This workflow is really cool!, been able to collect my resources in markdown in a repo and then been able to use ArcGIS Online as a backend server/database to provide a more "ArcGIS Friendly" interface and then build a front-end to quickly search/understand the offering of the platform...

Let's see if it really serves me to reduce the learning curve of new users to our technology ^_^ (+ [this video](https://www.youtube.com/watch?v=FypLh7-djjM) I made to make a good first impression)

Thanks one more time :smile:

**Comment by jgravois** [comment]
awesome. looking _really_ good!
