### ISSUE TITLE
getItemData() throws JSON parsing error if data is empty

### ISSUE THREAD

**Issue by tomwayson** [Esri/arcgis-rest-js#504]
The error is:

```
Fetch item data error. SyntaxError: Unexpected end of JSON input
    at eval (VM12042 request.js:134)
```

If the data is empty, this function could return `null` instead of forcing consuming apps to test for the above error.

**Comment by jgravois** [comment]
@qlqllu this is resolved in [`v1.19.2`](https://github.com/Esri/arcgis-rest-js/releases/v1.19.2)

**Comment by qlqllu** [comment]
Thanks for your quick fix, it works now.

**Comment by pfcstyle** [comment]
If in Safari, the error is
`SyntaxError: The string did not match the expected pattern.`

So it still has problem in safari. @jgravois

**Comment by jgravois** [comment]
I won't be able to look into this anytime soon. i'd recommend opening a new issue with a code snippet that runs against an existing public item.

a PR would work too if you know how to fix the problem.

**Comment by pfcstyle** [comment]
Thanks @jgravois !  I submitted a PR: https://github.com/Esri/arcgis-rest-js/pull/677
