### ISSUE TITLE
v2.0.0 doc improvements

### ISSUE THREAD

**Issue by patrickarlt** [Esri/arcgis-rest-js#518]
Given the volume of changes in 2.0.0 there are a lot of doc related tasks. We have also gotten a lot better at writing TypeScript and thus the custom typedoc rendering can't handle our fancy new typings.

#### Guide

* [x] Written guide for new 2.x features (@jgravois or @tomwayson)
* [ ] Write a new v1.x > 2.x migration guide (@jgravois or @tomwayson)
* [x] Guide for composition using `withOptions()`
* [x] Guide for defaults using `setDefaultRequestOptions()`
* [x] Update the package overview page for the new packages  (@jgravois or @tomwayson)
* [x] Guide for searching for items using `SearchQueryBuilder`.
* [x] Consolidate the WebPack/Rollup guides into a single guide (possibly also add parcel?)  (@jgravois or @tomwayson)
* [ ] Add a Typescript specific guide to talk about the common types
* [x] Add a guide for tree shaking (specifically webpack) (@jgravois)
* [x] Remove the browserify topic  (@jgravois or @patrickarlt)
* [ ] Add guide for contributors to wrapping an API endpoint (@patrickarlt)
* [ ] Add guide for writing a new param builder (@patrickarlt)

#### API Ref

* [x] Link the REST API page for each method (@jgravois)
* [x] API ref for `SearchQueryBuilder` (@patrickarlt)
* [x] API ref for `withOptions()` (@patrickarlt)
* [x] API ref for `setDefaultRequestOptions()` (@patrickarlt)
* [x] Fix formatting for return type of `updateGroup()` also https://github.com/Esri/arcgis-rest-js/pull/523). (@patrickarlt)
* [x] Handle type params for `ISearchResponse` (@patrickarlt)
* [x] Render `results` in `ISearchResponse` properly (@patrickarlt)
* [x] Render values properly for things like `NODEJS_DEFAULT_REFERER_HEADER`. (@patrickarlt)
* [x] Sort parameter tables by (@patrickarlt)
  1. Required
  1. Required + Inherited
  1. Optional
  1. Optional + Inherited
* [x] Sort the lists of exported items in the API reference for clarity (@patrickarlt)
   1. Classes
   2. Functions
   3. Constants
   4. Enums
   5.  Interfaces

**Comment by jgravois** [comment]
we're going to need _at least_ one demo to show off `SearchQueryBuilder`.

it'd be nice to be able to share a live link, instead of point folks at our /demos folder.

**Comment by jgravois** [comment]
not every last item in this list is done, but we have enough to ship.
