### ISSUE TITLE
OAuth2 demo "No thanks" paths don't seem to work

### ISSUE THREAD

**Issue by MikeTschudi** [Esri/arcgis-rest-js#536]
Demo [arcgis-rest-js/demos/oauth2-browser/](https://github.com/Esri/arcgis-rest-js/tree/master/demos/oauth2-browser)

Popup path's "No thanks" opens an empty window with the url ".../authenticate.html#error=access_denied&error_description=The%20user%20denied%20your%20request."

Inline redirect path's "No thanks" leads to: "Uncaught TypeError: Cannot read property '1' of null" because match for the state variable returns a null.  

Inline's error can be prevented by changing authenticate.html to shield `clientId = match[1];`:
```
      const match = window.location.href.match(
        /&state=([^&]+)/
      );
      if (match) {
        const clientId = match[1];
        let session;
        function processAuthentication() {
          window.location.href = './';
          session = arcgisRest.UserSession.completeOAuth2({
            clientId: clientId,
          });
          localStorage.setItem('__ARCGIS_REST_USER_SESSION__', session.serialize());
        }
        processAuthentication();
      } else {
        window.location.href = './';
      }
```

This doesn't help the with popup path, however; with the above change, it opens a copy of the unsigned-in demo page in a new window.  

(The "Approve" path works with or without the above change.)

Tests were made using the following arcgis-rest-js:
```
<script src="https://unpkg.com/@esri/arcgis-rest-request/dist/umd/request.umd.js"></script>
<script src="https://unpkg.com/@esri/arcgis-rest-auth/dist/umd/auth.umd.js"></script>
```

**Comment by jgravois** [comment]
A PR that traps for this scenario would be (warmly) received.

**Comment by MikeTschudi** [comment]
@jgravois, your suggestion helped; the following is an improvement for Chrome, Firefox, IE11:

```javascript
      let match = window.location.href.match(
        /&state=([^&]+)/
      );
      if (match) {
        const clientId = match[1];
        let session;
        function processAuthentication() {
          window.location.href = './';
          session = arcgisRest.UserSession.completeOAuth2({
            clientId: clientId,
          });
          localStorage.setItem('__ARCGIS_REST_USER_SESSION__', session.serialize());
        }
        processAuthentication();
      } else {
        if (window.opener && window.opener !== window) {  // popups & inline with target=_blank
          window.close();
        } else {
          window.location.href = './';
        }
      }
```
The `if (match) {` `else` path is followed for both types of "No thanks".  At that point, the problem becomes distinguishing between the popup window, which should be closed, and the inline form, which must not be closed.

The test for the opener fails in one important case: if the app was launched from another page, e.g., by a link with a target parameter, then the inline form will close the app because the launching page is the opener of the app page.

Another failure is Edge, which opens a new window with the popup path, whether "Accept" or "No thanks", and sometimes "No thanks" results in a logged-in state.

So, still a work in progress....

**Comment by patrickarlt** [comment]
This doesn't really apply anymore with PKCE auth. I rewrote the demo on the `beta` branch.
