### ISSUE TITLE
OAuth2 demo appears to require use of default HTML name

### ISSUE THREAD

**Issue by MikeTschudi** [Esri/arcgis-rest-js#537]
Demo [arcgis-rest-js/demos/oauth2-browser/](https://github.com/Esri/arcgis-rest-js/tree/master/demos/oauth2-browser)

If the demo page does not have a default name, e.g., one invokes it via ".../demo.html", all paths (popup vs. inline, "Accept" vs. "No thanks") lead to an attempt to open ".../demo.htmlauthenticate.html?clientID=..."

Because the demo shows "Be sure to add [...]/demo.html as a redirect uri for your application.",
I tried pruning the redirect_uri in the demo to remove the HTML file name for both paths.  This works for the popup path's "Accept", but for the other paths, it attempts to list the contents of the website.

Tests were made using the following arcgis-rest-js:
```
<script src="https://unpkg.com/@esri/arcgis-rest-request/dist/umd/request.umd.js"></script>
<script src="https://unpkg.com/@esri/arcgis-rest-auth/dist/umd/auth.umd.js"></script>
```

**Comment by jgravois** [comment]
which specific OAuth demo?

[`oauth2-browser`](https://github.com/Esri/arcgis-rest-js/tree/master/demos/oauth2-browser)?

**Comment by MikeTschudi** [comment]
yes; thanks for checking

**Comment by patrickarlt** [comment]
@MikeTschudi I'm going to close those. I rewrote this demo on the `beta` branch recently and most of this is handled I think.
