### ISSUE TITLE
searchItems sortDir should be sortOrder

### ISSUE THREAD

**Issue by ssylvia** [Esri/arcgis-rest-js#540]
The [`searchItems`](https://esri.github.io/arcgis-rest-js/api/portal/searchItems/) takes the [`ISearchOptions`](https://esri.github.io/arcgis-rest-js/api/portal/ISearchOptions/#sortDir) with `sortDir` as a parameter. Per the [REST API docs](https://developers.arcgis.com/rest/users-groups-and-items/search.htm#GUID-A2C8BFD1-89B2-483F-9275-65D2786F6A6C), this should be `sortOrder` and not `sortDir`. I can confirm in my app that sort order does not work correctly when using `sortDir`.

**Comment by jgravois** [comment]
good catch.

i actually already (partially) caught this out myself. currently we whitelist _both_ props internally and pass them through as a request parameter.

https://github.com/Esri/arcgis-rest-js/blob/c5047acf0d86ae33d12f7e43447ae17aa56a7b00/packages/arcgis-rest-portal/src/util/generic-search.ts#L31

to put it another way, you can already use `sortOrder`. we just need to document it (and stop documenting `sortDir`).

```ts
// js
searchItems({
  q,
  sortOrder
}) 

// ts
searchItems({
  q,
  sortOrder
} as any) 
```
