### ISSUE TITLE
dependency on 'types' results in fatal AMD loader error

### ISSUE THREAD

**Issue by jgravois** [Esri/arcgis-rest-js#549]
right now, its necessary to use a hack in order to avoid the Dojo loader reporting an error failing to load a non-existent UMD file for `@esri/arcgis-rest-types` and aborting JS execution entirely.

```html
<script>
const emptyJsFile = `https://gist.githubusercontent.com/fago/c21491255cf9ee14d4731955bd8a4cf4/raw/ae5350a839fa43383277086a6bffe039e30d66ca/empty`;
dojoConfig = {
  paths: {
    "@esri/arcgis-rest-request": "https://unpkg.com/@esri/arcgis-rest-request@2.0.0/dist/umd/request.umd",
    "@esri/arcgis-rest-auth": "https://unpkg.com/@esri/arcgis-rest-auth@2.0.0/dist/umd/auth.umd",
    // trick the dojo loader into thinking JS for the types packages can be fetched
    "@esri/arcgis-rest-types": emptyJsFile
  }
};
</script>
<script src="https:////ajax.googleapis.com/ajax/libs/dojo/1.10.4/dojo/dojo.js"></script>
<script>
  require(["@esri/arcgis-rest-request", "@esri/arcgis-rest-auth"], function(arcgis) {
    arcgis.request("https://www.arcgis.com/sharing/rest/info").then(response => {
      console.log(response);
    });
  });
</script>
```

there must be something we can do in the library to make this clearer, even if its just shipping an (empty) UMD.

https://jsbin.com/bonaqur/edit?html,output

**Comment by jgravois** [comment]
cc/ @MikeTschudi

**Comment by patrickarlt** [comment]
Maybe we should ignore `-types` for the UMD builds. I'll see if there is anything in the rollup options that might help us.

**Comment by patrickarlt** [comment]
@jgravois maybe https://www.npmjs.com/package/rollup-plugin-ignore?

**Comment by jgravois** [comment]
> maybe https://npmjs.com/package/rollup-plugin-ignore?

i gave it a shot, but found no joy.

reverting to [`rollup-plugin-typescript2`](https://npmjs.org/package/rollup-plugin-typescript2) did the trick though.
