### ISSUE TITLE
the library isn't tree shakable anymore

### ISSUE THREAD

**Issue by jgravois** [Esri/arcgis-rest-js#555]

**Comment by patrickarlt** [comment]
I woke up this morning ready to tackle something unrelated to the rest of my project and decided to look at this again only to find it working.

![Screenshot 2019-05-10 07 25 49](https://user-images.githubusercontent.com/378557/57534518-094b6200-72f5-11e9-8eb7-ffe0449759f1.png)
![Screenshot 2019-05-10 07 26 37](https://user-images.githubusercontent.com/378557/57534519-09e3f880-72f5-11e9-9cf1-745f14740aec.png)

**Comment by jgravois** [comment]
must be your awesome new avatar!
