### ISSUE TITLE
Add  geoprocessing support

### ISSUE THREAD

**Issue by JeffJacobson** [Esri/arcgis-rest-js#569]
Unless I missed something, there doesn't seem to currently be any way to use Geoprocessing services.

I had to [write my own][arcgis-rest-gp] for a project recently. If you plan to add this capability, feel free to copy from [this project][arcgis-rest-gp]. Note that the asynchronous stuff  (submit job, cancel job) is still untested.

[arcgis-rest-gp]:https://github.com/WSDOT-GIS/arcgis-rest-gp

**Comment by jgravois** [comment]
> I had to write my own for a project recently.

**very** cool!

if you're game for it, the most expeditious thing would be for us to just advertise the package you already created.
