### ISSUE TITLE
'data' not in IItemAdd

### ISSUE THREAD

**Issue by nick-romano-kci** [Esri/arcgis-rest-js#577]
## Issue: 
'data' key not in IItemAdd

## Summary:
Misleading documentation, the example shows that the item argument should include a data object, while data is not defined in the IItemAdd, which is the Type for the item argument.

## Details:
- The documentation for createItem provides the example (https://esri.github.io/arcgis-rest-js/api/portal/createItem/):
```
createItem({
  item: {
    title: "The Amazing Voyage",
    type: "Web Map",
    data: {}
  },
  authentication
})
```

Where item is Type: IItemAdd ( https://esri.github.io/arcgis-rest-js/api/types/IItemAdd/)
```
export interface IItemAdd {
  title: string;
  type: string;
  owner?: string;
  typeKeywords?: string[];
  description?: string;
  snippet?: string;
  documentation?: string;
  extent?: number[][];
  categories?: string[];
  spatialReference?: ISpatialReference;
  culture?: string;
  properties?: any;
  url?: string;
  tags?: string[];
  [key: string]: any;
}
```

I could probably add a PR if this is indeed and issue.

**Comment by jgravois** [comment]
> the example shows that the item argument should include a `data` object

i wouldn't say _should_, but it's certainly an option.

as a TypeScript user, the fact that the interface contains `key: string]: any;` means you should be able to include data without encountering any errors or warnings.

i agree that `data` not being declared explicitly is a little confusing. the reason for this is that [`IItem`](https://esri.github.io/arcgis-rest-js/api/types/IItem/) extends `IItemAdd` and once an item has been created in ArcGIS Online, the `data` passed in previously doesn't hang off the item anymore, its available via a totally different endpoint.

https://esri.github.io/arcgis-rest-js/api/portal/getItemData/

**Comment by nick-romano-kci** [comment]
I didn't consider `[key: string]: any`, but I guess that does cover my issue.

I think it's a little confusing for someone entering the portal REST API cold-turkey without using typescript (just node), as the ItemData separation happens after the initial operation, resulting in some unexplained behind the scenes magic. But that's not the job of this API to fix.
