### ISSUE TITLE
Session add new method: serializeToEsriAuthCookie

### ISSUE THREAD

**Issue by qlqllu** [Esri/arcgis-rest-js#578]
Many esri apps are using `esri_auth` to save sign in session, so I think it would be great if session can be serialized to this cookie.

**Comment by tomwayson** [comment]
You should be able to use [session.toCredential()](https://esri.github.io/arcgis-rest-js/api/auth/UserSession/#toCredential), but if not let me know.

**Comment by qlqllu** [comment]
`session.toCredential()` does not return the `esri_auth` cookie format. I think I can do this in the app lavel but this may be a common feature.

**Comment by MehulChoksey** [comment]
Not sure what the context is here.. but it is important to note that in couple of releases, Esri auth cookies will be encrypted and it is strongly recommended to not have helper methods/functions for esri auth cookie.
cc @lalitha4499  @rosso

**Comment by dbouwman** [comment]
@MehulChoksey @lalitha4499 @Rosso Emailing to as more about this on an internal channel...

**Comment by patrickarlt** [comment]
My understanding is the the `esri_auth` cookie is specific to Esri apps and should only be set by a properly configured sign in experience for an Esri app like ArcGIS Online, ArcGIS for Developers, ect...

Give what @MehulChoksey said in https://github.com/Esri/arcgis-rest-js/issues/578#issuecomment-500286045 it also looks like we should ignore this entirely so I'm going to close this.
