### ISSUE TITLE
Set a specific error code when unable to refresh token

### ISSUE THREAD

**Issue by qlqllu** [Esri/arcgis-rest-js#597]
When unable to refresh token, the user session just through a general `ArcGISAuthError` at this line: https://github.com/Esri/arcgis-rest-js/blob/master/packages/arcgis-rest-auth/src/UserSession.ts#L775, it would be better if we can give it a error code.

**Comment by patrickarlt** [comment]
@qlqllu Good catch. If you want to PR a change you could just add a second param to that line with whatever you wanted the error code to be. Something like `TOKEN_REFRESH_FAILED`

**Comment by patrickarlt** [comment]
In 4.0 There is a new `ArcGISTokenRequestError` which will be thrown whenver a request for a token fails. THis is different from `ArcGISAuthError` which throws only for invalid token errors. More details will be forthcoming in the 4.0 release notes.
