### ISSUE TITLE
Ensure 'magicKey' property is passed through

### ISSUE THREAD

**Issue by hparkertt** [Esri/arcgis-rest-js#601]
The fix in #365 missed the 'magicKey' property.

**Comment by jgravois** [comment]
great catch. the problem actually occurs because of the whitelist we added later.

https://github.com/Esri/arcgis-rest-js/blob/0768eab390912591e0aadbfbed114a306d991a01/packages/arcgis-rest-
geocoding/src/geocode.ts#L94-L106

a Pull Request with a fix would be _most_ welcome.

**Comment by hparkertt** [comment]
Should I commit on top of the current origin/HEAD (0768eab) or on top of Dave Bouwman's tagged v2.2.1 commit (528a4dc)?

**Comment by jgravois** [comment]
the fact that @dbouwman's most recent release tag never made it to `master` is _another_ great catch.

as for your PR, you should definitely still branch off origin/HEAD. ideally they'll merge the work as soon as they sort out ^^

**Comment by hparkertt** [comment]
Thanks, @jgravois!  I'll chalk this up as a productive Tuesday for me!  I'll make the quick change and put together a pull request shortly.
