### ISSUE TITLE
Docs are not being updated

### ISSUE THREAD

**Issue by COV-GIS** [Esri/arcgis-rest-js#602]
Published docs are still on v2.0.3. The SRI hashes are not valid for v2.0.3 which doesn't matter when docs next updated. Can confirm v2.2.0 SRI hashes in `srihashes.json` are correct.

**Comment by jgravois** [comment]
a revoked [`GITHUB_TOKEN`](https://github.com/Esri/arcgis-rest-js/blob/master/.travis.yml#L18) of mine is the most likely culprit.

I could have sworn @tomwayson already addressed that though.

**Comment by COV-GIS** [comment]
The readme travis badge has been `build error` since about that time. So it might not be addressed.

**Comment by COV-GIS** [comment]
@tomwayson 

https://travis-ci.org/Esri/arcgis-rest-js/jobs/569439361#L794

Before next release maybe? :)

**Comment by tomwayson** [comment]
I've finally replaced the github token, and this issue is now resolved:

**Comment by COV-GIS** [comment]
Thanks @tomwayson.

**Comment by COV-GIS** [comment]
Hey @tomwayson. The project is on release 2.4.0. But the docs are on 2.3.0. And only one of two jobs is passing https://travis-ci.org/Esri/arcgis-rest-js/builds/580361215.

I realize there was a disconnect there for a bit. But perhaps you can get everything lined backed up before the next release.

Thanks again.
