### ISSUE TITLE
API for FeatureService

### ISSUE THREAD

**Issue by tomrussell** [Esri/arcgis-rest-js#606]
Hey guys,

I'm trying to access information on a given FeatureService - listing out the layers primarily. I noticed you had discussed adding a `getService` API (#46) but I can't seem to find reference to this in the code

I had planned on writing functionality and types for querying these endpoints in our own codebase but wondered if adding this to the library was still part of your roadmap

**Comment by jgravois** [comment]
that'd be great (and it wouldn't be much work).

[`getLayer()`](https://github.com/Esri/arcgis-rest-js/blob/0768eab390912591e0aadbfbed114a306d991a01/packages/arcgis-rest-feature-layer/src/getLayer.ts) is probably the best reference point to get started.

you can reuse the [`ILayerDefinition`](https://esri.github.io/arcgis-rest-js/api/types/ILayerDefinition/) interface too.
