### ISSUE TITLE
Clarify performance implications of queryFeatures() vs ArcGIS API

### ISSUE THREAD

**Issue by tomwayson** [Esri/arcgis-rest-js#612]
Our docs should explain that [queryFeatures()](https://esri.github.io/arcgis-rest-js/api/feature-layer/queryFeatures/) does not do any of the fancy stuff that a [FeatureLayer](https://developers.arcgis.com/javascript/latest/api-reference/esri-layers-FeatureLayer.html)  ~~FeatureLayer.queryFeatures()~~ does like break the query into multiple requests in a grid. Nor do we handle PBF format, etc. 

We can say that those fancy features are generally not needed when performing count only or statistic queries, or if you have a tabular view that pages through a few records at a time. However, if you intend to show query results on a map, you are better off using the ArcGIS API for JavaScript.

**Comment by pspraveenkr** [comment]
> [FeatureLayer.queryFeatures()](https://developers.arcgis.com/javascript/latest/api-reference/esri-layers-FeatureLayer.html#queryFeatures) does like break the query into multiple requests in a grid

@tomwayson - FL.queryFeatures doesn't make tiled/grid requests though. It's up to the caller to do that if needed.
