### ISSUE TITLE
searchGroupUsers: Search Options Should Be Optional

### ISSUE THREAD

**Issue by drewctate** [Esri/arcgis-rest-js#615]
The [commented documentation for the searchGroupUsers function](https://github.com/Esri/arcgis-rest-js/blob/0768eab390912591e0aadbfbed114a306d991a01/packages/arcgis-rest-portal/src/groups/get.ts#L128) implies that the `searchOptions` argument is optional. In practice, that isn't the case because the function fails [here](https://github.com/Esri/arcgis-rest-js/blob/0768eab390912591e0aadbfbed114a306d991a01/packages/arcgis-rest-portal/src/groups/get.ts#L142) unless `searchOptions` are provided.

**Comment by jgravois** [comment]
good catch!

if you'd like to take a stab at a PR, you can find a few other good examples in the same file that use destructuring to achieve the desired result.

**Comment by drewctate** [comment]
Sure thing
