### ISSUE TITLE
getTokenForServer fails to refresh expired tokens

### ISSUE THREAD

**Issue by oselz** [Esri/arcgis-rest-js#621]
When a UserSession has a server with username and password it will only ever fetch one token, and then fails to update the token after it expires.  
```
const session = new UserSession({
    username: abc,
    password: def,
    server: my_enterprise_server_url,
    tokenDuration: 1,
})
request(someresource, {authentication: session})
--> works
(wait 1 minute)
request(someresource, {authentication: session})
--> fails (invalid token)
```

The reason is getTokenForServer checks for pending requests:

```
if (this._pendingTokenRequests[root]) {
      return this._pendingTokenRequests[root];
    }
```
however this check will _always_ be hit as the pending request is a Promise, thus will still exist as an object even after it is resolved.

The solution is to clear _pendingTokenRequests[root] when the promise resolves.

See https://github.com/Esri/arcgis-rest-js/pull/620

**Comment by patrickarlt** [comment]
This will be resolved in the upcoming 4.0 release which is currently on the `beta` branch.
