### ISSUE TITLE
geocode should accept and pass along outFields

### ISSUE THREAD

**Issue by tomwayson** [Esri/arcgis-rest-js#626]
See: https://developers.arcgis.com/rest/geocode/api-reference/geocoding-find-address-candidates.htm

[IGeocodeOptions](https://esri.github.io/arcgis-rest-js/api/geocoding/IGeocodeOptions/) does not currently support `outFields`.

I've confirmed that passing the following works as a workaround:

```js
params: {
  outFields: 'Place_addr'
}
```

**Comment by mpayson** [comment]
Added in #641 - closing
