### ISSUE TITLE
queryFeatures function - inSR paramater not taken in account

### ISSUE THREAD

**Issue by jsauca** [Esri/arcgis-rest-js#628]
"@esri/arcgis-rest-feature-layer": "^2.5.0",

The inSR paramaters is not taken into account

`    

 const queryParams = {
      url,
      geometry: { x: 151.11403770000004, y: -33.7842727 },
      geometryType: geometryType === 'point' ? 'esriGeometryPoint' : 'esriGeometryPolygon',
      spatialRel: 'esriSpatialRelIntersects',
      where: filters,
      inSR: '4326',
      outSR: '4326',
      returnGeometry: true,
      f: 'json',
    };

    const queryFeature = queryFeatures(queryParams);`

FYI, REST API with same data provided works correctly. See => https://maps.six.nsw.gov.au/arcgis/rest/services/public/NSW_Cadastre/MapServer/9/query?where=&text=&objectIds=&time=&geometry=%7B+x%3A+151.11403770000004%2C+y%3A+-33.7842727+%7D&geometryType=esriGeometryPoint&inSR=4326&spatialRel=esriSpatialRelIntersects&relationParam=&outFields=&returnGeometry=true&returnTrueCurves=false&maxAllowableOffset=&geometryPrecision=&outSR=4326&returnIdsOnly=false&returnCountOnly=false&orderByFields=&groupByFieldsForStatistics=&outStatistics=&returnZ=false&returnM=false&gdbVersion=&returnDistinctValues=false&resultOffset=&resultRecordCount=&queryByDistance=&returnExtentsOnly=false&datumTransformation=&parameterValues=&rangeValues=&f=html

**Comment by jgravois** [comment]
similar: https://github.com/Esri/esri-leaflet/issues/1167

a PR with a fix would be happily landed.

**Comment by mpayson** [comment]
Added in #641 - closing
