### ISSUE TITLE
BulkGeocode - adding params causes error 

### ISSUE THREAD

**Issue by gavinr** [Esri/arcgis-rest-js#630]
## Summary
When I add a `params` property to my `bulkGeocode` function call, I get an error.

## Expected
I should be able to add a `params` property to the passed object to pass arbitrary parameters to the REST call, per [the doc](https://esri.github.io/arcgis-rest-js/api/geocoding/bulkGeocode/#params).

## Actual
When I pass just `addresses` property to `bulkGeocode()`, [it works fine](https://codepen.io/gavinr/pen/vYYgLWQ):

```js
arcgisRest.bulkGeocode({ 
    endpoint: '...',
    addresses: [...]
  })
  .then((response) => {
    console.log('res', response);
  });
```

When I add a `params` property (below is what I'm using, but I think it happens with any contents of the params object):

```js
arcgisRest.bulkGeocode({ 
    endpoint: '...',
    addresses: [...],
    params: {
      outSR: '4326'
    }
  })
  .then((response) => {
    console.log('res', response);
  });
```

... I get this error: ([code showing issue](https://codepen.io/gavinr/pen/MWWJyNZ))

```
Uncaught TypeError: Cannot read property 'records' of undefined
    at bulk.ts:78
```

**Comment by gavinr** [comment]
@jgravois I was comparing the batch code to the geocoder code - would it make sense to utilize the [appendCustomParams](https://github.com/Esri/arcgis-rest-js/commit/99300a8c1a73fa9c9a77a592b672e3cc53b4ff65#diff-3e2ebf3255ae6b0604225f67f678f5dcR78) module in bulkGeocoder as well ([here](https://github.com/Esri/arcgis-rest-js/blob/cba6e5647a99d7154780cf9bf5f99c2ac90924f4/packages/arcgis-rest-geocoding/src/bulk.ts#L67-L74))?

**Comment by jgravois** [comment]
that would allow you to define an interface that exposed more properties specific to the operation as 'first class citizens'. if I could do it all over again I'd only do that for required parameters though.

I think [intimidating interfaces](https://esri.github.io/arcgis-rest-js/api/feature-layer/IQueryFeaturesOptions/) overwhelm the benefit of an 'uglier' signature. For everything optional, the `params` backdoor works just fine.
