### ISSUE TITLE
type: enum that can represent LineSymbolStyles

### ISSUE THREAD

**Issue by kumarGayu** [Esri/arcgis-rest-js#654]
can we have this types. so that it is easy for readability and user can use enum to define the type.

```
export const enum LineSymbolStyles {
  dash = "esriSLSDash",
  dashDot = "esriSLSDashDot",
  dashdotdot = "esriSLSDashDotDot",
  dot = "esriSLSDot",
  solid = "esriSLSSolid"
}
```

**Comment by maneetgoyal** [comment]
Adding some quick details:

1. Currently, `arcgis-rest-types` exports:
```ts
export type SimpleLineSymbolStyle =
  | "esriSLSDash"
  | "esriSLSDashDot"
  | "esriSLSDashDotDot"
  | "esriSLSDot"
  | "esriSLSNull"
  | "esriSLSSolid";

export interface ISimpleLineSymbol extends ISymbol {
  type: "esriSLS";
  style?: SimpleLineSymbolStyle;
  color?: Color;
  width?: number;
}

// etc.
```

2. As Kumar pointed out, if the following is done instead, it is serving more use cases.

```ts
export const enum SimpleLineSymbolStyle {
  Dash = "esriSLSDash",
  DashDot = "esriSLSDashDot",
  DashDotDot = "esriSLSDashDotDot",
  Dot = "esriSLSDot",
  Solid = "esriSLSSolid",
  Null = "esriSLSNull"
}

export interface ISimpleLineSymbol extends ISymbol {
  type: "esriSLS";
  style?: SimpleLineSymbolStyle;
  color?: Color;
  width?: number;
}

// etc.
```

3. As enums can be used as types too, the older usage isn't changing much. Further, we have cases wherein a particular `SimpleLineSymbolStyle` value needs to be assigned to a variable. With enums, we wouldn't need to maintain our own list of strings and be readily in sync with `arcgis-rest-types`.

**Comment by jgravois** [comment]
sounds reasonable enough to me.

please open a pull request with the proposed change and we can continue the discussion there.

**Comment by maneetgoyal** [comment]
@subgan82 @pemberdom
