### ISSUE TITLE
Include state in server OAuth?

### ISSUE THREAD

**Issue by mpayson** [Esri/arcgis-rest-js#660]
I noticed state isn't passed to `authorize` for server-based OAuth, should this be included?

https://github.com/Esri/arcgis-rest-js/blob/master/packages/arcgis-rest-auth/src/UserSession.ts#L460

**Comment by jgravois** [comment]
from the JSDoc it looks like it was a conscious choice in this library to flag state as `@browserOnly`

https://github.com/Esri/arcgis-rest-js/blob/25778e3e6b16d73cc22a79a7b9bc1c97f4f90ac4/packages/arcgis-rest-auth/src/UserSession.ts#L139-L144

but looking at the REST API doc, I'm not seeing anything that indicates it isn't valid for server-based flows.

https://developers.arcgis.com/rest/users-groups-and-items/authorize.htm

> should this be included?

do you have a use case that is improved by including it?
if so, if you've tested it and it works, that sounds like enough of a reason to me to open a PR and continue the discussion there.

**Comment by mpayson** [comment]
👋 @jgravois 

📝 Partners often have their own log in system and want to allow Esri-users to connect their ArcGIS account. This is commonly done on the server to store refresh tokens. So, the server needs to know in the `redirect` who the user is in the partner's system. One approach would be sessions, another would be the `state` param for stateless auth mechanisms (eg JWTs passed from the client)
✅ It works

I've been playing around with these workflows, so curious to hear if this is considered best practice or not. Thanks and LMK if you'd like a PR on my end!

**Comment by jgravois** [comment]
👋 old friend.

given the REST doc I linked to above and your own feedback, I think the library would benefit from passing through `state`. feel free to open a PR at your leisure.

**Comment by patrickarlt** [comment]
This will be resolved at 4.0 which is currently on the `beta` branch.
