### ISSUE TITLE
using popup oauth in an iframed app results in the app opening in the popup

### ISSUE THREAD

**Issue by tomwayson** [Esri/arcgis-rest-js#674]
STR:

- add a file called `framed.html` as a peer to `index.html` in the oauth2 browser demo, w/ the following content:

```html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>iFramed - ArcGIS REST JS Browser OAuth2</title>
  </head>
  <body>
    <iframe src="./" width="80%" height="600"></iframe>
  </body>
</html>
```

- follow the instructions to run the demo, but load http://localhost:8080/framed.html instead
- sign in w/ popup, you'll see this:

<img width="1089" alt="image" src="https://user-images.githubusercontent.com/662944/76985957-406ba600-68fe-11ea-84b8-cb0fc07e66c3.png">

I haven't thoroughly debugged this, but it seems in this case, we wouldn't get passed this line:

https://github.com/Esri/arcgis-rest-js/blob/869f466c47b2e80768018b20c89c6279212767aa/packages/arcgis-rest-auth/src/UserSession.ts#L362

b/c the `opener` is `index.html`, but it's `parent` is `framed.html`, so `win.opener.parent[`__ESRI_REST_AUTH_HANDLER_${clientId}`]` will be undefined, but `win.opener.[`__ESRI_REST_AUTH_HANDLER_${clientId}`]` should exist.

**Comment by patrickarlt** [comment]
This seems to work as expected now on the `beta` branch. Closing.
