### ISSUE TITLE
arcgis-rest-types package.json does not have main field

### ISSUE THREAD

**Issue by qlqllu** [Esri/arcgis-rest-js#680]
`arcgis-rest-types` package.json does not have `main` field, this causes type error in some cases (cause unit tests type error in our case). This is as design or the main field is lost?

**Comment by jgravois** [comment]
given that there is no compiled JavaScript being produced, what would you suggest?

```js
// ?
"main": "/src/index.ts"
```
https://unpkg.com/browse/@esri/arcgis-rest-types@2.10.0/

**Comment by qlqllu** [comment]
@jgravois 
Yes, `"main": "/src/index.ts"` is what i am expecting.

**Comment by jgravois** [comment]
seems reasonable enough to me. feel free to open a PR and others can chime in.

**Comment by patrickarlt** [comment]
Closing this we are removeing `arcgis-rest-types` at 4.0 so this won't be an issue anymore.
