### ISSUE TITLE
Make refresh token TTLs consistent

### ISSUE THREAD

**Issue by mpayson** [Esri/arcgis-rest-js#699]
According to the REST doc the [expiration /authorize](https://developers.arcgis.com/rest/users-groups-and-items/authorize.htm) parameter sets the refresh token TTL for server-based OAuth. Currently we handle these differently.

Expiration is defined by `duration` (default 20160) in [`authorize`](https://github.com/Esri/arcgis-rest-js/blob/master/packages/arcgis-rest-auth/src/UserSession.ts#L455) while the refresh token TTL is set by `refreshTokenTTL` param (default 1440) in [`exchangeAuthorizationCode`](https://github.com/Esri/arcgis-rest-js/blob/master/packages/arcgis-rest-auth/src/UserSession.ts#L481) without actually specifying this to the server.

A couple ideas to approach:
1. Update defaults to be the same
2. Respect `refreshTokenTTL` instead of `duration` in `authorize` (or fall back to `duration` for compatibility)?
3. Maybe pass in the `refreshTokenTTL` as state (ref #660 ) then set it in `exchangeRefreshToken` to ensure it's consistent between the two methods?

Let me know your thoughts and happy to PR if there's an updated approach!

**Comment by patrickarlt** [comment]
This will be resolved in the upcoming 4.0 release which is currently on the `beta` branch
