### ISSUE TITLE
tree shaking demos should includ setDefaultRequestOptions()

### ISSUE THREAD

**Issue by tomwayson** [Esri/arcgis-rest-js#706]
to make sure that using the module scoped variables is compatible w/:

https://github.com/Esri/arcgis-rest-js/blob/98b1f8ef161bf3cf4c44010a7c4468d62dce69a7/packages/arcgis-rest-request/package.json#L9

**Comment by patrickarlt** [comment]
This should work fine now at 4.0. I changed this to assign the defaults to `globalThis.DEFAULT_ARCGIS_REQUEST_OPTIONS` so there isn't any way for this to be optimized out. It is just a pair of methods to update an object we use to update a global object.
