### ISSUE TITLE
getUser returns the information for the current usersession

### ISSUE THREAD

**Issue by FardoshtAmirpanahi** [Esri/arcgis-rest-js#709]
I create a user session with a system account user credentials which had admin role.

```js
     this.adminSession = new UserSession({
        username: this.username,
        password: this.pwd
      });
Then I create a query 
        let query = new SearchQueryBuilder()
        .startGroup()
          .match(userName)
          .in("username")
        .endGroup()
```

But when I execute getUser method, the account information of the admin user is returned.

```js
    this.searchMember = getUser({q: query, authentication: this.adminSession }).then(response 
=> {
        alert(response.lastName)
        }).catch(error =>{
          aler(error)
        })
```
And searchUsers method returns an undefined object.

```js
this.searchMember = searchUsers({q: query, authentication: this.adminSession }).then(response => {
        alert(response.length)
        }).catch(error =>{
          alert(error)
        })
```

Appreciate any hint or suggestion to this problem.
Kind Regards,
Fardosht

**Comment by patrickarlt** [comment]
@FardoshtAmirpanahi `searchUsers` https://esri.github.io/arcgis-rest-js/api/portal/searchUsers/  does not return an array.  It returns a `ISearchResult` object which corresponds with the REST API https://esri.github.io/arcgis-rest-js/api/portal/ISearchResult/

Using `response.results.length` should return `1`.

**Comment by FardoshtAmirpanahi** [comment]
Hi Patrick,
I just realized it.
Thank you for the quick reply.
