### ISSUE TITLE
push up live doc site

### ISSUE THREAD

**Issue by jgravois** [Esri/arcgis-rest-js#71]
have we decided where this is going to live yet? `gh-pages`? surge?

**Comment by patrickarlt** [comment]
I vote for `gh-pages` because it is easy. https://www.npmjs.com/package/gh-pages could help automate deployment too.

**Comment by jgravois** [comment]
i agree, but the current design of the docs and typedoc file assume the site will land in the root of a domain (not at https://esri.github.io/arcgis-rest-js/)

it was a bigger pain than i expected this afternoon to get enough tweaks in place, so lets point folks at http://arcgis-rest-js.surge.sh/ until i have time to dig in deeper.

**Comment by jgravois** [comment]
closing, but happy to revisit using github pages later if anyone has the bandwidth.
