### ISSUE TITLE
Add wrappers for portal roles endpoints

### ISSUE THREAD

**Issue by FardoshtAmirpanahi** [Esri/arcgis-rest-js#710]
We use custom roles in our organization which are based on the default roles.  So for instance, we have modified the default privileges for the Publisher role and name the new role "Our Publisher:

I use  searchUsers() method to find a user.  If the use has been given any of these custom roles, the **response.results[0].role**  would return an encrypted value like this "9GFNWVFxPzullXv7". 

How can I get the actual name?

Best regards,
Fardosht

**Comment by FardoshtAmirpanahi** [comment]
In Python users.roles.get_role("custom role id") would return the role name and description.

but the response.results[0].roleId returns undefined. 
return searchUsers({authentication: this.adminSession, portal:this.agolHome,  q: query }).then(response => {
        alert(response.results[0].roleId)

**Comment by patrickarlt** [comment]
You'll need to use the generic `request` method to call https://developers.arcgis.com/rest/enterprise-administration/server/searchroles.htm on the REST API. We don't have the equivalent of `get_role` in ArcGIS REST JS yet. https://esri.github.io/arcgis-rest-js/api/request/request/

**Comment by patrickarlt** [comment]
We should probably add methods for these long term however it looks like there are different methods for Enterprise Admin vs Portal which is a little confusing.

**Comment by patrickarlt** [comment]
@FardoshtAmirpanahi you might also want https://developers.arcgis.com/rest/users-groups-and-items/role.htm depending on your use case.

**Comment by FardoshtAmirpanahi** [comment]
Thanks for all your suggestions.
