### ISSUE TITLE
getPortalUrl() => getPortalApiUrl()

### ISSUE THREAD

**Issue by tomwayson** [Esri/arcgis-rest-js#728]
[`getPortalUrl`](https://esri.github.io/arcgis-rest-js/api/portal/getPortalUrl/) really returns the URL of the Portal's API, and I think it should be named `getPortalApiUrl()`.

**Comment by patrickarlt** [comment]
@tomwayson do you want to do this for 4.0 and deprecate `getPortalUrl()`?

**Comment by tomwayson** [comment]
Will do after #911 is merged.
