### ISSUE TITLE
SingleLine address - search addresses starting with

### ISSUE THREAD

**Issue by bigalnz** [Esri/arcgis-rest-js#731]
If I type into the search widget in google maps "23 Quee" and stop, the typeahead options are:
23 Queens Avenue, Mount Eden, Auckland
23 Queens Road, Panmure, Auckland
23 Queens Street, Northcoate, Auckland
etc
etc

If I send the same string "23 Quee" to the REST API with a country restriction of NZL - I get exactly one result (and its none of the above)

Its like the API is trying to match "23 Quee" as a full address rather than addresses that begin with this string.

Is there anyway to change this behavior or a begins with type option?

Thanks

**Comment by gavinr** [comment]
API Key help is here: https://developers.arcgis.com/arcgis-rest-js/authentication/tutorials/authenticate-with-an-api-key/
