### ISSUE TITLE
`removeItemRelationship` is not working

### ISSUE THREAD

**Issue by yankuanz** [Esri/arcgis-rest-js#739]
Hi, this is my first issue in this project and this library has been bringing lots of convenience to my team! Thank you!

---

**What I expected**: `removeItemRelationship` (or a new API `deleteItemRelationship`) can remove item relationships.
**What I saw**: `removeItemRelationship` is always returning a 400 error: "User folder does not exist."

It seems the `removeItemRelationship` API is [using endpoint `/removeRelationship` in the implementation](https://github.com/Esri/arcgis-rest-js/blob/master/packages/arcgis-rest-portal/src/items/remove.ts#L63), but the REST API only supports [`/deleteRelationship`](https://developers.arcgis.com/rest/users-groups-and-items/delete-relationship.htm).

**Comment by dbouwman** [comment]
@yankuanz Thanks for letting us know - PR is up, and we'll have a release out later today/tomorrow.

**Comment by dbouwman** [comment]
@yankuanz this is resolved in v2.16.0 which was just published to npm. Thanks again for letting us know!

**Comment by yankuanz** [comment]
@dbouwman Thanks for the prompt response 🚀🚀🚀!
