### ISSUE TITLE
completeOAuth2() is blocked by 'Same-origin policy' from within a cross-origin iframe.

### ISSUE THREAD

**Issue by shUpt555** [Esri/arcgis-rest-js#751]
@dbouwman Could you please help to look into this problem?

I think #714 is a nice work, but when trying to access the `win.opener.parent[handlerFnName]` from within a cross-origin iframe, the accessing is blocked and get an error in the console: 

_"Unable to complete authentication. It's possible you specified popup based oAuth2 but no handler from "beginOAuth2()" present. This generally happens because the "popup" option differs between "beginOAuth2()" and "completeOAuth2()"."_

**Comment by mpriour** [comment]
> from within a cross-origin iframe, the accessing is blocked

That is the correct behavior in a modern browser. Allowing such access would be a serious security flaw.

**Comment by dbouwman** [comment]
@shUpt555 As @mpriour notes, this is expected. 

At this time there is no standardized, secure means to pass Esri auth into iframed, cross-origin applications.

**Comment by shUpt555** [comment]
Thanks @mpriour and @dbouwman. Closed.
