### ISSUE TITLE
subGeographyLayer and returnSubGeographyLayer is not working with studyAreas

### ISSUE THREAD

**Issue by haseebanwar** [Esri/arcgis-rest-js#801]
ArcGIS REST API for `GeoEnrichmentService` accepts the two parameters `subGeographyLayer` and `returnSubGeographyLayer`. Howerver, when I use `queryDemographicData` function from `@esri/arcgis-rest-demographics` I see no way to pass these options. It looks like the `queryDemographicData` funtcion accepts an array of object with just three following properties.

```javascript
const response = await queryDemographicData({
      studyAreas: [
        {
          sourceCountry: 'US',
          layer: 'US.States',
          ids: ['06'],
          subGeographyLayer: ['US.Places'], // ignored by library
          returnSubGeographyLayer: true, // ignored by library
        },
      ],
      authentication,
    });
```

Any workaround to pass these options with `queryDemographicData` function?

**Comment by gavinr** [comment]
The `queryDemographicData` calls the [enrich REST API endpoint](https://developers.arcgis.com/rest/geoenrichment/api-reference/enrich.htm) - I see neither `subGeographyLayer` nor `returnSubGeographyLayer` on that page - can you please link to the documentation where you are seeing `subGeographyLayer` nor `returnSubGeographyLayer`?

**Comment by haseebanwar** [comment]
Yes enrich doesn't have those but if you see [here](https://github.com/Esri/arcgis-rest-js/blob/master/packages/arcgis-rest-demographics/src/helpers.ts#L12) there is a rest URL for Standard Geographic Query. Also, the method `queryDemographicData` accepts `endpoint` as argument. If I am passing https://geoenrich.arcgis.com/arcgis/rest/services/World/geoenrichmentserver/StandardGeographyQuery as the endpoint, the function is returning 404.

How can I make a Standard Geography Query using the library?

**Comment by gavinr** [comment]
Ok, I think you want https://esri.github.io/arcgis-rest-js/api/demographics/getGeography/

Note that you can generally find out the REST endpoint that is being used by a particular ArcGIS REST JS function by clicking the link `REST Documentation`

![image](https://user-images.githubusercontent.com/209355/108376720-2b2c8500-71fb-11eb-8af2-a0d679760a56.png)

**Comment by haseebanwar** [comment]
Got it, thanks so much for your quick support
