### ISSUE TITLE
New geocode URL requires token

### ISSUE THREAD

**Issue by yankuanz** [Esri/arcgis-rest-js#803]
In our app we recently encountered a regression when using `suggest` and `geocode` (we used to make the these requests without passing in any `authentication`) because of the change of the default geocode URL https://github.com/Esri/arcgis-rest-js/commit/613837ddaa0638f826aa75d11c00ee1007cb6e72:

![image](https://user-images.githubusercontent.com/31449467/108572904-34cfee80-72c8-11eb-9cae-9f0e8a6fc7ec.png)

Would assume everthing should just work before and after the URL update. Is this expected?

---

So once we did pass in this time, we got another error 

![image](https://user-images.githubusercontent.com/31449467/108573025-7f516b00-72c8-11eb-8101-4dc742cb9c5c.png)

Note that we are making the requests from devext tier. Is this also expected? What would be best practice in here?

Thanks!

**Comment by vicb** [comment]
Hum I am getting this error and can not find anything in the docs!

**Comment by vicb** [comment]
It seems like you should use [`setDefaultRequestOptions`](https://esri.github.io/arcgis-rest-js/api/request/setDefaultRequestOptions/) and pass the `token` value in the `params`

**Comment by yankuanz** [comment]
> It seems like you should use [`setDefaultRequestOptions`](https://esri.github.io/arcgis-rest-js/api/request/setDefaultRequestOptions/) and pass the `token` value in the `params`

Thanks @vicb . Will give a shot!

**Comment by vicb** [comment]
Here is what I use successfuly:

```typescript
import { geocode } from '@esri/arcgis-rest-geocoding';
import { setDefaultRequestOptions } from '@esri/arcgis-rest-request';

setDefaultRequestOptions({ params: { token: "...your API key..." } });
const { candidates } = await geocode(address);
```
