### ISSUE TITLE
Broken link to browser-based login image in documentation

### ISSUE THREAD

**Issue by MikeTschudi** [Esri/arcgis-rest-js#804]
On page https://esri.github.io/arcgis-rest-js/guides/browser-authentication/, the link to "browser-based login" is broken:
![image](https://user-images.githubusercontent.com/2125181/108599623-21179d00-7347-11eb-8176-5f4f799964d6.png)

Should this link be removed, or will this image do the job: https://developers.arcgis.com/documentation/static/5a68e29d341f1a1e7641b6bc289c9c2f/4cdf7/4-oauth-screen.png?

**Comment by jf990** [comment]
Image referenced above has been taken down, we just published updated Security and Authentication docs with new images

https://developers.arcgis.com/documentation/mapping-apis-and-services/security/arcgis-identity/serverless-web-apps/
