### ISSUE TITLE
Confusion about layers and tables types in IFeatureServiceDefinition

### ISSUE THREAD

**Issue by sandromartis** [Esri/arcgis-rest-js#808]
I'm struggling to understand the types inside `IFeatureServiceDefinition`.

In  [`IFeatureServiceDefinition`](https://esri.github.io/arcgis-rest-js/api/types/IFeatureServiceDefinition/):
- layers are of type: `ILayerDefinition[] | ILayerDefinition`
- tables are of type: `ITable[] | ITable`

Why are tables not of type `ILayerDefinition[] | ILayerDefinition` as well?

My issue is that `ILayerDefinition` has `id` with type `number`, but `ITable` has `id` with type `string`.

So when I use [`getService`](https://esri.github.io/arcgis-rest-js/api/feature-layer/getService/) to get the feature service definition, I will get quite a mix of types when extracting `layers` and `tables`.

If I call the feature service directly I seem to be getting the same data structure for both layers and tables so I'm not sure why they have different types:
https://developers.arcgis.com/rest/services-reference/feature-service.htm

Could you shed some light on this? Are these types correct? :)

**Comment by tomwayson** [comment]
It looks like `ITable.id` should be a number. It _might_ have been defined as a `string` by mistake. I'd accept a PR that updates the definition.

**Comment by sandromartis** [comment]
Sounds good, I can do a PR for that 👍
