### ISSUE TITLE
arcgis-rest-request should expose the `signal` option of the underlying `fetch` call

### ISSUE THREAD

**Issue by thw0rted** [Esri/arcgis-rest-js#810]
If I'm reading [the `request` method](https://github.com/Esri/arcgis-rest-js/blob/master/packages/arcgis-rest-request/src/request.ts#L253) correctly, there doesn't seem to be a way to pass arbitrary options to the underlying `fetch` call, and the method itself doesn't take an AbortSignal in the options argument.  Passing this parameter would allow callers to [cancel long-running API calls](https://developer.mozilla.org/en-US/docs/Web/API/AbortSignal#examples) when needed, and has had broad support in modern browsers for several years now.

Once supported by `request`, it should also be added to other ArcGIS packages that depend on it, like `arcgis-rest-feature-layer`, etc.

**Comment by jgravois** [comment]
I probably shouldn't have closed out #114

**Comment by thw0rted** [comment]
Crud, sorry, I searched for "AbortSignal" but not "AbortController".  Would it be better to close this issue and re-open that one, since it has some extra context?

As an aside, IIRC user-agents that don't support `signal` are allowed to just ignore it, so if you use a non-standard `fetch` that doesn't already support `signal`, that's fine.  As I understand it, sending an abort signal means you'd like to (maybe, please, if you can) abort the call, but it's not guaranteed.

**Comment by jgravois** [comment]
continuing to track via this issue is fine, but in 2021 that the status is still 'a PR would be welcome'.

**Comment by patrickarlt** [comment]
This will be included in the 4.0.0 release. Currently on the `beta` branch.
