### ISSUE TITLE
Enh: support ArcGIS Online 9.1 credentials

### ISSUE THREAD

**Issue by MikeTschudi** [Esri/arcgis-rest-js#816]
Credentials in ArcGIS Online &ge;9.1 do not include the `expires` or `ssl` properties. This is a breaking change for arcgis-rest-js that prevents tokens from being fetched or refreshed.

The arcgis-rest-js, the search code calls `getFreshToken`. Even though a token exists inside `UserSession`, the missing expiration date prevents `UserSession` from returning that value, and so `getFreshToken` returns an entry on its `_pendingTokenRequests` while it tries to refresh the token. But the refresh fails because the `refreshToken` inside `UserSession` is not defined:
![image](https://user-images.githubusercontent.com/2125181/110954150-0492d300-82fd-11eb-8f54-b5895b395cb5.png)

A test page for reproducing the problem in Chrome and Firefox is shown below. It offers buttons to sign in and out; after signin, it lists the account name and the number of items owned by that account. (*Note that an appId for your system needs to be supplied on line 33.*)

The page as-is will only show the count of public items because line 45 (`credential.expires = undefined;`) emulates what the ArcGIS Online 9.1 authorization returns as a credential that we supply to arcgis-rest-js' `UserSession.fromCredential`. Comment out line 45 to emulate the ArcGIS Online 8.4 credential, and you will see a count that includes private items.

```html
<!doctype html>
<html lang="en" dir="ltr">
<head>
  <meta http-equiv="content-type" content="text/html; charset=utf-8" />
  <script>
    var dojoConfig = {
      "paths": {
        "@esri/arcgis-rest-auth": "https://unpkg.com/@esri/arcgis-rest-auth@3.0.2/dist/umd/auth.umd",
        "@esri/arcgis-rest-portal": "https://unpkg.com/@esri/arcgis-rest-portal@3.0.2/dist/umd/portal.umd",
        "@esri/arcgis-rest-request": "https://unpkg.com/@esri/arcgis-rest-request@3.0.2/dist/umd/request.umd"
      }
    }
  </script>
  <script src="https://js.arcgis.com/4.19/dojo/dojo.js"></script>
</head>
<body>
  <button id="signinBtn" onclick="signinFcn()" disabled>Sign in</button>
  <button id="signoutBtn" onclick="signoutFcn()" disabled>Sign out</button>
  <br/><br/>
  <div id="info"></div>

  <script>
    var signinFcn, signoutFcn;

    require(["esri/config", "esri/identity/IdentityManager", "esri/identity/OAuthInfo", "@esri/arcgis-rest-auth", "@esri/arcgis-rest-portal"],
      function (esriConfig, IdentityManager, OAuthInfo, auth, portal) {
        signinFcn = signin;
        signoutFcn = signout;
        const portalUrl = "https://www.arcgis.com";

        esriConfig.portalUrl = portalUrl;
        const info = new OAuthInfo({
          appId: "<insert appId>",  // supply an appId
          popup: false,
          portalUrl: portalUrl,
          preserveUrlHash: true
        });
        IdentityManager.useSignInPage = false;
        IdentityManager.registerOAuthInfos([info]);
        IdentityManager.checkSignInStatus(portalUrl + "/sharing").then(
          credential => {
            document.getElementById("signinBtn").disabled = true;
            document.getElementById("signoutBtn").disabled = false;

            credential.expires = undefined;  // as-is: ArcGIS Online 9.1; commented-out: ArcGIS Online 8.4

            const userSession = auth.UserSession.fromCredential(credential);
            console.log("Signed in", JSON.stringify(credential, null, 2), JSON.stringify(userSession, null, 2));

            const searchOptions = {
              q: "owner:" + credential.userId,
              authentication: userSession,
              portal: portalUrl + "/sharing/rest"
            };
            portal.searchItems(searchOptions)
            .then(
              results => {
                document.getElementById("info").innerHTML =
                  "Signed in as " + credential.userId + "<br>" + results.total + " items found in account";
              }
            );

          },
          error => {
            document.getElementById("signinBtn").disabled = false;
            document.getElementById("signoutBtn").disabled = true;
            console.log("Not signed in", JSON.stringify(error, null, 2));
            document.getElementById("info").innerHTML = "Not signed in";
          }
        );

        function signin() {
          IdentityManager.getCredential(portalUrl + "/sharing")
          .then(
            () => {
              window.location.reload();
            }
          );
        }

        function signout() {
          IdentityManager.destroyCredentials();
          window.location.reload();
        }
      }
    );
  </script>
</body>
</html>
```

---

Changing `fromCredential` line
```ts
tokenExpires: new Date(credential.expires),
```
to
```ts
tokenExpires: credential.expires ? new Date(credential.expires) : undefined
```
solves the problem.

**Comment by dbouwman** [comment]
Great sleuthing @MikeTschudi! 

I do have a question though - did your research find that the platform (i.e. /oauth2/authorize) is no longer returning the `.expires` or `.ssl` properties? or the JSAPI's IdentityManager is no longer returning these properties? I'm asking because (to date) we have not run into issues in Hub against 9.1, and we rely on rest-js UserSession.
 
I looked at the PR your submitted - which solves this particular case, but the `.expires` property is used in plenty of other places, so if it's no longer set by the platform at all, then we will need a more holistic solution. 

If it's just not returned by the JSAPI, maybe we can ask @dasa for more background?

**Comment by dbouwman** [comment]
Additional background via @dasa email
> I’m not sure where the esri_auth cookie cookie on devext is coming from, but JS API 4.19 does not try to read it. If Id Manager can’t find esriJSAPIOAuth, it’ll try to get the token by calling /sharing/rest/oauth2/platformSelf. If this succeeds, the credential that is returned does not have ssl or expires values. Are either of these required by REST JS? They’re not required by Id Manager, and /platformSelf did not initially return expires. It does now, but since it’s not required, Id Manager has not been updated to read expires.
 
So - it seems like REST-JS needs to decide how to handle this scenario... without breaking anything... I'm on vacation this week, but I think we need a holistic solution for `.expires === undefined`

**Comment by MikeTschudi** [comment]
Dasa pointed out that "A token can fail at anytime, for example, if it’s revoked or the user changes their password."  The Identity Manager "...for a new one when the existing one fails."  REST-JS is already prepared.

Most importantly, however, is that with the in-progress ArcGIS Online 9.1 release, ***REST-JS will not work at all with credentials supplied by the platform.***  So a solution is urgently needed because 9.1 is already in QA testing. Can we please create a REST-JS release with this patch now, and investigate a holistic solution in parallel?

**Comment by tomwayson** [comment]
Is this issue resolved now @MikeTschudi ?

**Comment by MikeTschudi** [comment]
Verified in ArcGIS Online 9.1 dev and qa testing.
Thank you for the reminder, @tomwayson
