### ISSUE TITLE
geocodeAddresses always returns "User does not have permissions to store geocoding results."

### ISSUE THREAD

**Issue by sepehr500** [Esri/arcgis-rest-js#828]
I am trying to make a request to the geocodeAddresses endpoint using the `bulkGeocode` function in the `@esri/arcgis-rest-geocoding` package. No matter what I do it always returns "User does not have permissions to store geocoding results." even when I pass `forStorage=false` into the params. I have verified the correct param is being passed to the service. Is this a bug?

**Comment by jgravois** [comment]
bulk geocoding always required authentication because it is always paid.

https://developers.arcgis.com/rest/geocode/api-reference/geocoding-free-vs-paid.htm

**Comment by jf990** [comment]
@sepehr500 Which [Authentication method](https://developers.arcgis.com/documentation/mapping-apis-and-services/security/#authentication-methods) are you using? Your token may not have the `forStorage` scope set on it?

**Comment by sepehr500** [comment]
I spoke to support and turns out bulk geocode is always assumed to be stored and you can't turn it off even with forStorage set to false. Still trying to figure out if that's on purpose.

**Comment by jgravois** [comment]
the endpoint is ignoring your attempt to set `forStorage` because its not a valid parameter for `geocodeAddresses`.

https://developers.arcgis.com/rest/geocode/api-reference/geocoding-geocode-addresses.htm
