### ISSUE TITLE
ILayerDefinition "geometryType" field can be "esriGeometryMultiPatch"

### ISSUE THREAD

**Issue by thw0rted** [Esri/arcgis-rest-js#832]
I don't expect the library to support consuming the binary MultiPatch encoding natively, but it's possible for [a layer definition](https://services.arcgis.com/V6ZHFr6zdgNZuVG0/ArcGIS/rest/services/LABuildings_3D/FeatureServer/0) to come back with the subject value for the `geometryType` field.  The typings for the `ILayerDefinition` interface should reflect this.

(For such layers, it's possible to specify `multipatchOption: "xyFootprint"` and get back `esriGeometryPolygon` features instead, which are easier to work with.)

**Comment by gavinr** [comment]
Hi, thank you for the report. Just to clarify, you are proposing that we add:

```
geometryType?: string;
```

to this interface: https://github.com/Esri/arcgis-rest-js/blob/c4f62d806facb9d74f8c64c6579e7b94388d57aa/packages/arcgis-rest-feature-service/src/helpers.ts#L683-L813 ?

**Comment by thw0rted** [comment]
It's been a while but I think I was saying that the `GeometryType` enumeration should include the string literal `esriGeometryMultiPatch` in addition to the other strings.

**Comment by gavinr** [comment]
Ah, yes - you're right, `geometryType` is already in that interface. So the request is to add `esriGeometryMultiPatch` to https://github.com/Esri/arcgis-rest-js/blob/c4f62d806facb9d74f8c64c6579e7b94388d57aa/packages/arcgis-rest-request/src/types/geometry.ts#L173. Thank you!

**Comment by patrickarlt** [comment]
@gavinr looks like your last comment got a 👍🏻 . Do you want to implement this?
