### ISSUE TITLE
Refresh token expiration is not accurate

### ISSUE THREAD

**Issue by hogpilot** [Esri/arcgis-rest-js#842]
In a `UserSession` object (specifically with an `authorize` workflow), the `refreshTokenTTL` property is what drives the expiration time of the refresh token (`refreshTokenExpires`).  There are a couple issues with this:

1. It is set directly via the constructor options (`refreshTokenTTL`), or defaulted to `1440`.  This seems to only be used internally to the `UserSession` object and not know by ArcGIS API calls.

    * It isn't representative of when the refresh token actually expires, which is described [here](https://developers.arcgis.com/rest/users-groups-and-items/authorize.htm) as defaulting to `20160` (2 weeks) or as specified in the `expiration` parameter of the  `ouath2/authorize` API call

    * This will cause an unhandled exception [here](https://github.com/Esri/arcgis-rest-js/blob/e59e49968ae9bc88c76035e81aaffc9c971080f1/packages/arcgis-rest-auth/src/UserSession.ts#L1267) and [here](https://github.com/Esri/arcgis-rest-js/blob/e59e49968ae9bc88c76035e81aaffc9c971080f1/packages/arcgis-rest-auth/src/UserSession.ts#L1291) when the refresh token actually has expired, but `UserSession` *thinks* it is still valid.
   
2. It is [initially](https://github.com/Esri/arcgis-rest-js/blob/e59e49968ae9bc88c76035e81aaffc9c971080f1/packages/arcgis-rest-auth/src/UserSession.ts#L579) treated as "number of seconds", but then [later](https://github.com/Esri/arcgis-rest-js/blob/e59e49968ae9bc88c76035e81aaffc9c971080f1/packages/arcgis-rest-auth/src/UserSession.ts#L1297) on (after a call to `refreshSession`) as "number of minutes".

This can be reproduced by waiting at least 30 minutes (the default accest token duration) between initial creation and refresh (due to #840, you can't currently set the expiration with `arcgis-rest-js`).

Once that issue is fixed, then reproducing it can be done more quickly by specifying a `duration` of `1` when creating a new `UserSession` (authorize) instance... waiting a minute, then trying to call `refreshSession`.

**Comment by mpayson** [comment]
Ref #704 too, it's gone stale but I think it tackles this

**Comment by patrickarlt** [comment]
This will be resolved at v4 which is currently on the beta branch.
