### ISSUE TITLE
Switch from tslint

### ISSUE THREAD

**Issue by gavinr** [Esri/arcgis-rest-js#844]
from [the tslint website](https://palantir.github.io/tslint/):

> TSLint has been deprecated as of 2019. Please see this issue for more details: Roadmap: TSLint → ESLint. typescript-eslint is now your best option for linting TypeScript.

I propose switching to [typescript-eslint](https://github.com/typescript-eslint/typescript-eslint). Thoughts/comments?

**Comment by COV-GIS** [comment]
I think that's a great idea @gavinr.

`tslint-config-prettier` can be switched out for `eslint-config-prettier`. `tslint-config-standard` can be removed.

And both can be configured via simple JSON in `package.json` instead of extra config files in the root.

**Comment by gavinr** [comment]
Closed via #863
