### ISSUE TITLE
Switch to npm local paths

### ISSUE THREAD

**Issue by gavinr** [Esri/arcgis-rest-js#873]
[This article](https://www.linkedin.com/pulse/things-i-wish-had-known-when-started-javascript-monorepo-gorej/), discusses a more modern way to configure our package dependencies:

> By introducing npm local paths, a lot of Lerna complex commands are no longer necessary to use. Plain old npm install suffice to setup the entire monorepo

Part 1 of this would be to update the dependencies in the `package.json` file for each package (for example [here](https://github.com/Esri/arcgis-rest-js/blob/af59dcdbc24cca2486664a69083f462cb9a9b363/packages/arcgis-rest-auth/package.json#L16)) per this example:

![image](https://user-images.githubusercontent.com/209355/123325085-210ef000-d527-11eb-9b8e-ba152225f104.png)

The next step would be to update the main [`package.json`](https://github.com/Esri/arcgis-rest-js/blob/af59dcdbc24cca2486664a69083f462cb9a9b363/package.json) file to reference all the packages per this example:

![image](https://user-images.githubusercontent.com/209355/123324991-03da2180-d527-11eb-9b89-867193b82571.png)

Finally, after all these changes, we can now remove the [`lerna bootstrap` step](https://github.com/Esri/arcgis-rest-js/blob/af59dcdbc24cca2486664a69083f462cb9a9b363/package.json#L112-L113) from the `postinstall` script since it's no longer necessary.

Just throwing this out there for initial feedback and comments. It seems like doing this is now the "more proper" way to do things, and in theory might speed up the `npm install` process.

**Comment by patrickarlt** [comment]
@gavinr not sure if https://github.com/Esri/arcgis-rest-js/pull/911 handles this or not. You might want to take a look.

**Comment by gavinr** [comment]
I think #911 cleans things up in a different way, using the workspaces stuff, so let's close this for now and come back to it after the dust settles from the next major release if it still is applicable.
