### ISSUE TITLE
Cannot use library, types are missing: 

### ISSUE THREAD

**Issue by luchianvictor** [Esri/arcgis-rest-js#878]
1. Installed these packages in a node js typescript application:
"@esri/arcgis-rest-auth": "^3.2.1",
"@esri/arcgis-rest-geocoding": "^3.2.1",
"@esri/arcgis-rest-request": "^3.2.1"
2. Tried following example usecase: 

```
import {
    bulkGeocode,
    geocode,
    getGeocodeService,
    reverseGeocode,
    suggest,
} from "@esri/arcgis-rest-geocoding";

const x = await suggest('Starb');
console.log({ x });
const y = await geocode('test');
console.log({ y });
```

When trying to compile the application, I get the following typescript compiling errors: 
```

node_modules/@esri/arcgis-rest-request/dist/esm/utils/IAuthenticationManager.d.ts:21:41 - error TS2304: Cannot find name 'RequestCredentials'.

21     getDomainCredentials?(url: string): RequestCredentials;
                                           ~~~~~~~~~~~~~~~~~~

node_modules/@esri/arcgis-rest-request/dist/esm/utils/IRequestOptions.d.ts:38:21 - error TS2304: Cannot find name 'RequestInfo'.

38     fetch?: (input: RequestInfo, init?: RequestInit) => Promise<Response>;
                       ~~~~~~~~~~~

node_modules/@esri/arcgis-rest-request/dist/esm/utils/IRequestOptions.d.ts:38:41 - error TS2304: Cannot find name 'RequestInit'.

38     fetch?: (input: RequestInfo, init?: RequestInit) => Promise<Response>;
                                           ~~~~~~~~~~~

node_modules/@esri/arcgis-rest-request/dist/esm/utils/IRequestOptions.d.ts:38:65 - error TS2304: Cannot find name 'Response'.

38     fetch?: (input: RequestInfo, init?: RequestInit) => Promise<Response>;
                                                                   ~~~~~~~~

node_modules/@esri/arcgis-rest-request/dist/esm/utils/IRequestOptions.d.ts:42:19 - error TS2304: Cannot find name 'RequestCredentials'.

42     credentials?: RequestCredentials;
                     ~~~~~~~~~~~~~~~~~~

node_modules/@esri/arcgis-rest-request/dist/esm/utils/ITokenRequestOptions.d.ts:7:21 - error TS2304: Cannot find name 'RequestInfo'.

7     fetch?: (input: RequestInfo, init?: RequestInit) => Promise<Response>;
                      ~~~~~~~~~~~

node_modules/@esri/arcgis-rest-request/dist/esm/utils/ITokenRequestOptions.d.ts:7:41 - error TS2304: Cannot find name 'RequestInit'.

7     fetch?: (input: RequestInfo, init?: RequestInit) => Promise<Response>;
                                          ~~~~~~~~~~~

node_modules/@esri/arcgis-rest-request/dist/esm/utils/ITokenRequestOptions.d.ts:7:65 - error TS2304: Cannot find name 'Response'.

7     fetch?: (input: RequestInfo, init?: RequestInit) => Promise<Response>;
                                                                  ~~~~~~~~

node_modules/@esri/arcgis-rest-request/dist/esm/utils/encode-form-data.d.ts:7:79 - error TS2304: Cannot find name 'FormData'.

7 export declare function encodeFormData(params: any, forceFormData?: boolean): FormData | string;
                                                                                ~~~~~~~~


Found 9 errors.

error Command failed with exit code 2.
```

**Comment by gavinr** [comment]
Hi, thank you for the report. Could you please share the specific replication steps to get these errors?

**Comment by luchianvictor** [comment]
hi @gavinr, thanks for your response. I created a new typescript project to isolate this issue: 
my `package.json` 

{
  "name": "node_project",
  "version": "1.0.0",
  "description": "",
  "main": "dist/app.js",
  "scripts": {
    "start": "tsc -p . && node dist/app.js"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "tslint": "^5.12.1",
    "typescript": "4.3.5"
  },
  "dependencies": {
    "@esri/arcgis-rest-auth": "^3.2.1",
    "@esri/arcgis-rest-geocoding": "^3.2.1",
    "@esri/arcgis-rest-request": "^3.2.1"
  }
}

my `tsconfig.json`

{
  "compilerOptions": {
    "target": "es2015",
    "module": "commonjs",
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "sourceMap": true,
    "lib": [
      "es2017"
    ],
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "suppressImplicitAnyIndexErrors": true,
    "allowSyntheticDefaultImports": true
  }
}

`tslint.json`

{
    "defaultSeverity": "error",
    "extends": [
        "tslint:recommended"
    ],
    "jsRules": {},
    "rules": {},
    "rulesDirectory": []
}

`src/app.ts`

import {
  geocode,
  suggest,
} from "@esri/arcgis-rest-geocoding";

(async () => {
  const x = await suggest('Starb');
  console.log({ x });
  const y = await geocode('test');
  console.log({ y });

})();

commands: 
`npm install`
`npm start`

**Comment by gavinr** [comment]
Thanks for this. I'm not quite sure if this is a perfect solution, but here's what I did to get it working:

1. Add `"skipLibCheck": true` to tsconfig.json. 
2. run `npm install @types/node --save-dev` to get your `console.log`s not to error
3. Installed cross-fetch and isomorphic-form-data for the global polyfills per https://esri.github.io/arcgis-rest-js/guides/node/

**Comment by luchianvictor** [comment]
Ok, seems like this solved my issue. Thank you!
