### ISSUE TITLE
Specifying API key for queryFeatures or updateFeatures

### ISSUE THREAD

**Issue by galvarez421** [Esri/arcgis-rest-js#881]
Hello, how do I specify an API key for `queryFeatures` or `updateFeatures` from `@esri/arcgis-rest-feature-layer`? I see that both accept an `authentication` option of type `IAuthenticationManager`, but that type seems to support only https://esri.github.io/arcgis-rest-js/api/auth/UserSession/ and https://esri.github.io/arcgis-rest-js/api/auth/ApplicationSession/ per https://esri.github.io/arcgis-rest-js/api/request/IAuthenticationManager/, and I am not seeing how to set an API key using either of those. It seems https://esri.github.io/arcgis-rest-js/api/auth/ApiKey/ also implements the type `IAuthenticationManager` although I don't see that as a supported class in the documentation for `IAuthenticationManager`. Is the documentation for `IAuthenticationManager` perhaps outdated or incomplete? Thank you!

**Requested issue details from `CONTRIBUTING.md` template:**

- Browser (or Node.js) version: Haven't experienced an issue in a specific environment -- just wondering about the API.
- A snippet of code: In general, any code making use of `queryFeatures` or `updateFeatures` from `@esri/arcgis-rest-feature-layer` package with a REST service that is set up to use API key authentication.
- What I saw: Haven't experienced an issue specifically -- just wondering about the API.
- What I expected to see: API to include `ApiKey` as a supported class for `IAuthenticationManager`.

**Comment by gavinr** [comment]
Thank you for the question Gerry. 

## updateFeatures using an API Key

> how do I specify an API key for `queryFeatures` or `updateFeatures` from `@esri/arcgis-rest-feature-layer`

Per the documentation, 

> Only ArcGIS Developer accounts can use API keys to **read** private content.

https://developers.arcgis.com/documentation/mapping-apis-and-services/security/api-keys/#access-content-and-items

So `updateFeatures` will not be available for API Keys. 

## queryFeatures using an API Key

Querying private content using an API Key should be possible (it's currently in beta as of 2021-07-30 [per the documentation](https://developers.arcgis.com/documentation/mapping-apis-and-services/security/api-keys/#access-content-and-items)). 

The typescript types may not indicate it, but you can pass an `ApiKey` instance to the `authentication` property of `queryFeatures` and it should work, like this:


```js
import { ApiKey } from "https://cdn.skypack.dev/@esri/arcgis-rest-auth";
import { queryFeatures } from "https://cdn.skypack.dev/@esri/arcgis-rest-feature-layer";

const apiKey =
  "YOUR API KEY";

const authentication = new ApiKey({
  key: apiKey // from https://developers.arcgis.com ... to access content, see https://developers.arcgis.com/documentation/mapping-apis-and-services/security/api-keys/#access-content-and-items for details
});

queryFeatures({
  url:
    "https://YOUR_PRIVATE_SERVICE_URL/arcgis/rest/services/xyz/FeatureServer/0",
  where: "1=1",
  authentication
}).then(
  (response) => {
    console.log("Results:", response);
  },
  (err) => {
    console.error("Error:", err);
  }
);
```

([full example](https://codepen.io/gavinr/pen/PomeBXe?editors=0010))

Once this feature comes out of beta, we should update the TypeScript types to better reflect this. Lets leave this issue open to track that.

**Comment by galvarez421** [comment]
Thank you for the quick response and clarification!

Given that `updateFeatures` cannot be used with an API key, would application credentials be the next best option for me if I am trying to enable a web application to query and update features? API keys seemed like exactly what I was looking for based on https://developers.arcgis.com/documentation/mapping-apis-and-services/security/#choosing-an-authentication-method and my requirements and preferences:

1. No server-side code, i.e., the ability to safely specify/expose the API key in JS code. My understanding is that I can do this with an API key so long as the referrers for the key are properly configured.
2. Do not require end user to authenticate.

**Comment by gavinr** [comment]
If you do not want to require the end user to authenticate, you essentially want anyone to be able to edit (anonymous editing). In this case, I would recommend enabling editing and setting the sharing access to "Public":

![image](https://user-images.githubusercontent.com/209355/127869268-36c64b90-33d9-4112-b4b9-577e6f96354b.png)

**Comment by galvarez421** [comment]
Hi @gavinr thank you for the response! I maybe wasn't clear or maybe I am misunderstanding! By end user I mean a user of the web application UI that I am working on. I would like the web app itself to be authorized to query and edit, but only that web app, as opposed to any web app with knowledge of the URL. In other words, I don't want users of the web application UI to have to authenticate (e.g., via the authorization page shown in https://developers.arcgis.com/documentation/mapping-apis-and-services/security/#arcgis-identity), but I do want to require authentication for applications.

**Comment by arielhasidim** [comment]
Is there anyway I can edit Feature Layer only with authenticated request and keep it publicly open for reading-only (for example with updateFeature or applyEdits methods)?
@gavinr

**Comment by gavinr** [comment]
This thread is getting off topic, so I'm closing. @arielhasidim please ask questions general question about Feature Layer settings in the Esri Community:  https://community.esri.com/t5/arcgis-online/ct-p/arcgis-online or https://community.esri.com/t5/arcgis-rest-js/ct-p/arcgis-rest-js
