### ISSUE TITLE
Add a static `UserSession.signIn()` method for username/password auth

### ISSUE THREAD

**Issue by gavinr** [Esri/arcgis-rest-js#887]
To be consistent with using _static_ methods on the `UserSession` class.

**Comment by tomwayson** [comment]
To clarify, this method takes `username: string, password: string`, as arguments, right?

Thoughts on naming:

The REST API docs seem to use "sign in" and "sign out":

- ["Keep me signed in"](https://developers.arcgis.com/rest/users-groups-and-items/authorize.htm)
- ["when a user signs out"](https://developers.arcgis.com/rest/users-groups-and-items/revoke-token.htm)

https://developers.arcgis.com/rest/users-groups-and-items/revoke-token.htm

So, I wonder if we name this `UserSession.signIn(username, password)`?

**Comment by patrickarlt** [comment]
@gavinr I also think we discussed:

```js
   const session = await UserSession.fromToken({
     token
     tokenExpires // optional
     username  // optional
     portal // optional, defaults to online, required for enterprise
   });
```

I think this as to be async since TONS of existing modules rely on a syncronsous read of `session.username` so we either fix all those methods OR just make this async to populate `username` before returning the session.

**Comment by patrickarlt** [comment]
Closing this. This will be part of the upcoming 4.0 release.
