### ISSUE TITLE
Allow authentication with only a token

### ISSUE THREAD

**Issue by gavinr** [Esri/arcgis-rest-js#889]
Allow API calls to be made by bringing your own token (or token+user name).

We had discussed internally:

> The option to have an  `authentication` option on request to accept a `string` which will be passed directly to the `token`.

**Comment by patrickarlt** [comment]
@gavinr I want to think about how we can warn users that they SHOULD consider using `UserSession` or `ApplicationSession` if possible. Directly using a string for authentication means that you miss out on quite a bit. For example:

1. All federation
2. All security checks. For example if you are on/not on AGOL
3. All additional error handling and checking
4. Refreshing the token

For API key (and to some degree `ApplicationSession`) this is generally OK but I would like think about this a bit if we want to handle this in just doc or if we want a warning in the actual code.

**Comment by patrickarlt** [comment]
@gavinr I'm thinking maybe introducing a new `token` option on `IRequestOptions` instead of overloading `authentication`

We could then look the `token` param and if it does not start with `AAPK` warn (once) that passing a token directly is discouraged and you consider using `UserSession` or `ApplicationSession`. Something like:

```js
if(
  options.token && // you used the token param
  !option.token.startsWith("AAPK") && // doesn't look like an API Key
  !options.suppressWarnings && // user doesn't want to suppress warnings for this request
  !globalThis.ARCGIS_REST_JS_SUPPRESS_TOKEN_WARNING // we havn't shown the user this warning yet
) {
    warn(`Using an oAuth 2.0 access token directly in the token option is discouraged. Consider using UserSession or Application session.\n\nhttp://...\n\n if you want to suppress this warning see http://...')
    globalThis.ARCGIS_REST_JS_SUPPRESS_TOKEN_WARNING = true;
}
```

Then if you wanted to suppress all warnings you could do this:

```js
import {setDefaultRequestOptions} from "@esri/arcgis-rest-request";

setDefaultRequestOptions("supressWarnings", true);
```

The opens up being able to add other warnings in the future.

**Comment by gavinr** [comment]
Sounds good to me.

**Comment by patrickarlt** [comment]
Closing this. This will be part of the upcoming 4.0 release.
