### ISSUE TITLE
Clarify the recommended ways to create UserSession

### ISSUE THREAD

**Issue by gavinr** [Esri/arcgis-rest-js#893]
Right now, [the documentation for UserSession](https://esri.github.io/arcgis-rest-js/api/auth/UserSession/) implies that the constructor (`new UserSession()`) should be used. 

After #887, the idea will be that in most cases a user should only ever call the static methods:

- `UserSession.beginOAuth2({...})`
- `UserSession.authorize({...})`
- `UserSession.login({...})` (new in #887)

.. so we should update the documentation page to make this more obvious.

**Comment by patrickarlt** [comment]
Updated in #941
