### ISSUE TITLE
Authentication manager design

### ISSUE THREAD

**Issue by patrickarlt** [Esri/arcgis-rest-js#914]
This has been bugging me since our discussion with @hogpilot in https://github.com/Esri/arcgis-rest-js/issues/893. 

We want to encourage static methods for creating `UserSession` as opposed to `new UserSession()`, I.e. `UserSession.login()`, `UserSession.beginOAuth2()`, ect... but we don't encourage them for `ApiKey` or `ApplicationSession`.

Generally we didn't cover it because ApiKey and ApplicationSession are super simple whereas `UserSession` can accept a whole range of options that are difficult to construct but this seems weird from an API perspective.

@alaframboise has pointed out in https://github.com/Esri/arcgis-rest-js/issues/786#issuecomment-917115707 that `new APIKey` from the `request` package might imply a new key is created.

Similarly there are other issues:

* We have 3 classes `APIKey`, `ApplicationSession` and `UserSession`
* We have 3 general methods of authentication https://developers.arcgis.com/documentation/mapping-apis-and-services/security/#authentication-methods API Keys, Application Credentials and ArcGIS Identity.

Should we align these?

* `APIKey` > `ApiKeyManager` - manages authentication via an API key for ArcGIS REST JS authentication
* `ApplicationSession` > `ApplicationCredentialsManager` - manages authentication via Application Credentials for ArcGIS REST JS authentication
* `UserSession` > `IdentityManager`/`ArcGISIdentityManager` - manages authentication via an ArcGIS Identity for ArcGIS REST JS. Are we concerned with having an `IdentityManager` class in ArcGIS REST JS?

Then add static methods to `ApiKeyManager`  and `ApplicationCredentialsManager` to match `IdentityManager`. The preference will be that users always use these factory methods instead of `new ...` if possible.

```js
import {
  ApiKeyManager,
  ApplicationCredentialsManager
} from "@esri/arcgis-rest-request";

const myKey = ApiKeyManager.fromApiKey("AAPK...")
const myKey = new ApiKeyManager({
  apiKey: "AAPK..."
})

request("...", {
  authentication: myKey
})
```

```js
import {
  ApplicationCredentialsManager
} from "@esri/arcgis-rest-request";


const myApp = ApplicationCredentialsManager.fromCredentials({
  clientId: "•••",
  clientSecret: "•••"
});
const myApp = new ApplicationCredentialsManager({
  clientId: "•••",
  clientSecret: "•••"
});

request("...", {
  authentication: myApp
})
```

This is also pretty backward compatible since it just renames `APIKey`, `ApplicationSession` and `UserSession` and then adds new static methods. We could just deprecate and export them.

**Comment by gavinr** [comment]
This sounds good to me.

---

> Are we concerned with having an IdentityManager class in ArcGIS REST JS?

I do think having the same name might be confusing for users who use both APIs. ... I would vote `UserSessionManager` or  `ArcGISIdentityManager` or `UserIdentityManager`

**Comment by patrickarlt** [comment]
Closing this. This will be part of the upcoming 4.0 release.
