### ISSUE TITLE
SearchQueryBuilder: Quotes make a difference for single-word terms

### ISSUE THREAD

**Issue by andrewctate** [Esri/arcgis-rest-js#916]
I have validated that a query with a single-word term not wrapped in quotes is a fuzzy match, while a term wrapped in quotes is more strict. The current [`SearchQueryBuilder`](https://github.com/Esri/arcgis-rest-js/blob/master/packages/arcgis-rest-portal/src/util/SearchQueryBuilder.ts) API instead assumes that quotes are only necessary for multi-word queries.

As an example, the following query returns an item of type `CSV Collection`.
[`(typekeywords:\"exportItem:3fb958ef52d1484d856dbada3b22f05b\" AND typekeywords:\"exportLayer:null\") AND ( (type:CSV AND typekeywords:\"spatialRefId: 3857\"))`](https://rpubs19001.ags.esri.com/portal/sharing/rest/search?f=json&q=(typekeywords%3A%22exportItem%3A3fb958ef52d1484d856dbada3b22f05b%22%20AND%20typekeywords%3A%22exportLayer%3Anull%22)%20AND%20(%20(type%3ACSV%20AND%20typekeywords%3A%22spatialRefId%3A3857%22))&num=1&sortField=modified&sortOrder=DESC)

However, when we wrap the item type in quotes, we do not get the `CSV Collection` and presumably would only see items of type `CSV`.

[`(typekeywords:\"exportItem:3fb958ef52d1484d856dbada3b22f05b\" AND typekeywords:\"exportLayer:null\") AND ( (type:"CSV" AND typekeywords:\"spatialRefId: 3857\"))`](https://rpubs19001.ags.esri.com/portal/sharing/rest/search?f=json&q=(typekeywords%3A%22exportItem%3A3fb958ef52d1484d856dbada3b22f05b%22%20AND%20typekeywords%3A%22exportLayer%3Anull%22)%20AND%20(%20(type%3A%22CSV%22%20AND%20typekeywords%3A%22spatialRefId%3A3857%22))&num=1&sortField=modified&sortOrder=DESC).

It seems like we need to provide some way to allow a client to specify whether or not a given single-word param should be a strict match. I think multi-word params always will be.

cc: @patrickarlt @tomwayson

**Comment by tomwayson** [comment]
We could either add an `options?: { strict?: Boolean }` argument to `match()`, my preference, or if that doesn't work for some reason we could add `.strictMatch()`.

**Comment by tomwayson** [comment]
As a work around, does it currently do the right thing if you pass `'"CSV"'` into `match()`?

**Comment by andrewctate** [comment]
> options?: { strict?: Boolean } argument to match()

I like this pattern best because it's extensible. But it almost seems like we should default to everything being a strict match since mult-word terms already will be. Then, we could have an option: `fuzzy?: boolean`.

> As a work around, does it currently do the right thing if you pass '"CSV"' into match()?

It appears so from the logic, but I can test.

**Comment by andrewctate** [comment]
https://github.com/Esri/arcgis-rest-js/pull/913
