### ISSUE TITLE
Extent inside of IItemAdd interface has incorrect type 

### ISSUE THREAD

**Issue by JonnyDawe** [Esri/arcgis-rest-js#921]
`version: 3.03`

The extent property inside of the IItemAdd interface is set to be number[][], but the REST API docs looks to require the extent to be either a comma separated list of numbers **or** an array of numbers [xmin,ymin,xmax,ymax] as per the [item parameters docs](https://developers.arcgis.com/rest/users-groups-and-items/common-parameters.htm)

If we pass in an extent as number[][], e.g. [[xmin,ymin],[xmax,ymax]], then the extent is incorrect in the request made to createItemInFolder, e.g.

![image](https://user-images.githubusercontent.com/59748759/134901942-42140ebb-c51e-41b4-9030-30f2dd199e33.png)

_**Note:**_
This behaviour has changed since `"@esri/arcgis-rest-portal": "2.13.1"` where previously extents of the format number[][] were correctly included in the additem request made to the portal.

Many of our existing Webmap items store the extent in their item definition as number[][], as shown in the below image, meaning we are having to write extra code to fix the definitions into number[] when publishing new webmaps which use these as a template.:
![image](https://user-images.githubusercontent.com/59748759/134904057-3e90333f-3d1a-40c4-a6c4-ead7111c47e4.png)

**Comment by gavinr** [comment]
Thanks for the report, and sorry for the delay. We plan to fix this under #1023.
