### ISSUE TITLE
why does "applyEdits" doesn't get x,y coordinates as exampled

### ISSUE THREAD

**Issue by arielhasidim** [Esri/arcgis-rest-js#937]
Hello,
On all of the official examples here: [1](https://esri.github.io/arcgis-rest-js/api/feature-layer/applyEdits/), [2](https://developers.arcgis.com/arcgis-rest-js/layers/edit-feature-data/) and [3](https://developers.arcgis.com/javascript/latest/sample-code/sandbox/?sample=editing-applyedits),
_applyEdits_ gets geometry like this: 

``geometry: { x: -120, y: 45, spatialReference: { wkid: 4326 } }`` 

or just 

``geometry: { x: -120, y: 45 }``

But when I try to pass in the example I get this error:
<img width="766" alt="Screen Shot 2021-11-09 at 10 43 10" src="https://user-images.githubusercontent.com/23483971/140891913-d7af9870-4aba-4831-8b4e-55370818f4c9.png">

When I check, _applyEdits_ gets _IFeature_, and _IFeature_ geometry gets _IGeometry_ which defined like this:
```
export interface IGeometry {
    spatialReference?: ISpatialReference;
}
```
And _ISpatialReference_ defined like this:
```
export interface ISpatialReference {
    wkid?: number;
    latestWkid?: number;
    vcsWkid?: number;
    latestVcsWkid?: number;
    wkt?: string;
    latestWkt?: string;
}
```

### Shouldn't _IFeature_ get geometry as an _IPoint_?? 

It's defined like this:
```
export interface IPoint extends IHasZM, IGeometry {
    x: number;
    y: number;
    z?: number;
}
```

**Comment by COV-GIS** [comment]
Hey @gavinr.

`IFeature[geometry]` does have a type issue. It needs to be a list of geometry types and not the shared `IGeometry`.

I won't PR b/c of the all the work going on.

It you want to fix it, it's a pretty simple.

Here's my [branch](https://github.com/COV-GIS/arcgis-rest-js/tree/fix-feature-geom-type) and associated [commit](https://github.com/COV-GIS/arcgis-rest-js/commit/fc64c99d434ed812c2c09849828a8beec8f106ae).

**Comment by arielhasidim** [comment]
> Hey @gavinr.
> 
> `IFeature[geometry]` does have a type issue. It needs to be a list of geometry types and not the shared `IGeometry`.
> 
> I won't PR b/c of the all the work going on.
> 
> It you want to fix it, it's a pretty simple.
> 
> Here's my [branch](https://github.com/COV-GIS/arcgis-rest-js/tree/fix-feature-geom-type) and associated [commit](https://github.com/COV-GIS/arcgis-rest-js/commit/fc64c99d434ed812c2c09849828a8beec8f106ae).

Look's great.
Why not PR this AS IS?

I can fork, commit and PR if you would like (I want it to be included in the official pkg for use in firebase-cloud functions).

**Comment by gavinr** [comment]
fc64c99d434ed812c2c09849828a8beec8f106ae looks good to me, thanks @COV-GIS. If you want to PR, that's fine, we can merge it upstream with our many version v4 changes.

**Comment by gavinr** [comment]
We got this in to the v4 branch in #1010. Closing. If there's still an issue after the next release, please let us know. Thanks again @COV-GIS
