### ISSUE TITLE
create example which demonstrates how to batch geocode a .csv

### ISSUE THREAD

**Issue by jgravois** [Esri/arcgis-rest-js#97]
ref: https://github.com/Esri/geoservices-js/issues/95

**Comment by mpayson** [comment]
@jgravois I'm happy to build the sample too if it'd be helpful, been eager to try this lib out

**Comment by jgravois** [comment]
that'd be great!

**Comment by phpmaps** [comment]
@jgravois @mpayson @patrickarlt so what is the minimum node.js version required to run this project?  on the project home page there is an example that uses what looks to be the promise / then() pattern, which suggests v6x.   can the sample be v8x with (async / await)?

**Comment by jgravois** [comment]
check out the Node.js getting started section in https://esri.github.io/arcgis-rest-js/guides/

the gist is that even in Node.js 8x you need to import `isomorphic-fetch` and `isomorphic-form-data` to polyfill yourself.

**Comment by mpayson** [comment]
two quick questions:

1) is the scope to create a sample in the browser for users to upload a csv and download the results, or just create a node script that writes back the output? I'm in favor of the latter since it's slightly more straight forward and could be pulled into html

2) any recommended libraries for parsing csv strings? I'm leaning towards [Papa Parse](http://papaparse.com/)

thanks!

**Comment by jgravois** [comment]
@mpayson just follow your ❤️  and you'll go far :smile:

**Comment by phpmaps** [comment]
@mpayson I would say the latter, too b/ it has simple and real value.  Though for me arcgis-rest-js is a new project that I've not explored.  If it already includes consistency in samples that show end-to-end browser to JS backend, I vote for consistency.  Never a fan of wearing a tie to a Hawaiian shirt party.   On parsers @jgravois and I had already started something with cvs-parser in the developer support repo https://github.com/Esri/developer-support/tree/master/web-js/batch-geocoding-nodejs.

**Comment by phpmaps** [comment]
@mpayson per comment above follow your heart.   I'd like to get something done here in a joint effort that leverages the polyfill part also mentioned above.  That obviously coupled with the issue GIS and batch geocoding.

**Comment by mpayson** [comment]
fyi @phpmaps started to work on this [here](https://github.com/mpayson/arcgis-rest-js/tree/mp-batch-geocode/demos/batch-geocoder)

still need to:
- [ ] write results back to csv
- [ ] annotate
- [ ] (maybe) condense duplicate requests to save credits

**Comment by jgravois** [comment]
cool! open up a PR whenever you're ready and i can take a deeper look.

**Comment by phpmaps** [comment]
@mpayson way to go on this!  I started reviewing good use of config file.  I like how it's not just a JSON doc.  I am with @jgravois, a PR would be great.  The only thing I might say to update would be the last few lines, where it seems like there may be an unnecessary then() right before the catch.  I might consider putting the console log bit directly inside where promise.all resolves.

**Comment by mpayson** [comment]
updated and first pr, would love to hear your feedback!

#105
