### ISSUE TITLE
Bug: "createFolder" does not seem to accept added "owner" request option

### ISSUE THREAD

**Issue by alexanderela** [Esri/arcgis-rest-js#971]
#### Issue description
I am trying to use the [createFolder](https://esri.github.io/arcgis-rest-js/api/portal/createFolder/) method from `@esri/arcgis-rest-portal` in such a way that when I'm logged into an admin ArcGIS Enterprise account, I can add a folder in a different user's account by passing the [optional `owner` request option](https://esri.github.io/arcgis-rest-js/api/portal/createFolder/#owner).

However, when I pass an owner name as a string value under the `owner` property, the owner property does not seem to be passed in the payload of the network request.

#### Steps to reproduce the issue

1.  Navigate to [this sample app](https://codesandbox.io/s/condescending-leakey-vx72jx?file=/src/App.js) used to recreate the bug.
2. Log in to an Enterprise account using a Portal URL and App ID
3. Enter a folder name and owner name under whose account the folder should be added.
4. See in network request that `owner` property has not been passed into request payload.

**Comment by gavinr** [comment]
Thanks for logging the issue, Alex.

For the `/createFolder` endpoint, the `owner` property does not get passed in the POST body, but instead is in the URL, per spec:
https://developers.arcgis.com/rest/users-groups-and-items/create-folder.htm

In the provided sample code, I do think that's happening correctly:
![image](https://user-images.githubusercontent.com/209355/174875428-8d275fa6-ddbc-43d9-b34f-f2c9e8149d6c.png)

So I do think that ArcGIS REST JS is probably doing the correct thing here, unless I'm missing something.
