### ISSUE TITLE
active directory / ntlm authentication with ArcGIS Enterprise

### ISSUE THREAD

**Issue by b00tsy** [Esri/arcgis-rest-js#974]
Our maintainer recently migrated our enterprise portal to AD authentication, which works well when using eg. Postman. However all our existing scripts don't work anymore and we also tested this library, which seems to not authenticate against AD / ntlm. 

Is that the case (no support for AD / ntlm) or are we doing it wrong (ie theoretically it should work)? If it's not supported: are you planning to support AD / ntlm authentication?

Both relevant examples in the guides sections seems to be "work in progress":

https://esri.github.io/arcgis-rest-js/guides/cli-authentication/
https://esri.github.io/arcgis-rest-js/guides/server-authentication/

**Comment by patrickarlt** [comment]
Generally this isn't controled by ArcGIS REST JS. It is controlled by the [`credentials`](https://developers.arcgis.com/arcgis-rest-js/api-reference/arcgis-rest-request/IRequestOptions#credentials) option which is a part of every request method. `credentials` just passes through to [the `fetch`, `Request.credentials` option](https://developer.mozilla.org/en-US/docs/Web/API/Request/credentials) so setting `credentials: 'include'` should make most things work.

If you aren't running in a browser then most of this will be no help. There is very little info about getting AD/NTLM auth working in Node JS. I'm not entirely sure it is even possible.

**Comment by b00tsy** [comment]
Hi Patrick, thanks for your response. 

I’m running server side scripts with node. I’ve seen http libraries such as axios having a customized version to handle the NTLM talk, but that looks quite outdated and would not be an option with ArcGIS REST JS (as one had to exchange the underlying request library). For me that’s fine, I just had to know whether it’s possible or not, so I’m trying to get a new user with other, supported, auth options enabled.

Issue can be closed.

**Comment by patrickarlt** [comment]
Thanks for the response @b00tsy

**Comment by b00tsy** [comment]
Another comment on the issue: it seems like that depending on the authentication method configured in the enterprise portal either the WebAdaptor in front of the portal or the portal itself handles the authentication. 

If the portal itself handles the authentication the WebAdaptor probably just passes every request to the portal allowing multiple authentication methods to be configured (eg. named user and OAuth2).

In case of ActiveDirectory ntlm is being handled by the WebAdaptor (IIS) and in that case no other authentication methods seem to be possible (cause the IIS is rejecting all requests that are not ntlm).

@patrickarlt do you have insights into the enterprise portal configuration options and confirm this or probably propose a workaround? Maybe the portal can be accessed directly without passing requests through the WebAdaptor (but still keeping ntlm via WebAdaptor)?

**Comment by b00tsy** [comment]
Comment for others facing this problem: arcGIS Portal / arcGIS Server hosts are also accessible via internal hostnames on ports 7443 / 6443 allowing to bypass the official DNS name that gets proxied through the WebAdaptor...
