### ISSUE TITLE
Entend IUser provider type to include 'apple'

### ISSUE THREAD

**Issue by anumysore5** [Esri/arcgis-rest-js#978]
As users are now allowed to sign up to StoryMaps Express using `Apple` as their social IDP, could the [IUser's provider property type](https://developers.arcgis.com/arcgis-rest-js/api-reference/arcgis-rest-portal/IUser#provider) be extended to reflect that?

**Comment by gavinr** [comment]
Thank you for this report. We are working on getting the new social IDPs in the rest documentation, then when that is done will get it into ArcGIS REST JS too.

**Comment by gavinr** [comment]
This is fixed in #1055 and should be released in a future version.
