### ISSUE TITLE
Importing UserSession from CDN

### ISSUE THREAD

**Issue by cthackt** [Esri/arcgis-rest-js#982]
I am attempting to import UserSession from the CDN provided in the documentation - https://unpkg.com/@esri/arcgis-rest-auth@3.4.3/dist/umd/auth.umd.min.js

However according to devtools UserSession is not included in the exports from that CDN.

Am I missing something?

**Comment by patrickarlt** [comment]
If you are using 3.4.3 the UMD modules from the CDN will declare an `arcgisRest` global so you will have to use `arcgisRest.UserSession`.

If you want to use `import { UserSession } from "..."` AND a CDN we started supporting that at 4.0.0 which is documented at https://developers.arcgis.com/arcgis-rest-js/install/#cdn

**Comment by patrickarlt** [comment]
Also at 4.0 `UserSession` is now `ArcGISIdentityManager` which is documented in the upgrade guide https://developers.arcgis.com/arcgis-rest-js/release-notes/upgrade-v3-v4/

**Comment by gavinr** [comment]
Closing this as resolved by Patrick's comments. If you have any other questions please feel free to follow-up. Thanks!
