### ISSUE TITLE
@esri/arcgis-rest-feature-layer addFeatures TypeError: Network request failed

### ISSUE THREAD

**Issue by AlexandrBol** [Esri/arcgis-rest-js#994]
Hi!
I'm using:
 ```
   "@arcgis/core": "4.23.7",
    "@esri/arcgis-rest-feature-layer": "3.4.3",
    "@esri/arcgis-rest-request": "4.0.3",
```
with  `"react-native": "0.66.3",` and when I'm trying to add data with `addFeatures` on Android, I'm getting next error:
```
TypeError: Network request failed
    at fetch.umd.js:535:18
    at JSTimers.js:214:18
    at _callTimer (JSTimers.js:112:7)
    at Object.callTimers (JSTimers.js:357:7)
    at MessageQueue.__callFunction (MessageQueue.js:419:27)
    at MessageQueue.js:116:12
    at MessageQueue.__guard (MessageQueue.js:370:9)
    at MessageQueue.callFunctionReturnFlushedQueue (MessageQueue.js:115:10)
    at debuggerWorker.aca173c4.js:4:902
```
At the same time on iOS all work perfectly!
I already tried to add    `android:usesCleartextTraffic="true"` to the AndroidManifext.xml, but it doesn't help

My code:
<img width="794" alt="Screenshot 2022-05-21 at 19 57 26" src="https://user-images.githubusercontent.com/26917977/169663694-21b9f727-d4c5-45cf-af12-d97f22b4b302.png">

**Comment by gavinr** [comment]
Hi, thank you for the report. Could you please provide a step-by-step simplified replication case that demonstrates the issue? Preferably in an emulator that does not require a specific Android device. Thanks!

**Comment by gavinr** [comment]
Closing due to lack of response. If you're still having issues please leave a comment.
