### ISSUE TITLE
4.x redirectUri does not support query param

### ISSUE THREAD

**Issue by qlqllu** [Esri/arcgis-rest-js#995]
When we call `beginOAuth2` with the redirectUri that has query param, after call `completeOAuth2`, it reports `invalid redirect uri` error. After dig around, we find the token endpoint needs the redirect uri to be the same with the redirct uri passed in the `beginOAuth2`, but [this line](https://github.com/Esri/arcgis-rest-js/blob/%40esri/arcgis-rest-request%404.0.3/packages/arcgis-rest-request/src/ArcGISIdentityManager.ts#L628) remove the query params, which causes the above error I think.

**Comment by patrickarlt** [comment]
As far as I can tell the spec does allow for URLs with query params so we need to respect that and that means this is a bug.
