### ISSUE TITLE
Setting SceneView.container to ' ' with drawn area in AreaMeasurement

### ISSUE THREAD

**Issue by BEJIEC** [Esri/arcgis-rest-js#997]
When set container prop of SceneView to ' ' with drawn and computed area in AreaMeasurement widget, it causes crash of view (maybe trying to update labels). Same actions with MapView don't

![image](https://user-images.githubusercontent.com/35963217/171365246-b225dc43-b9b7-46d8-828d-38edd1ff953b.png)

**Comment by gavinr** [comment]
Hi @BEJIEC. This repository is only for issues regarding **ArcGIS REST JS**. Based on your question mentioning SceneView and MapView, I think your issue is regarding the **ArcGIS API for JavaScript**.

**Comment by BEJIEC** [comment]
> Hi @BEJIEC. This repository is only for issues regarding **ArcGIS REST JS**. Based on your question mentioning SceneView and MapView, I think your issue is regarding the **ArcGIS API for JavaScript**.

Hi, noticed it's too late) I'll move it to js api repo. Thanks for reply
